
import { DialogueNode } from '../types';

export const CIVILLIAN_DIALOGUE: Record<string, string[]> = {
    general: [
        "Heard the goblins in the mines are getting bolder. Nasty little creatures.",
        "That Old Man Fitzwilliam... complains about everything, but he has a good heart.",
        "The road south to Oakhaven is dangerous. Full of bandits, they say.",
        "They say the Whispering Woods got their name 'cause the trees themselves are alive... others say it's just the wind.",
        "Some say a great treasure is buried in the swamps to the east... others say it's just mud and monsters.",
        "The smithy is always busy. Valerius is a master of his craft.",
        "Looking for work? The board in The Rusty Flagon sometimes has odd jobs.",
        "The mountains to the north are treacherous. Full of harpies and worse, I hear.",
        "A feywood log is worth a pretty penny, but getting them is the tricky part. The woods are... strange.",
        "Have you seen the ranch west of town? McGregor's got the fattest cows and the fluffiest sheep.",
        "The capital city, Silverhaven... they say the walls are made of pure silver. Don't believe a word of it, but it's a sight to see.",
        "Something about the stones in the ancient clearings... they hum with a strange energy.",
        "There are altars hidden all over the world. Places of great power for those who know how to use them.",
        "Careful with those runes. Magic is a fickle thing, and powerful.",
        "Some say a witch lives deep in the Murkwallow Swamp. I wouldn't go looking for her.",
        "The Serpent's Coil... a maze of mangroves and monsters. Only the foolish or the brave go there.",
        "The Isle of Whispers... it's a place of ghosts and forgotten gods. Not many who sail there come back.",
        "The salt flats to the west were once a great sea. Now it's just... salt. And strange creatures.",
        "Looking for adventure? You've come to the right place. Just try not to get killed.",
        "Don't forget to check your map if you get lost! It can save your skin.",
        "Always carry a tinderbox. You never know when you'll need a warm fire.",
        "A good shield can be the difference between a close call and a long walk back from your respawn point.",
        "Different monsters are weak to different attack styles. Stab, slash, or crush... it pays to know which to use.",
        "I saw an adventurer once, wearing armor that shimmered like water. Must have cost a fortune.",
        "Burying bones is a good way to train your Prayer skill. It's a bit grim, but effective.",
        "Some folks say the strongest weapons can't be smithed, but are dropped by powerful monsters.",
        "Always check the quest board in a new town. It's the best way to earn some coin and a bit of renown.",
        "Don't underestimate a good meal. A well-cooked fish can save your life in a pinch.",
        "That banker in the town square seems a bit stern, but your items are safe with him.",
        "If you see something glowing, it's either very valuable or very dangerous. Sometimes both.",
        "I've heard tales of a reclusive smith in the mountains who can forge mighty warhammers.",
        "The world is full of secrets. Keep your eyes open, and you might find something amazing.",
        "Some potions can boost your skills temporarily. Very useful for tough tasks.",
        "Don't forget to train your Defence. It's no use hitting hard if you can't take a punch.",
        "The further you travel from the main cities, the more dangerous the world becomes.",
    ],
    meadowdale: [
        "Welcome to Meadowdale! It's a quiet town, mostly. Except for the goblins.",
        "Valerius, over at the smithy, taught me everything I know about metal. Which isn't much, but he's a great teacher.",
        "The library has some fascinating old books. Librarian Alexia knows all the local history.",
        "If you're heading to the Stonebreak Mine, watch your step. The goblins have set up some crude traps.",
        "Rancher McGregor's fields to the west are a great source of wool and hides, if you're into that sort of thing.",
        "The water from the fountain is surprisingly clean. Perfect for filling up your vials.",
        "I saw a strange spirit in the woods to the north. It seemed... sad.",
        "The Rusty Flagon is a fine establishment, but the ale is a bit watered down, if you ask me.",
        "Clerk Augustus in the Town Hall seems stressed. I think the bandits on the southern road are bad for business.",
        "You'll need both copper and tin to make bronze. The mine has plenty of both.",
        "Old Man Fitzwilliam is a town treasure. A grumpy, complaining treasure.",
        "The fishing at the Murky Riverbank is decent. Lots of shrimp and sardines.",
        "A friend of mine tried to explore the depths of the mine and said he saw strange, glowing crystals.",
        "That ancient clearing in the woods gives me the creeps. The stones just... watch you.",
        "I heard a rumor that the goblin king, Grumlok, has a soft spot for shiny things.",
        "Be careful if you see a goblin with a sack. They throw rocks, and they're surprisingly accurate.",
        "You can find flax growing in the fields by McGregor's ranch. Good for making bowstrings.",
        "Valerius is looking for an apprentice. Might be worth talking to him if you're strong of arm.",
        "The fish in the local river are pretty basic. For the bigger catches, you'll need to travel further afield.",
        "The guards at the gates don't see much action, thankfully. It's a peaceful town.",
        "Need a hammer or a knife? The general store in the square should have what you need.",
        "I once found a rusty old sword near the mine. Wonder if it was worth anything.",
        "The town was founded on older ruins. You can see some of the old stonework in the library's cellar.",
        "If you're going to cook, use the range in the kitchen building. Much better than an open fire.",
        "The wind up on the plateau to the north... they say it carries the whispers of the sky gods.",
        "That's how the Gust Altar got its name, I'd wager.",
        "The path to the mountains is a treacherous one. Only for seasoned adventurers.",
        "Watch out for giant spiders in the abandoned farmstead to the south. Nasty things.",
        "A simple bronze dagger is a good first weapon to smith. Doesn't take much metal.",
        "I heard a tale of a binding altar somewhere to the west of Oakhaven, a place of foundational magic.",
    ],
    oakhaven: [
        "Welcome to Oakhaven, the craftiest town in the kingdom!",
        "If you need tools or thread, the Artisan Supplies shop has the best selection.",
        "Tanner Sven can turn any hide into workable leather, for a small fee of course.",
        "The Carved Mug has the best boar stew this side of the capital.",
        "Looking for herbs? Anise's Apothecary is the place to go. She knows all the local flora.",
        "The King's Road to the west used to be a major trade route. Now, the bridge is out and it's full of highwaymen.",
        "Bronn the Retired Adventurer in the tavern has some wild stories. Half of them might even be true.",
        "They say the harpies in the Gale-Swept Peaks have feathers sharp as steel. Might be useful for fletching.",
        "I've heard you can find yew trees high up in the mountains, but it's a dangerous climb.",
        "The local wishing well is said to grant good fortune to those who are patient.",
        "Need to make potions? You'll need a pestle and mortar to grind your ingredients. The supply shop has them.",
        "The woods to the west are full of boars and bears. Good for hunting, if you're brave enough.",
        "Some say the gems found in the mines have magical properties when enchanted.",
        "I saw a strange, shimmering stag in the hills. It vanished before I could get a closer look.",
        "The wood from the Feywood is said to be naturally magical. Bows made from it are incredibly powerful.",
        "Watch out for the swamp monsters. They're slow, but they hit like a falling rock.",
        "Guard Captain Elara is worried about the capital. Says the roads need to be secured.",
        "If you're a ranger, you'll want to visit Oakhaven. We have the best fletching supplies.",
        "Making your own armor from hides is a great way to save coin.",
        "The Sunken Lands are a dangerous place. Full of horrors and ancient ruins.",
        "Some of the local fishermen talk of a hidden pond, teeming with fish, up in the hills.",
        "The local guard are always looking for brave souls to clear out the bandit camps.",
        "You can make your own bowstrings by spinning flax on a spinning wheel. There's one in McGregor's barn, and another in Silverhaven.",
        "A good crushing weapon is best for dealing with armored foes, like those golems I've heard about.",
        "The local artisans can teach you a lot about crafting, for the right price.",
        "The ruins in the Tanglewood are said to be haunted by spirits of the forest.",
        "Need gold for jewelry? You'll have to find a gold mine. They're not common around here.",
        "The best trout are in the clearwater streams, not the murky rivers.",
        "A retired adventurer told me a goblin king's weakness is his love for treasure. A well-placed bribe, perhaps?",
        "Watch out for the giant hornets in the western woods. Their sting is no joke.",
    ],
    silverhaven: [
        "Welcome to Silverhaven, the heart of the kingdom!",
        "If you want to hunt the most dangerous beasts, you must speak with Kaelen, the Slayer Master, at the Spire.",
        "The Grand Bank here is the most secure place in the world to store your valuables.",
        "The Gilded Hammer Armory sells the finest plate armor, but it'll cost you a mountain of gold.",
        "The ferry to the Isle of Whispers leaves from the docks. A one-way trip, for some.",
        "I saw a strange, lighter-than-air ship moored at the top of the Slayer's Spire. Wonder where it goes.",
        "The trade district is the best place to sell your goods. Merchants from all over the world come here.",
        "The city guard is always on alert. The threats from the Salt Flats and the Isle are very real.",
        "Historian Pallas knows more about the old kingdom than any book. His office is in the trade district.",
        "They say the Sunken Labyrinth on the Isle was a temple to a forgotten god of the deep.",
        "The fish market at the docks has the freshest catches from the Great Sea.",
        "The artisans in their quarter can craft almost anything, provided you have the right materials.",
        "The Royal Castle looms over the city. I wonder what the King is like.",
        "The Salt Flats are a desolate wasteland, but I hear they're rich in strange minerals.",
        "Only slayers of high renown are permitted to use the blimp service. It's a fast way to travel to dangerous lands.",
        "Be careful in the residential district. Some of the nobles are... particular.",
        "I heard a merchant complaining his shipment from Oakhaven was seized by bandits on the King's Road.",
        "The smiths here can work with the rarest metals, like Adamantite and whatever that 'runic' stuff is.",
        "The air smells of salt and industry here. A far cry from the forests and fields.",
        "You want to make a name for yourself? Slaying a rare beast is the quickest way to do it.",
        "The whispers from the Isle... some say they can drive a man mad.",
        "The Crystal Scuttlers in the Salt Flats have shells harder than steel.",
        "The ancient sentinels in the Labyrinth are said to be indestructible.",
        "There's an old woman in the residential district who lost a precious heirloom. She's been heartbroken for weeks.",
        "The Town Crier always has the latest news and bounties. It pays to listen to him.",
        "If you're looking for high-level runes, the monsters on the Isle of Whispers are your best bet.",
        "The alchemists here are always buying rare herbs and monster parts.",
        "Don't wander into the sewers. They say something... ancient... lives down there.",
        "The view from the top of the Slayer's Spire is breathtaking.",
        "Silverhaven is a city of opportunity, but also of great danger. Tread carefully.",
    ],
    fouthia: [
        "Welcome to Fouthia. Keep an eye on your coin purse and an eye on your waterskin.",
        "The Sand Serpent Inn is the only place to get a drink that isn't half sand.",
        "Don't wander out into the Salt Flats at night. The things that crawl out there... they're not natural.",
        "The town guard does their best, but they're outnumbered by the bandits in the surrounding wastes.",
        "Water is more valuable than gold out here. Don't waste a drop.",
        "That alchemist, Zafira, can brew a potion for just about anything. Heatstroke, scorpion venom... you name it.",
        "The bazaar is the heart of this town. You can find anything there, if you've got the coin.",
        "I heard whispers of a great 'Sunken City' far to the west, but who'd be mad enough to look for it?",
        "The Scorched Peaks to the north are said to be home to fire drakes and other nasty creatures.",
        "If you're looking for trouble, you'll find it in the back alleys. Or it'll find you.",
        "This town was built on an old oasis. The well in the square is the only reason we're still here.",
        "The armorer, Khalid, knows how to make gear that won't cook you alive in your own armor.",
    ],
    sanctity: [
        "The light protects us here in Sanctity.",
        "Did you come from the swamps? You have my sympathies. It is a foul place.",
        "Our artisans in the south are brilliant. They say their forges are blessed.",
        "The chapel is beautiful at dawn. A true sight to behold.",
        "I feel safe within these walls. The guards are vigilant, and our faith is strong.",
        "The Pilgrim's Rest doesn't serve ale, but their milk is the freshest you'll ever taste.",
        "Have you seen the library? So many holy texts to study.",
        "We are a town of piety and progress. The two are not mutually exclusive.",
        "Be wary of the eastern fields. There's an old fear that lingers there.",
        "The slums are a necessary evil, a place for those still finding their faith. We pray for them daily."
    ],
    lantern_festival: [
        "The glow of the lanterns over the lake is absolutely stunning!",
        "I ate three meat pies from the food stalls. No regrets!",
        "Have you tried the ring toss? Jin makes it look easy, but those pegs are slippery!",
        "Brokk is showing off at the high striker again. That bell hasn't stopped ringing all evening.",
        "Kenji's log balance pond is harder than it looks. I slipped right in on my first try!",
        "I bought a lovely paper lantern from Mira's stall. I'm going to launch it with my family tonight.",
        "The music, the lights, the laughter... I wish the Lantern Festival lasted all year!",
        "Hana's Whack-a-Lantern game is incredibly addictive. My arm is sore from all the mallet swinging!",
        "Make sure to visit the Gourd Patch! Smashing them open is surprisingly satisfying.",
        "Lin's trivia kiosk really tested my brain today. I'm glad I paid attention to Oakhaven's history!",
        "I love seeing the children running around with their small hand-held lanterns.",
        "The lake breeze at night is chilly, but the warmth of the crowd keeps everyone cozy.",
        "I'm saving up my Festival Tickets for one of those rare souvenir rewards!",
        "Did you see the giant master lantern in the plaza? The carving on it is magnificent.",
        "It's so wonderful to see everyone from town taking a break to celebrate together."
    ],
};
