
import { RepeatableQuest, SkillName } from '../types';

export const REPEATABLE_QUEST_POOL: RepeatableQuest[] = [
    // --- TUTORIAL ---
    { id: 'tutorial_magic_rat', questNum: 1, type: 'kill', title: 'Magical Pest Control', description: "A rat in the tavern has been chewing on spellbooks. The manager wants it gone, and the Magic Guide suggests using magic.", location: 'general', target: { monsterId: 'tutorial_rat' }, baseCoinReward: 10, xpReward: { skill: SkillName.Magic, amount: 10 } },

    // --- MEADOWDALE: GATHER ---
    { id: 'gather_logs_meadowdale', questNum: 2, type: 'gather', title: 'Restock the Woodpile', description: "The innkeeper needs more logs for the fire. Bring him a bundle of standard logs.", location: 'meadowdale', target: { itemId: 'logs' }, baseCoinReward: 5, xpReward: { skill: SkillName.Woodcutting, amount: 5 } },
    { id: 'gather_copper_ore_meadowdale', questNum: 3, type: 'gather', title: 'Ore for the Smithy', description: "The smithy is running low on basic ore for training new apprentices. Provide some copper ore.", location: 'meadowdale', target: { itemId: 'copper_ore' }, baseCoinReward: 8, xpReward: { skill: SkillName.Mining, amount: 4 } },
    { id: 'gather_tin_ore_meadowdale', questNum: 4, type: 'gather', title: 'Tin for the Tinsmith', description: "A local tinsmith needs a fresh supply of tin ore for their wares.", location: 'meadowdale', target: { itemId: 'tin_ore' }, baseCoinReward: 8, xpReward: { skill: SkillName.Mining, amount: 4 } },
    { id: 'gather_iron_ore_meadowdale', questNum: 5, type: 'gather', title: 'Iron for Valerius', description: "Valerius the smith needs iron ore for a special commission.", location: 'meadowdale', target: { itemId: 'iron_ore' }, baseCoinReward: 15, xpReward: { skill: SkillName.Mining, amount: 8 } },
    { id: 'gather_coal_meadowdale', questNum: 6, type: 'gather', title: 'Coal for the Forge', description: "The smithy's forge is running low on coal, needed to smelt steel.", location: 'meadowdale', target: { itemId: 'coal' }, baseCoinReward: 30, xpReward: { skill: SkillName.Mining, amount: 50 } },
    { id: 'gather_shrimp_meadowdale', questNum: 7, type: 'gather', title: "Chef's Request: Shrimp", description: "The local chef needs fresh shrimp for a new recipe. They'll pay for any you can bring.", location: 'meadowdale', target: { itemId: 'raw_shrimp' }, baseCoinReward: 5, xpReward: { skill: SkillName.Fishing, amount: 3 } },
    { id: 'gather_raw_beef_meadowdale', questNum: 8, type: 'gather', title: 'Beef for the Butcher', description: "The town butcher is preparing for a feast and needs more raw beef.", location: 'meadowdale', target: { itemId: 'raw_beef' }, baseCoinReward: 7, xpReward: { skill: SkillName.Cooking, amount: 2 } },
    { id: 'gather_raw_chicken_meadowdale', questNum: 9, type: 'gather', title: 'Poultry Procurement', description: "The tavern needs more chicken for their pies.", location: 'meadowdale', target: { itemId: 'raw_chicken' }, baseCoinReward: 5, xpReward: { skill: SkillName.Cooking, amount: 2 } },
    { id: 'gather_eggs_meadowdale', questNum: 10, type: 'gather', title: "Baker's Dozen", description: "The baker is short on eggs for today's cakes. Collect some from the chicken coop.", location: 'meadowdale', target: { itemId: 'eggs' }, baseCoinReward: 3, xpReward: { skill: SkillName.Cooking, amount: 1 } },
    { id: 'gather_bones_meadowdale', questNum: 11, type: 'gather', title: 'Respect for the Dead', description: "The chapel groundskeeper needs more bones for... reasons. It's best not to ask.", location: 'meadowdale', target: { itemId: 'bones' }, baseCoinReward: 5, xpReward: { skill: SkillName.Prayer, amount: 1 } },
    { id: 'gather_feathers_meadowdale', questNum: 12, type: 'gather', title: "Fletcher's Stock", description: "The local fletcher is buying feathers in bulk for arrow production.", location: 'meadowdale', target: { itemId: 'feathers' }, baseCoinReward: 2, xpReward: { skill: SkillName.Fletching, amount: 1 }, minQuantity: 100, maxQuantity: 250 },
    { id: 'gather_flax_meadowdale', questNum: 13, type: 'gather', title: 'Flax for the Spinner', description: "A local spinner needs flax to create bowstrings for the town guard.", location: 'meadowdale', target: { itemId: 'flax' }, baseCoinReward: 3, xpReward: { skill: SkillName.Crafting, amount: 1 } },
    { id: 'gather_oak_logs_meadowdale', questNum: 14, type: 'gather', title: 'Sturdy Oak Needed', description: "A carpenter requires oak logs for a more resilient piece of furniture.", location: 'meadowdale', target: { itemId: 'oak_logs' }, baseCoinReward: 19, xpReward: { skill: SkillName.Woodcutting, amount: 15 } },
    { id: 'gather_goblin_hide_meadowdale', questNum: 15, type: 'gather', title: 'Goblin Hide Bounty', description: "A local crafter is experimenting with goblin hide and will pay for any you bring them.", location: 'meadowdale', target: { itemId: 'goblin_hide' }, baseCoinReward: 15, xpReward: { skill: SkillName.Crafting, amount: 3 } },
    { id: 'gather_spider_silk_meadowdale', questNum: 16, type: 'gather', title: 'Silky Smooth', description: "The tailor needs spider silk for a special order. Be careful collecting it.", location: 'meadowdale', target: { itemId: 'spider_silk' }, baseCoinReward: 15, xpReward: { skill: SkillName.Crafting, amount: 4 } },
    { id: 'gather_wheat_meadowdale', questNum: 17, type: 'gather', title: 'Wheat for the Mill', description: "The windmill operator needs more wheat to mill into flour for the town.", location: 'meadowdale', target: { itemId: 'wheat' }, baseCoinReward: 3, xpReward: { skill: SkillName.Cooking, amount: 1 } },
    { id: 'gather_flour_meadowdale', questNum: 18, type: 'gather', title: "Baker's Emergency", description: "The baker has run out of flour and needs some urgently.", location: 'meadowdale', target: { itemId: 'flour' }, baseCoinReward: 7, xpReward: { skill: SkillName.Cooking, amount: 1 } },
    { id: 'gather_rat_tails_meadowdale', questNum: 19, type: 'gather', title: 'A Strange Request', description: "An eccentric alchemist in town is paying for rat tails for a... 'special' brew.", location: 'meadowdale', target: { itemId: 'rat_tail' }, baseCoinReward: 5, xpReward: { skill: SkillName.Herblore, amount: 1 } },

    // --- MEADOWDALE: KILL ---
    { id: 'kill_rats_meadowdale', questNum: 20, type: 'kill', title: 'Cellar Infestation', description: "Giant rats have infested the tavern's cellar. Clear them out.", location: 'meadowdale', target: { monsterId: 'tavern_rat' }, baseCoinReward: 50, xpReward: { skill: SkillName.Attack, amount: 14 }, isInstance: true, instancePoiId: 'tavern_cellar' },
    { id: 'kill_goblins_meadowdale', questNum: 21, type: 'kill', title: 'Mine Mischief', description: 'Goblins are causing trouble in the Stonebreak Mine again. Thin their numbers.', location: 'meadowdale', target: { monsterId: 'goblin' }, baseCoinReward: 20, xpReward: { skill: SkillName.Strength, amount: 16 } },
    { id: 'kill_cows_meadowdale', questNum: 22, type: 'kill', title: 'Mad Cow Problem', description: "A strange sickness is making McGregor's cows aggressive. They need to be put down.", location: 'meadowdale', target: { monsterId: 'cow' }, baseCoinReward: 20, xpReward: { skill: SkillName.Attack, amount: 16 }, aggressionToggle: { poiId: 'cow_pasture', monsterId: 'cow' } },
    { id: 'kill_chickens_meadowdale', questNum: 23, type: 'kill', title: 'Fowl Play', description: "Something's not right with the chickens at the ranch. They're attacking people on sight!", location: 'meadowdale', target: { monsterId: 'chicken' }, baseCoinReward: 20, xpReward: { skill: SkillName.Attack, amount: 6 }, aggressionToggle: { poiId: 'chicken_coop', monsterId: 'chicken' } },
    { id: 'kill_goblin_scouts_meadowdale', questNum: 24, type: 'kill', title: 'Deeper Threats', description: "Goblin scouts have been spotted deeper in the mines, suggesting a larger presence. Take them out.", location: 'meadowdale', target: { monsterId: 'goblin_scout' }, baseCoinReward: 70, xpReward: { skill: SkillName.Defence, amount: 36 } },
    { id: 'kill_spiders_meadowdale', questNum: 25, type: 'kill', title: 'Web of Trouble', description: "Giant spiders are nesting too close to the southern road. Clear them out before someone gets hurt.", location: 'meadowdale', target: { monsterId: 'giant_spider' }, baseCoinReward: 70, xpReward: { skill: SkillName.Defence, amount: 30 } },
    { id: 'kill_bandits_meadowdale', questNum: 26, type: 'kill', title: 'Roadside Robbery', description: "Cloaked bandits are still a problem on the southern road. The town guard will pay for every one you dispatch.", location: 'meadowdale', target: { monsterId: 'cloaked_bandit' }, baseCoinReward: 120, xpReward: { skill: SkillName.Strength, amount: 40 } },
    { id: 'kill_boars_meadowdale', questNum: 27, type: 'kill', title: 'Boarish Behavior', description: "Wild boars from the fields are becoming a nuisance to local travelers and farmers. Cull their numbers.", location: 'meadowdale', target: { monsterId: 'wild_boar' }, baseCoinReward: 110, xpReward: { skill: SkillName.Attack, amount: 44 } },
    { id: 'kill_wolves_meadowdale', questNum: 28, type: 'kill', title: 'A Wolf at the Door', description: "Wolves from the highlands are preying on McGregor's livestock. He's offering a reward.", location: 'meadowdale', target: { monsterId: 'wolf' }, baseCoinReward: 150, xpReward: { skill: SkillName.Strength, amount: 50 } },
    { id: 'kill_slimes_meadowdale', questNum: 29, type: 'kill', title: 'Slimy Situation', description: "The deeper parts of the mine are getting clogged with cave slimes. Clean up the mess.", location: 'meadowdale', target: { monsterId: 'cave_slime' }, baseCoinReward: 30, xpReward: { skill: SkillName.Defence, amount: 20 } },

    // --- MEADOWDALE: INTERACT ---
    { id: 'interact_clean_tavern_meadowdale', questNum: 30, type: 'interact', title: 'Tidy the Tavern', description: "The Rusty Flagon is a mess after a busy night. Help the barkeep clean up.", location: 'meadowdale', locationPoiId: 'the_rusty_flagon', target: { name: 'Tidy the Tavern' }, baseCoinReward: 100, xpReward: { skill: SkillName.Strength, amount: 150 } },
    { id: 'interact_deliver_mail_meadowdale', questNum: 31, type: 'interact', title: 'Postal Service', description: "The town clerk needs some letters delivered around Meadowdale.", location: 'meadowdale', locationPoiId: 'town_hall', target: { name: 'Deliver Mail' }, baseCoinReward: 120, xpReward: { skill: SkillName.Hitpoints, amount: 10 } },
    { id: 'interact_restock_shelves_meadowdale', questNum: 32, type: 'interact', title: 'Restock the General Store', description: "Help the general store owner organize and restock the shelves.", location: 'meadowdale', locationPoiId: 'meadowdale_square', target: { name: 'Restock Shelves' }, baseCoinReward: 150, xpReward: { skill: SkillName.Crafting, amount: 20 } },
    { id: 'interact_repair_fence_meadowdale', questNum: 33, type: 'interact', title: 'Fence Mending', description: "A section of fence at McGregor's Ranch has been damaged. Help him repair it.", location: 'meadowdale', locationPoiId: 'mcgregors_ranch', target: { name: 'Repair Fence' }, baseCoinReward: 200, xpReward: { skill: SkillName.Woodcutting, amount: 240 } },
    { id: 'interact_sort_books_meadowdale', questNum: 34, type: 'interact', title: 'Library Assistance', description: "Librarian Elara needs help sorting and re-shelving returned books.", location: 'meadowdale', locationPoiId: 'meadowdale_library', target: { name: 'Sort Books' }, baseCoinReward: 220, xpReward: { skill: SkillName.Magic, amount: 300 } },

    // --- OAKHAVEN: GATHER ---
    { id: 'gather_oak_logs_oakhaven', questNum: 35, type: 'gather', title: 'Oak for Oakhaven', description: 'A local carpenter needs oak logs for a sturdy commission.', location: 'oakhaven', target: { itemId: 'oak_logs' }, baseCoinReward: 19, xpReward: { skill: SkillName.Woodcutting, amount: 30 } },
    { id: 'gather_willow_logs_oakhaven', questNum: 36, type: 'gather', title: 'Willow for Bows', description: "The fletcher is buying willow logs for lightweight bows.", location: 'oakhaven', target: { itemId: 'willow_logs' }, baseCoinReward: 35, xpReward: { skill: SkillName.Woodcutting, amount: 60 } },
    { id: 'gather_raw_trout_oakhaven', questNum: 37, type: 'gather', title: 'Trout for the Tavern', description: "The Carved Mug is famous for its trout, and they're running low.", location: 'oakhaven', target: { itemId: 'raw_trout' }, baseCoinReward: 20, xpReward: { skill: SkillName.Fishing, amount: 30 } },
    { id: 'gather_raw_pike_oakhaven', questNum: 38, type: 'gather', title: 'A Noble Order', description: 'A noble from Silverhaven has ordered pike, and the tavern needs to fulfill it.', location: 'oakhaven', target: { itemId: 'raw_pike' }, baseCoinReward: 25, xpReward: { skill: SkillName.Fishing, amount: 40 } },
    { id: 'gather_raw_eel_oakhaven', questNum: 39, type: 'gather', title: 'Swamp Delicacy', description: "A chef will pay well for raw eels from the swamp. Watch out for what lurks in the water.", location: 'oakhaven', target: { itemId: 'raw_eel' }, baseCoinReward: 35, xpReward: { skill: SkillName.Fishing, amount: 50 } },
    { id: 'gather_iron_ore_oakhaven', questNum: 40, type: 'gather', title: 'Iron Supply Run', description: 'The blacksmiths of Oakhaven need a steady supply of iron for their tools.', location: 'oakhaven', target: { itemId: 'iron_ore' }, baseCoinReward: 15, xpReward: { skill: SkillName.Mining, amount: 20 } },
    { id: 'gather_coal_oakhaven', questNum: 41, type: 'gather', title: 'Fueling the Forges', description: 'Coal is needed to fuel the forges for high-temperature smelting. The demand is high.', location: 'oakhaven', target: { itemId: 'coal' }, baseCoinReward: 30, xpReward: { skill: SkillName.Mining, amount: 50 } },
    { id: 'gather_silver_ore_oakhaven', questNum: 42, type: 'gather', title: 'Silver for the Smiths', description: 'A silversmith is paying a premium for raw silver ore to craft fine jewelry.', location: 'oakhaven', target: { itemId: 'silver_ore' }, baseCoinReward: 35, xpReward: { skill: SkillName.Mining, amount: 30 } },
    { id: 'gather_wolf_pelt_oakhaven', questNum: 43, type: 'gather', title: 'Warm Winter Cloaks', description: 'Tanner Sven needs wolf pelts for a set of warm cloaks before winter sets in.', location: 'oakhaven', target: { itemId: 'wolf_pelt' }, baseCoinReward: 20, xpReward: { skill: SkillName.Crafting, amount: 40 } },
    { id: 'gather_glimmer_thread_oakhaven', questNum: 44, type: 'gather', title: 'Shimmering Threads', description: "The weavers are trying to replicate the shimmer of Glimmerhorn Stag manes. They need fibers.", location: 'oakhaven', target: { itemId: 'glimmer_thread_fiber' }, baseCoinReward: 15, xpReward: { skill: SkillName.Crafting, amount: 50 } },

    // --- OAKHAVEN: KILL ---
    { id: 'kill_highwaymen_oakhaven', questNum: 45, type: 'kill', title: "King's Road Patrol", description: "Highwaymen are making a nuisance of themselves on the old King's Road. Clear them out.", location: 'oakhaven', target: { monsterId: 'highwayman' }, baseCoinReward: 105, xpReward: { skill: SkillName.Strength, amount: 70 } },
    { id: 'kill_wild_boars_oakhaven', questNum: 46, type: 'kill', title: 'Boar Hunt', description: 'Wild boars are becoming aggressive and trampling the fields west of the ranch.', location: 'oakhaven', target: { monsterId: 'wild_boar' }, baseCoinReward: 110, xpReward: { skill: SkillName.Attack, amount: 44 } },
    { id: 'kill_wolves_oakhaven', questNum: 47, type: 'kill', title: 'Wolf Pack Problem', description: 'A wolf pack in the Tanglewood has grown bold, threatening travelers.', location: 'oakhaven', target: { monsterId: 'wolf' }, baseCoinReward: 150, xpReward: { skill: SkillName.Strength, amount: 50 } },
    { id: 'kill_bears_oakhaven', questNum: 48, type: 'kill', title: 'Bear Necessities', description: "Bears have been wandering out of their caves, scaring locals. Thin their numbers.", location: 'oakhaven', target: { monsterId: 'bear' }, baseCoinReward: 180, xpReward: { skill: SkillName.Defence, amount: 70 } },
    { id: 'kill_glimmerhorn_stags_oakhaven', questNum: 49, type: 'kill', title: 'Antler Collection', description: "A collector wants the antlers of the mystical Glimmerhorn Stags. The pay is good.", location: 'oakhaven', target: { monsterId: 'glimmerhorn_stag' }, baseCoinReward: 160, xpReward: { skill: SkillName.Ranged, amount: 40 } },
    { id: 'kill_forest_spirits_oakhaven', questNum: 50, type: 'kill', title: 'Restless Spirits', description: 'The Forest Spirits near the ancient stones have become agitated. Quell their anger.', location: 'oakhaven', target: { monsterId: 'forest_spirit' }, baseCoinReward: 160, xpReward: { skill: SkillName.Magic, amount: 60 } },
    { id: 'kill_treant_saplings_oakhaven', questNum: 51, type: 'kill', title: 'Pruning the Overgrowth', description: 'Young Treants are overrunning the western ruins, making the area impassable.', location: 'oakhaven', target: { monsterId: 'treant_sapling' }, baseCoinReward: 170, xpReward: { skill: SkillName.Woodcutting, amount: 76 } },
    { id: 'kill_young_hill_giants_oakhaven', questNum: 52, type: 'kill', title: 'Giant Problems', description: "Young Hill Giants are causing tremors on the plateau. Put a stop to their roughhousing.", location: 'oakhaven', target: { monsterId: 'young_hill_giant' }, baseCoinReward: 110, xpReward: { skill: SkillName.Strength, amount: 90 } },
    { id: 'kill_giant_toads_oakhaven', questNum: 53, type: 'kill', title: 'Toad Trouble', description: 'The giant toads in the Sunken Lands are a noisy, slimy nuisance. Reduce their population.', location: 'oakhaven', target: { monsterId: 'giant_toad' }, baseCoinReward: 150, xpReward: { skill: SkillName.Attack, amount: 46 } },
    { id: 'kill_bog_mites_oakhaven', questNum: 54, type: 'kill', title: 'Mire Extermination', description: 'Swarms of Bog Mites are making the Mire of Sorrow even more unpleasant. Clear them out.', location: 'oakhaven', target: { monsterId: 'bog_mite' }, baseCoinReward: 130, xpReward: { skill: SkillName.Defence, amount: 90 } },
    { id: 'kill_swamp_horrors_oakhaven', questNum: 55, type: 'kill', title: 'Horrors of the Swamp', description: 'Terrifying Swamp Horrors have emerged from the sunken ruins. They must be destroyed.', location: 'oakhaven', target: { monsterId: 'swamp_horror' }, baseCoinReward: 205, xpReward: { skill: SkillName.Strength, amount: 120 } },
    { id: 'kill_mountain_goats_oakhaven', questNum: 56, type: 'kill', title: 'Aggressive Goats', description: 'The mountain goats in the Gale-Swept Peaks are unusually aggressive, knocking travelers from the paths.', location: 'oakhaven', target: { monsterId: 'mountain_goat' }, baseCoinReward: 180, xpReward: { skill: SkillName.Attack, amount: 60 } },
    { id: 'kill_harpies_oakhaven', questNum: 57, type: 'kill', title: 'Harpy Hunt', description: "Harpies from the roost are preying on travelers in the mountain pass. A bounty has been posted.", location: 'oakhaven', target: { monsterId: 'harpy' }, baseCoinReward: 110, xpReward: { skill: SkillName.Ranged, amount: 70 } },
    { id: 'kill_goblin_brutes_oakhaven', questNum: 58, type: 'kill', title: 'Brute Force', description: 'Goblin Brutes have been seen guarding key passages in the warrens. Eliminate the threat.', location: 'oakhaven', target: { monsterId: 'goblin_brute' }, baseCoinReward: 120, xpReward: { skill: SkillName.Strength, amount: 80 } },
    { id: 'bounty_grumlok_oakhaven', questNum: 59, type: 'kill', title: 'Bounty: Grumlok the Goblin King', description: "A bounty has been posted for the head of Grumlok. He is a formidable foe in the Goblin Warrens. Combat level 30+ is strongly recommended.", location: 'oakhaven', target: { monsterId: 'grumlok_goblin_king' }, baseCoinReward: 246, xpReward: { skill: SkillName.Slayer, amount: 240 }, minQuantity: 1, maxQuantity: 1 },

    // --- OAKHAVEN: INTERACT ---
    { id: 'interact_clean_carved_mug_oakhaven', questNum: 60, type: 'interact', title: 'Tavern Cleanup', description: "The Carved Mug is in disarray after a rowdy night. Help Freya clean up the mess.", location: 'oakhaven', locationPoiId: 'the_carved_mug', target: { name: 'Clean Tavern' }, baseCoinReward: 200, xpReward: { skill: SkillName.Strength, amount: 80 } },
    { id: 'interact_restock_artisan_supplies_oakhaven', questNum: 61, type: 'interact', title: 'Restock Supplies', description: 'The Artisan Supplies shop needs help restocking shelves with heavy goods.', location: 'oakhaven', locationPoiId: 'oakhaven_crafting_supplies', target: { name: 'Restock Shelves' }, baseCoinReward: 220, xpReward: { skill: SkillName.Crafting, amount: 90 } },
    { id: 'interact_prepare_hides_oakhaven', questNum: 62, type: 'interact', title: "Tanner's Assistant", description: "Tanner Sven needs help preparing raw hides for the tanning process. It's smelly work.", location: 'oakhaven', locationPoiId: 'tanner_svens_shop', target: { name: 'Prepare Hides' }, baseCoinReward: 240, xpReward: { skill: SkillName.Crafting, amount: 100 } },
    { id: 'interact_organize_apothecary_oakhaven', questNum: 63, type: 'interact', title: 'Apothecary Aid', description: "Herbalist Anise's shop is a mess of vials and herbs. She needs a hand organizing it.", location: 'oakhaven', locationPoiId: 'oakhaven_herblore_shop', target: { name: 'Organize Vials' }, baseCoinReward: 260, xpReward: { skill: SkillName.Herblore, amount: 110 } },
    { id: 'interact_deliver_wood_oakhaven', questNum: 64, type: 'interact', title: 'Lumber Delivery', description: "Deliver a cart of freshly cut lumber from Alaric's workshop to the market.", location: 'oakhaven', locationPoiId: 'oakhaven_woodworkers_shop', target: { name: 'Deliver Lumber' }, baseCoinReward: 280, xpReward: { skill: SkillName.Woodcutting, amount: 120 } },

    // --- ISLE OF WHISPERS ---
    { id: 'kill_crabs_isle', questNum: 65, type: 'kill', title: 'Crab Cull', description: "The giant crab population is out of control and threatening the docks. Thin their numbers.", location: 'isle_of_whispers', target: { monsterId: 'giant_crab' }, baseCoinReward: 90, xpReward: { skill: SkillName.Attack, amount: 50 } },
    { id: 'gather_driftwood_isle', questNum: 66, type: 'gather', title: 'Salvage Operation', description: "The settlers need driftwood to reinforce their shacks before the next storm. Gather some from the beaches.", location: 'isle_of_whispers', target: { itemId: 'driftwood_logs' }, baseCoinReward: 10, xpReward: { skill: SkillName.Woodcutting, amount: 40 } },
    { id: 'kill_specters_isle', questNum: 67, type: 'kill', title: 'Ghost Busting', description: "The shipwreck specters are becoming more aggressive. Put them to rest.", location: 'isle_of_whispers', target: { monsterId: 'shipwreck_specter' }, baseCoinReward: 195, xpReward: { skill: SkillName.Ranged, amount: 150 } },
    { id: 'interact_sort_salvage_isle', questNum: 68, type: 'interact', title: 'Sort the Salvage', description: "Help Salty Sam sort through the latest haul of shipwreck salvage at The Barnacle's Bite.", location: 'isle_of_whispers', locationPoiId: 'the_barnacles_bite', target: { name: 'Sort Salvage' }, baseCoinReward: 300, xpReward: { skill: SkillName.Crafting, amount: 120 } },

    // --- SILVERHAVEN: GATHER ---
    { id: 'gather_yew_logs_silverhaven', questNum: 69, type: 'gather', title: 'Yew for the Shipwrights', description: 'The shipwrights at the docks require yew logs for a new vessel.', location: 'silverhaven', target: { itemId: 'yew_logs' }, baseCoinReward: 65, xpReward: { skill: SkillName.Woodcutting, amount: 180 } },
    { id: 'gather_mithril_ore_silverhaven', questNum: 70, type: 'gather', title: 'Mithril for the Armory', description: 'The Gilded Hammer Armory has a large order for mithril equipment.', location: 'silverhaven', target: { itemId: 'mithril_ore' }, baseCoinReward: 55, xpReward: { skill: SkillName.Mining, amount: 85 } },
    { id: 'gather_adamantite_ore_silverhaven', questNum: 71, type: 'gather', title: 'Adamantite Stockpile', description: 'The city guard is stockpiling adamantite for emergencies. They pay well.', location: 'silverhaven', target: { itemId: 'adamantite_ore' }, baseCoinReward: 60, xpReward: { skill: SkillName.Mining, amount: 125 } },
    { id: 'gather_raw_swordfish_silverhaven', questNum: 72, type: 'gather', title: 'Banquet Supplies: Swordfish', description: 'The castle chef is preparing a banquet and needs fresh swordfish.', location: 'silverhaven', target: { itemId: 'raw_swordfish' }, baseCoinReward: 50, xpReward: { skill: SkillName.Fishing, amount: 145 } },
    { id: 'gather_raw_shark_silverhaven', questNum: 73, type: 'gather', title: 'An Exotic Order', description: 'A noble has requested a fresh shark for a... display piece. The fish market will buy any you catch.', location: 'silverhaven', target: { itemId: 'raw_shark' }, baseCoinReward: 80, xpReward: { skill: SkillName.Fishing, amount: 215 } },
    { id: 'gather_mahogany_logs_silverhaven', questNum: 74, type: 'gather', title: 'Furniture for a Noble', description: 'A wealthy noble is commissioning furniture and requires mahogany logs.', location: 'silverhaven', target: { itemId: 'mahogany_logs' }, baseCoinReward: 50, xpReward: { skill: SkillName.Woodcutting, amount: 130 } },
    { id: 'gather_uncut_diamonds_silverhaven', questNum: 75, type: 'gather', title: 'Jeweler\'s Demand', description: 'The city jewelers are in desperate need of uncut diamonds for a royal commission.', location: 'silverhaven', target: { itemId: 'uncut_diamond' }, baseCoinReward: 210, xpReward: { skill: SkillName.Crafting, amount: 360 } },

    // --- SILVERHAVEN: CRAFTING (GATHER) ---
    { id: 'craft_yew_longbows_silverhaven', questNum: 76, type: 'gather', title: 'Bows for the Guard', description: "The city guard's archer division needs a new supply of Yew Longbows.", location: 'silverhaven', target: { itemId: 'yew_longbow' }, baseCoinReward: 150, xpReward: { skill: SkillName.Fletching, amount: 80 } },
    { id: 'craft_adamantite_platelegs_silverhaven', questNum: 77, type: 'gather', title: 'Leg Day', description: "The Gilded Hammer needs help fulfilling an order for Adamantite Platelegs.", location: 'silverhaven', target: { itemId: 'adamantite_platelegs' }, baseCoinReward: 420, xpReward: { skill: SkillName.Smithing, amount: 200 } },
    { id: 'craft_super_attack_potions_silverhaven', questNum: 78, type: 'gather', title: 'Alchemical Supply', description: 'The Slayer Master requires Super Attack Potions for their new recruits.', location: 'silverhaven', target: { itemId: 'super_attack_potion' }, baseCoinReward: 500, xpReward: { skill: SkillName.Herblore, amount: 105 } },
    { id: 'craft_diamond_amulets_silverhaven', questNum: 79, type: 'gather', title: 'Amulets of Power', description: 'A merchant wants to export a crate of enchanted Diamond Amulets.', location: 'silverhaven', target: { itemId: 'amulet_of_power' }, baseCoinReward: 1500, xpReward: { skill: SkillName.Crafting, amount: 200 } },

    // --- SILVERHAVEN: RUNECRAFTING (GATHER) ---
    { id: 'gather_verdant_runes_silverhaven', questNum: 80, type: 'gather', title: 'Verdant Runes for the Mages', description: 'The mages in the Arcane Wares shop need a large supply of Verdant Runes.', location: 'silverhaven', target: { itemId: 'verdant_rune' }, baseCoinReward: 12, xpReward: { skill: SkillName.Runecrafting, amount: 10 }, minQuantity: 100, maxQuantity: 500 },
    { id: 'gather_nexus_runes_silverhaven', questNum: 81, type: 'gather', title: 'Nexus Rune Research', description: 'Archmage Theron is conducting research and requires Nexus Runes.', location: 'silverhaven', target: { itemId: 'nexus_rune' }, baseCoinReward: 44, xpReward: { skill: SkillName.Runecrafting, amount: 14 }, minQuantity: 100, maxQuantity: 500 },
    { id: 'gather_hex_runes_silverhaven', questNum: 82, type: 'gather', title: 'Hexes for the Guard', description: 'The city guard is enchanting their bolts with minor hexes and need the runes.', location: 'silverhaven', target: { itemId: 'hex_rune' }, baseCoinReward: 6, xpReward: { skill: SkillName.Runecrafting, amount: 5 }, minQuantity: 100, maxQuantity: 500 },

    // --- SILVERHAVEN: KILL ---
    { id: 'kill_sirens_silverhaven', questNum: 83, type: 'kill', title: 'Siren Song', description: 'The sirens on the Isle of Whispers are luring too many ships to their doom. Put an end to their song.', location: 'silverhaven', target: { monsterId: 'siren' }, baseCoinReward: 220, xpReward: { skill: SkillName.Ranged, amount: 180 } },
    { id: 'kill_abyssal_knights_silverhaven', questNum: 84, type: 'kill', title: 'Knight Eradication', description: 'The Abyssal Knights in the Sunken Labyrinth pose a significant threat. They must be eliminated.', location: 'silverhaven', target: { monsterId: 'abyssal_knight' }, baseCoinReward: 195, xpReward: { skill: SkillName.Defence, amount: 200 } },
    { id: 'kill_grave_revenants_silverhaven', questNum: 85, type: 'kill', title: 'Rest for the Dead', description: 'Grave Revenants haunt the Sunken Labyrinth. Grant them final rest.', location: 'silverhaven', target: { monsterId: 'grave_revenant' }, baseCoinReward: 190, xpReward: { skill: SkillName.Prayer, amount: 170 } },
    { id: 'kill_coral_golems_silverhaven', questNum: 86, type: 'kill', title: 'Reef Clearing', description: 'Coral Golems are blocking ancient waterways in the labyrinth. Clear them out.', location: 'silverhaven', target: { monsterId: 'coral_golem' }, baseCoinReward: 192, xpReward: { skill: SkillName.Strength, amount: 220 } },
    { id: 'bounty_abyssal_warden_silverhaven', questNum: 87, type: 'kill', title: 'Bounty: The Abyssal Warden', description: 'A large bounty has been placed on the head of The Abyssal Warden, guardian of the Sunken Labyrinth. Combat level 70+ recommended.', location: 'silverhaven', target: { monsterId: 'the_abyssal_warden' }, baseCoinReward: 240, xpReward: { skill: SkillName.Slayer, amount: 300 }, minQuantity: 1, maxQuantity: 1 },

    // --- SILVERHAVEN: INTERACT ---
    { id: 'interact_polish_fountain_silverhaven', questNum: 88, type: 'interact', title: 'Polish the Fountain', description: 'The great silver dragon fountain in the square is looking a bit tarnished. Polish it up.', location: 'silverhaven', locationPoiId: 'silverhaven_square', target: { name: 'Polish Fountain' }, baseCoinReward: 400, xpReward: { skill: SkillName.Crafting, amount: 150 } },
    { id: 'interact_sort_cargo_silverhaven', questNum: 89, type: 'interact', title: 'Sort the Cargo', description: 'The harbormaster at the docks needs help sorting and cataloging incoming cargo.', location: 'silverhaven', locationPoiId: 'silverhaven_docks', target: { name: 'Sort Cargo' }, baseCoinReward: 450, xpReward: { skill: SkillName.Strength, amount: 160 } },
    { id: 'interact_clean_spire_silverhaven', questNum: 90, type: 'interact', title: 'Spire Maintenance', description: "The Slayer's Spire needs a good cleaning. Kaelen is too busy to do it himself.", location: 'silverhaven', locationPoiId: 'silverhaven_slayers_spire', target: { name: 'Clean the Spire' }, baseCoinReward: 500, xpReward: { skill: SkillName.Strength, amount: 180 } }, // Agility is not a skill, using Strength as a placeholder
    { id: 'interact_organize_armory_silverhaven', questNum: 91, type: 'interact', title: 'Organize the Armory', description: 'Help Master Smith Gideon organize the vast stores of armor and weapons in The Gilded Hammer.', location: 'silverhaven', locationPoiId: 'silverhaven_smithy', target: { name: 'Organize Armory' }, baseCoinReward: 550, xpReward: { skill: SkillName.Smithing, amount: 200 } },

    // --- FOUTHIA: KILL ---
    { id: 'kill_sand_scrabblers_fouthia', questNum: 92, type: 'kill', title: 'Pest Control', description: 'Sand Scrabblers are overrunning the northern dunes.', location: 'fouthia', target: { monsterId: 'sand_scrabbler' }, baseCoinReward: 165, xpReward: { skill: SkillName.Attack, amount: 100 } },
    { id: 'kill_dune_stalkers_fouthia', questNum: 93, type: 'kill', title: 'Stalker Hunt', description: 'Dune Stalkers pose a threat to travelers near the Whispering Gulch.', location: 'fouthia', target: { monsterId: 'dune_stalker' }, baseCoinReward: 186, xpReward: { skill: SkillName.Slayer, amount: 130 } },
    { id: 'kill_oasis_crocs_fouthia', questNum: 94, type: 'kill', title: 'Oasis Danger', description: 'The crocodiles at the Dying Oasis are becoming aggressive.', location: 'fouthia', target: { monsterId: 'oasis_croc' }, baseCoinReward: 204, xpReward: { skill: SkillName.Strength, amount: 160 } },
    { id: 'kill_canyon_basilisks_fouthia', questNum: 95, type: 'kill', title: 'Basilisk Threat', description: 'Basilisks in the Serpent Canyon are petrifying unwary miners.', location: 'fouthia', target: { monsterId: 'canyon_basilisk' }, baseCoinReward: 225, xpReward: { skill: SkillName.Defence, amount: 180 } },
    { id: 'kill_sunstone_scorpions_fouthia', questNum: 96, type: 'kill', title: 'Scorpion Sting', description: 'Giant scorpions are guarding the crystal veins.', location: 'fouthia', target: { monsterId: 'sunstone_scorpion' }, baseCoinReward: 246, xpReward: { skill: SkillName.Attack, amount: 200 } },
    { id: 'kill_desert_nomads_fouthia', questNum: 97, type: 'kill', title: 'Nomad Raids', description: 'Hostile nomads are raiding trade caravans.', location: 'fouthia', target: { monsterId: 'desert_nomad' }, baseCoinReward: 264, xpReward: { skill: SkillName.Ranged, amount: 170 } },
    { id: 'kill_blazing_efreeti_fouthia', questNum: 98, type: 'kill', title: 'Fire Spirits', description: 'Efreeti are emerging from the volcanic vents.', location: 'fouthia', target: { monsterId: 'blazing_efreeti' }, baseCoinReward: 285, xpReward: { skill: SkillName.Magic, amount: 220 } },
    { id: 'kill_sand_wyrms_fouthia', questNum: 99, type: 'kill', title: 'Wyrm Hunt', description: 'A Sand Wyrm has been spotted near the crystal heart.', location: 'fouthia', target: { monsterId: 'sand_wyrm' }, baseCoinReward: 315, xpReward: { skill: SkillName.Slayer, amount: 360 } },
    { id: 'kill_temple_guardians_fouthia', questNum: 100, type: 'kill', title: 'Ancient Guardians', description: 'The guardians of the buried temple have awakened.', location: 'fouthia', target: { monsterId: 'temple_guardian' }, baseCoinReward: 345, xpReward: { skill: SkillName.Defence, amount: 300 } },
    { id: 'kill_salt_flat_skitterers_fouthia', questNum: 101, type: 'kill', title: 'Salt Skitterers', description: 'Clear out the skitterers near the outpost path.', location: 'fouthia', target: { monsterId: 'salt_flat_skitterer' }, baseCoinReward: 160, xpReward: { skill: SkillName.Attack, amount: 96 } },
    { id: 'kill_salt_leapers_fouthia', questNum: 102, type: 'kill', title: 'Leaper Plague', description: 'Salt Leapers are swarming the entrance to the flats.', location: 'fouthia', target: { monsterId: 'salt_leaper' }, baseCoinReward: 175, xpReward: { skill: SkillName.Strength, amount: 110 } },
    { id: 'kill_salt_preserved_vultures_fouthia', questNum: 103, type: 'kill', title: 'Scavenger Hunt', description: 'Vultures are picking clean the skeletal remains.', location: 'fouthia', target: { monsterId: 'salt_preserved_vulture' }, baseCoinReward: 170, xpReward: { skill: SkillName.Ranged, amount: 100 } },
    { id: 'kill_crystal_scuttlers_fouthia', questNum: 104, type: 'kill', title: 'Crystal Pests', description: 'Scuttlers are damaging the crystal formations.', location: 'fouthia', target: { monsterId: 'crystal_scuttler' }, baseCoinReward: 200, xpReward: { skill: SkillName.Defence, amount: 130 } },
    { id: 'kill_crystalline_tortoises_fouthia', questNum: 105, type: 'kill', title: 'Hard Shells', description: 'Tortoises are blocking the path to the veins.', location: 'fouthia', target: { monsterId: 'crystalline_tortoise' }, baseCoinReward: 190, xpReward: { skill: SkillName.Strength, amount: 140 } },
    { id: 'kill_brine_elementals_fouthia', questNum: 106, type: 'kill', title: 'Brine Spirits', description: 'Elemental spirits are haunting the saline pools.', location: 'fouthia', target: { monsterId: 'brine_elemental' }, baseCoinReward: 210, xpReward: { skill: SkillName.Magic, amount: 180 } },
    { id: 'kill_ancient_ammonites_fouthia', questNum: 107, type: 'kill', title: 'Ancient Threat', description: 'An Ancient Ammonite has awoken near the great pillar.', location: 'fouthia', target: { monsterId: 'ancient_ammonite' }, baseCoinReward: 240, xpReward: { skill: SkillName.Defence, amount: 220 } },

    // --- FOUTHIA: GATHER ---
    { id: 'gather_rock_salt_fouthia', questNum: 108, type: 'gather', title: 'Salt Harvest', description: 'The alchemist needs rock salt for her potions.', location: 'fouthia', target: { itemId: 'rock_salt' }, baseCoinReward: 30, xpReward: { skill: SkillName.Mining, amount: 40 } },
    { id: 'gather_brine_crystals_fouthia', questNum: 109, type: 'gather', title: 'Crystal Collection', description: 'Brine crystals are needed for magical research.', location: 'fouthia', target: { itemId: 'brine_crystal' }, baseCoinReward: 150, xpReward: { skill: SkillName.Mining, amount: 100 } },
    { id: 'gather_coal_fouthia', questNum: 110, type: 'gather', title: 'Fuel for the Forge', description: 'The armorer needs coal to keep the fires burning.', location: 'fouthia', target: { itemId: 'coal' }, baseCoinReward: 40, xpReward: { skill: SkillName.Mining, amount: 60 } },
    { id: 'gather_silver_ore_fouthia', questNum: 111, type: 'gather', title: 'Silver Demand', description: 'Silver is needed for intricate desert jewelry.', location: 'fouthia', target: { itemId: 'silver_ore' }, baseCoinReward: 50, xpReward: { skill: SkillName.Mining, amount: 50 } },
    { id: 'gather_gold_ore_fouthia', questNum: 112, type: 'gather', title: 'Gold Rush', description: 'Gold veins have been spotted near the quarry.', location: 'fouthia', target: { itemId: 'gold_ore' }, baseCoinReward: 150, xpReward: { skill: SkillName.Mining, amount: 120 } },
    { id: 'gather_mithril_ore_fouthia', questNum: 113, type: 'gather', title: 'Mithril Shipment', description: 'A shipment of mithril is needed for the town guard.', location: 'fouthia', target: { itemId: 'mithril_ore' }, baseCoinReward: 55, xpReward: { skill: SkillName.Mining, amount: 150 } },
    { id: 'gather_adamantite_ore_fouthia', questNum: 114, type: 'gather', title: 'Rare Metal', description: 'Adamantite is scarce but highly valued.', location: 'fouthia', target: { itemId: 'adamantite_ore' }, baseCoinReward: 200, xpReward: { skill: SkillName.Mining, amount: 250 } },
    { id: 'gather_titanium_ore_fouthia', questNum: 115, type: 'gather', title: 'Titanium Request', description: 'The smith needs titanium for a masterwork piece.', location: 'fouthia', target: { itemId: 'titanium_ore' }, baseCoinReward: 400, xpReward: { skill: SkillName.Mining, amount: 400 } },
    { id: 'gather_driftwood_logs_fouthia', questNum: 116, type: 'gather', title: 'Desert Wood', description: 'Driftwood is the only fuel source besides coal.', location: 'fouthia', target: { itemId: 'driftwood_logs' }, baseCoinReward: 10, xpReward: { skill: SkillName.Woodcutting, amount: 40 } },
    { id: 'gather_brimstone_fouthia', questNum: 117, type: 'gather', title: 'Volcanic Harvest', description: 'Zafira needs brimstone for her explosive mixtures.', location: 'fouthia', target: { itemId: 'brimstone' }, baseCoinReward: 250, xpReward: { skill: SkillName.Mining, amount: 300 } },
    { id: 'gather_crystalline_shell_shards_fouthia', questNum: 118, type: 'gather', title: 'Tortoise Shells', description: 'Shell shards are used for armor plating.', location: 'fouthia', target: { itemId: 'crystalline_shell_shard' }, baseCoinReward: 120, xpReward: { skill: SkillName.Crafting, amount: 150 } },
    { id: 'gather_scuttler_shell_fragments_fouthia', questNum: 119, type: 'gather', title: 'Scuttler Chitin', description: 'Fragments from scuttlers are used in alchemy.', location: 'fouthia', target: { itemId: 'scuttler_shell_fragment' }, baseCoinReward: 50, xpReward: { skill: SkillName.Herblore, amount: 60 } },
    { id: 'gather_ancient_fossils_fouthia', questNum: 120, type: 'gather', title: 'Fossil Hunt', description: 'A collector in Silverhaven pays well for desert fossils.', location: 'fouthia', target: { itemId: 'ancient_fossil' }, baseCoinReward: 300, xpReward: { skill: SkillName.Mining, amount: 200 } },
    { id: 'gather_uncut_sunstones_fouthia', questNum: 121, type: 'gather', title: 'Sunstone Seekers', description: 'Jewelers crave the rare Sunstone gems.', location: 'fouthia', target: { itemId: 'uncut_sunstone' }, baseCoinReward: 1000, xpReward: { skill: SkillName.Mining, amount: 500 } },
    { id: 'gather_waterskins_fouthia', questNum: 122, type: 'gather', title: 'Water Reserves', description: 'The town needs more waterskins for caravans.', location: 'fouthia', target: { itemId: 'waterskin' }, baseCoinReward: 20, xpReward: { skill: SkillName.Crafting, amount: 30 } },

    // --- FOUTHIA: INTERACT ---
    { id: 'interact_clean_sand_serpent_fouthia', questNum: 123, type: 'interact', title: 'Sweep the Sand', description: "The Sand Serpent Inn is always dusty. Help Zale clean up.", location: 'fouthia', locationPoiId: 'the_sand_serpent_inn', target: { name: 'Clean Tavern' }, baseCoinReward: 200, xpReward: { skill: SkillName.Strength, amount: 100 } },
    { id: 'interact_organize_armory_fouthia', questNum: 124, type: 'interact', title: 'Organize the Forge', description: "Khalid's armory is a mess of metal scraps. Sort them out.", location: 'fouthia', locationPoiId: 'fouthia_armorer', target: { name: 'Organize Forge' }, baseCoinReward: 250, xpReward: { skill: SkillName.Smithing, amount: 120 } },
    { id: 'interact_sort_alchemy_fouthia', questNum: 125, type: 'interact', title: 'Sort Ingredients', description: "Zafira needs help organizing her rare desert herbs.", location: 'fouthia', locationPoiId: 'fouthia_alchemist', target: { name: 'Sort Herbs' }, baseCoinReward: 250, xpReward: { skill: SkillName.Herblore, amount: 120 } },
    { id: 'interact_patrol_fouthia', questNum: 126, type: 'interact', title: 'Barracks Inspection', description: "Help Captain Omar inspect the equipment at the barracks.", location: 'fouthia', locationPoiId: 'fouthia_barracks', target: { name: 'Inspect Gear' }, baseCoinReward: 220, xpReward: { skill: SkillName.Defence, amount: 110 } },
    { id: 'interact_water_oasis_fouthia', questNum: 127, type: 'interact', title: 'Tend the Oasis', description: "The palm trees at the Dying Oasis need care.", location: 'fouthia', locationPoiId: 'sw_dying_oasis', target: { name: 'Tend Trees' }, baseCoinReward: 180, xpReward: { skill: SkillName.Woodcutting, amount: 90 } },
    { id: 'interact_scout_salt_flats_fouthia', questNum: 128, type: 'interact', title: 'Scout the Flats', description: "Check for signs of monster movement near the Salt Flats entrance.", location: 'fouthia', locationPoiId: 'salt_flats_entrance', target: { name: 'Scout Area' }, baseCoinReward: 200, xpReward: { skill: SkillName.Slayer, amount: 100 } },
    { id: 'interact_inspect_pillar_fouthia', questNum: 129, type: 'interact', title: 'Inspect the Pillar', description: "Check the Great Salt Pillar for structural stability.", location: 'fouthia', locationPoiId: 'the_great_salt_pillar', target: { name: 'Inspect Pillar' }, baseCoinReward: 300, xpReward: { skill: SkillName.Mining, amount: 150 } },
    { id: 'interact_clear_debris_fouthia', questNum: 130, type: 'interact', title: 'Clear Ruins', description: "Clear sand and debris from the Ruined Outpost.", location: 'fouthia', locationPoiId: 'sw_ruined_outpost', target: { name: 'Clear Debris' }, baseCoinReward: 250, xpReward: { skill: SkillName.Strength, amount: 130 } },
    { id: 'interact_inspect_watchtower_fouthia', questNum: 131, type: 'interact', title: 'Check Watchtower', description: "Ensure the Abandoned Watchtower hasn't been reclaimed by bandits.", location: 'fouthia', locationPoiId: 'sp_abandoned_watchtower', target: { name: 'Inspect Tower' }, baseCoinReward: 220, xpReward: { skill: SkillName.Slayer, amount: 110 } },

    // --- SANCTITY: KILL ---
    { id: 'kill_wolves_sanctity', questNum: 132, type: 'kill', title: 'Wolf Threat', description: 'Wolves are prowling near the Shepherd\'s Path.', location: 'sanctity', target: { monsterId: 'wolf' }, baseCoinReward: 150, xpReward: { skill: SkillName.Attack, amount: 50 } },
    { id: 'kill_wild_boars_sanctity', questNum: 133, type: 'kill', title: 'Boar Trouble', description: 'Wild boars are digging up the fields near the old farmstead.', location: 'sanctity', target: { monsterId: 'wild_boar' }, baseCoinReward: 110, xpReward: { skill: SkillName.Strength, amount: 44 } },
    { id: 'kill_bears_sanctity', questNum: 134, type: 'kill', title: 'Bear Hunt', description: 'Bears in the woods are becoming a danger to fishermen.', location: 'sanctity', target: { monsterId: 'bear' }, baseCoinReward: 180, xpReward: { skill: SkillName.Defence, amount: 70 } },
    { id: 'kill_highwaymen_sanctity', questNum: 135, type: 'kill', title: 'Highway Patrol', description: 'Clear the crossroads of highwaymen.', location: 'sanctity', target: { monsterId: 'highwayman' }, baseCoinReward: 105, xpReward: { skill: SkillName.Attack, amount: 70 } },
    { id: 'kill_plains_lions_sanctity', questNum: 136, type: 'kill', title: 'Lion Hunt', description: 'Lions on the savanna are hunting too close to town.', location: 'sanctity', target: { monsterId: 'plains_lion' }, baseCoinReward: 210, xpReward: { skill: SkillName.Strength, amount: 150 } },
    { id: 'kill_sunstone_golems_sanctity', questNum: 137, type: 'kill', title: 'Golem Breaker', description: 'Sunstone Golems have gone rogue in the quarry.', location: 'sanctity', target: { monsterId: 'sunstone_golem' }, baseCoinReward: 225, xpReward: { skill: SkillName.Strength, amount: 180 } },
    { id: 'kill_roc_hatchlings_sanctity', questNum: 138, type: 'kill', title: 'Roc Control', description: 'Roc hatchlings are preying on local livestock.', location: 'sanctity', target: { monsterId: 'roc_hatchling' }, baseCoinReward: 240, xpReward: { skill: SkillName.Ranged, amount: 160 } },
    { id: 'kill_zealous_nomads_sanctity', questNum: 139, type: 'kill', title: 'Fanatic Purge', description: 'Zealots on the plateau are harassing pilgrims.', location: 'sanctity', target: { monsterId: 'zealous_nomad' }, baseCoinReward: 250, xpReward: { skill: SkillName.Attack, amount: 170 } },
    { id: 'kill_shadow_cats_sanctity', questNum: 140, type: 'kill', title: 'Shadow Stalkers', description: 'Shadow Cats in the grove are hunting travelers.', location: 'sanctity', target: { monsterId: 'shadow_cat' }, baseCoinReward: 165, xpReward: { skill: SkillName.Slayer, amount: 120 } },
    { id: 'kill_wispwood_spirits_sanctity', questNum: 141, type: 'kill', title: 'Spirit Rest', description: 'Calm the agitated Wispwood Spirits.', location: 'sanctity', target: { monsterId: 'wispwood_spirit' }, baseCoinReward: 174, xpReward: { skill: SkillName.Magic, amount: 100 } },
    { id: 'kill_timid_dryads_sanctity', questNum: 142, type: 'kill', title: 'Corrupted Nature', description: 'Even the dryads are turning hostile. Defend yourself.', location: 'sanctity', target: { monsterId: 'timid_dryad' }, baseCoinReward: 186, xpReward: { skill: SkillName.Ranged, amount: 140 } },
    { id: 'kill_bramble_lurkers_sanctity', questNum: 143, type: 'kill', title: 'Thorn Clearing', description: 'Lurkers in the brambles are ambushing hunters.', location: 'sanctity', target: { monsterId: 'bramble_lurker' }, baseCoinReward: 195, xpReward: { skill: SkillName.Defence, amount: 160 } },
    { id: 'kill_feywood_stalkers_sanctity', questNum: 144, type: 'kill', title: 'Stalker Hunt', description: 'Feywood Stalkers are a menace to the grove.', location: 'sanctity', target: { monsterId: 'feywood_stalker' }, baseCoinReward: 204, xpReward: { skill: SkillName.Slayer, amount: 150 } },
    { id: 'kill_enchanted_boars_sanctity', questNum: 145, type: 'kill', title: 'Magical Beasts', description: 'Enchanted Boars are rampaging.', location: 'sanctity', target: { monsterId: 'enchanted_boar' }, baseCoinReward: 210, xpReward: { skill: SkillName.Strength, amount: 180 } },
    { id: 'kill_frostfang_wolves_sanctity', questNum: 146, type: 'kill', title: 'Mountain Wolves', description: 'Frostfang Wolves are descending from the peaks.', location: 'sanctity', target: { monsterId: 'frostfang_wolf' }, baseCoinReward: 198, xpReward: { skill: SkillName.Attack, amount: 120 } },
    { id: 'kill_glacial_bears_sanctity', questNum: 147, type: 'kill', title: 'Ice Bears', description: 'Glacial Bears block the mountain pass.', location: 'sanctity', target: { monsterId: 'glacial_bear' }, baseCoinReward: 216, xpReward: { skill: SkillName.Strength, amount: 180 } },
    { id: 'kill_ice_imps_sanctity', questNum: 148, type: 'kill', title: 'Imp Mischief', description: 'Ice Imps are freezing the water supplies.', location: 'sanctity', target: { monsterId: 'ice_imp' }, baseCoinReward: 207, xpReward: { skill: SkillName.Magic, amount: 80 } },
    { id: 'kill_rime_coated_serpents_sanctity', questNum: 149, type: 'kill', title: 'Cold Blooded', description: 'Serpents on the snowy trails are dangerous.', location: 'sanctity', target: { monsterId: 'rime_coated_serpent' }, baseCoinReward: 225, xpReward: { skill: SkillName.Defence, amount: 160 } },
    { id: 'kill_frost_golems_sanctity', questNum: 150, type: 'kill', title: 'Frozen Golems', description: 'Frost Golems are guarding the upper slopes.', location: 'sanctity', target: { monsterId: 'frost_golem' }, baseCoinReward: 240, xpReward: { skill: SkillName.Strength, amount: 240 } },
    { id: 'kill_yetis_sanctity', questNum: 151, type: 'kill', title: 'Yeti Sighting', description: 'Yetis have been spotted near the caves.', location: 'sanctity', target: { monsterId: 'yeti' }, baseCoinReward: 255, xpReward: { skill: SkillName.Slayer, amount: 260 } },
    { id: 'kill_ice_trolls_sanctity', questNum: 152, type: 'kill', title: 'Troll Patrol', description: 'Ice Trolls are raiding from their outpost.', location: 'sanctity', target: { monsterId: 'ice_troll' }, baseCoinReward: 246, xpReward: { skill: SkillName.Attack, amount: 300 } },
    { id: 'kill_deranged_botanists_sanctity', questNum: 153, type: 'kill', title: 'Mad Science', description: 'Deranged Botanists in the cave are conducting dark experiments.', location: 'sanctity', target: { monsterId: 'deranged_botanist' }, baseCoinReward: 170, xpReward: { skill: SkillName.Magic, amount: 44 } },
    { id: 'kill_skeletal_archers_sanctity', questNum: 154, type: 'kill', title: 'Skeleton Crew', description: 'Skeletal Archers guard the old halls.', location: 'sanctity', target: { monsterId: 'skeletal_archer' }, baseCoinReward: 165, xpReward: { skill: SkillName.Ranged, amount: 100 } },

    // --- SANCTITY: GATHER ---
    { id: 'gather_oak_logs_sanctity', questNum: 155, type: 'gather', title: 'Oak for Construction', description: 'Oak logs are needed for building repairs.', location: 'sanctity', target: { itemId: 'oak_logs' }, baseCoinReward: 20, xpReward: { skill: SkillName.Woodcutting, amount: 30 } },
    { id: 'gather_willow_logs_sanctity', questNum: 156, type: 'gather', title: 'Willow Weaving', description: 'Willow branches are needed for baskets.', location: 'sanctity', target: { itemId: 'willow_logs' }, baseCoinReward: 35, xpReward: { skill: SkillName.Woodcutting, amount: 60 } },
    { id: 'gather_maple_logs_sanctity', questNum: 157, type: 'gather', title: 'Maple Stock', description: 'Maple logs are needed for sturdy furniture.', location: 'sanctity', target: { itemId: 'maple_logs' }, baseCoinReward: 60, xpReward: { skill: SkillName.Woodcutting, amount: 100 } },
    { id: 'gather_yew_logs_sanctity', questNum: 158, type: 'gather', title: 'Sacred Yew', description: 'Yew logs are needed for temple carvings.', location: 'sanctity', target: { itemId: 'yew_logs' }, baseCoinReward: 120, xpReward: { skill: SkillName.Woodcutting, amount: 200 } },
    { id: 'gather_feywood_logs_sanctity', questNum: 159, type: 'gather', title: 'Magical Wood', description: 'Feywood is needed for enchanted items.', location: 'sanctity', target: { itemId: 'feywood_logs' }, baseCoinReward: 250, xpReward: { skill: SkillName.Woodcutting, amount: 400 } },
    { id: 'gather_iron_ore_sanctity', questNum: 160, type: 'gather', title: 'Iron Tools', description: 'Iron ore for the town smithy.', location: 'sanctity', target: { itemId: 'iron_ore' }, baseCoinReward: 30, xpReward: { skill: SkillName.Mining, amount: 40 } },
    { id: 'gather_coal_sanctity', questNum: 161, type: 'gather', title: 'Coal Reserves', description: 'Coal to keep the fires burning.', location: 'sanctity', target: { itemId: 'coal' }, baseCoinReward: 30, xpReward: { skill: SkillName.Mining, amount: 50 } },
    { id: 'gather_silver_ore_sanctity', questNum: 162, type: 'gather', title: 'Silver Casting', description: 'Silver ore for religious icons.', location: 'sanctity', target: { itemId: 'silver_ore' }, baseCoinReward: 40, xpReward: { skill: SkillName.Mining, amount: 60 } },
    { id: 'gather_gold_ore_sanctity', questNum: 163, type: 'gather', title: 'Gold Leaf', description: 'Gold ore for gilding the chapel.', location: 'sanctity', target: { itemId: 'gold_ore' }, baseCoinReward: 120, xpReward: { skill: SkillName.Mining, amount: 150 } },
    { id: 'gather_mithril_ore_sanctity', questNum: 164, type: 'gather', title: 'Mithril Order', description: 'Mithril ore for the guard\'s armor.', location: 'sanctity', target: { itemId: 'mithril_ore' }, baseCoinReward: 55, xpReward: { skill: SkillName.Mining, amount: 300 } },
    { id: 'gather_adamantite_ore_sanctity', questNum: 165, type: 'gather', title: 'Adamant Strength', description: 'Adamantite ore for heavy plating.', location: 'sanctity', target: { itemId: 'adamantite_ore' }, baseCoinReward: 400, xpReward: { skill: SkillName.Mining, amount: 450 } },
    { id: 'gather_raw_trout_sanctity', questNum: 166, type: 'gather', title: 'River Fish', description: 'Fresh trout for the inn.', location: 'sanctity', target: { itemId: 'raw_trout' }, baseCoinReward: 25, xpReward: { skill: SkillName.Fishing, amount: 50 } },
    { id: 'gather_raw_pike_sanctity', questNum: 167, type: 'gather', title: 'Pike Catch', description: 'Pike from the river bend.', location: 'sanctity', target: { itemId: 'raw_pike' }, baseCoinReward: 45, xpReward: { skill: SkillName.Fishing, amount: 80 } },
    { id: 'gather_raw_eel_sanctity', questNum: 168, type: 'gather', title: 'Eel Basket', description: 'Eels from the pond.', location: 'sanctity', target: { itemId: 'raw_eel' }, baseCoinReward: 60, xpReward: { skill: SkillName.Fishing, amount: 100 } },

    // --- SANCTITY: INTERACT ---
    { id: 'interact_tidy_pilgrims_rest_sanctity', questNum: 169, type: 'interact', title: 'Tidy Inn', description: "Help Phoebe tidy up The Pilgrim's Rest.", location: 'sanctity', locationPoiId: 'sanctity_inn', target: { name: 'Tidy Inn' }, baseCoinReward: 150, xpReward: { skill: SkillName.Agility, amount: 50 } },
    { id: 'interact_organize_library_sanctity', questNum: 170, type: 'interact', title: 'Library Aid', description: "Help Anya organize scrolls in the library.", location: 'sanctity', locationPoiId: 'sanctity_library', target: { name: 'Sort Scrolls' }, baseCoinReward: 200, xpReward: { skill: SkillName.Magic, amount: 100 } },
    { id: 'interact_assist_kael_sanctity', questNum: 171, type: 'interact', title: 'Smithing Help', description: "Assist Artisan Kael in the workshop.", location: 'sanctity', locationPoiId: 'sanctity_artisans_quarter', target: { name: 'Assist Kael' }, baseCoinReward: 250, xpReward: { skill: SkillName.Smithing, amount: 120 } },
    { id: 'interact_pray_chapel_sanctity', questNum: 172, type: 'interact', title: 'Morning Prayer', description: "Join the morning prayers at the Grand Chapel.", location: 'sanctity', locationPoiId: 'sanctity_chapel', target: { name: 'Pray' }, baseCoinReward: 100, xpReward: { skill: SkillName.Prayer, amount: 150 } },
];
