import { Monster, MonsterType, SkillName, MonsterId } from '@/types';

export const demon: Monster[] = [
    {
        id: 'blight_imp', name: 'Blight Imp', level: 7, maxHp: 18, attack: 1, magic: 8, strength: 3, defence: 5,
        stabDefence: 5, slashDefence: 5, crushDefence: 5, rangedDefence: 10, magicDefence: 0,
        iconUrl: 'imp-laugh',
        guaranteedDrops: [
            { itemId: 'imp_ashes', minQuantity: 1, maxQuantity: 1 }
        ],
        mainDrops: [
            { tableId: 'herb_table', chance: "1/4", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'binding_rune', chance: "1/5", minQuantity: 5, maxQuantity: 10 },
            { itemId: 'flux_rune', chance: "1/20", minQuantity: 1, maxQuantity: 3 },
            { itemId: 'ashes', chance: "1/4", minQuantity: 1, maxQuantity: 2 },
            { itemId: 'ember_rune', chance: "1/8", minQuantity: 1, maxQuantity: 5 },
            { itemId: 'grimy_guromoot', chance: "1/12", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bones', chance: "1/8", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Demon], attackSpeed: 4, respawnTime: 600000, aggressive: true, alwaysAggressive: true, attackStyle: 'magic',
        specialAttacks: [{ name: 'Wilt', chance: 0.2, effect: 'stat_drain', skill: SkillName.Strength, value: -2 }],
        elementalWeakness: 'fire', // Quest-specific summon
    },
    {
        id: 'magma_imp', name: 'Magma Imp', level: 43, maxHp: 60, attack: 1, ranged: 50, strength: 20, defence: 40,
        stabDefence: 25, slashDefence: 25, crushDefence: 25, rangedDefence: 30, magicDefence: 30,
        iconUrl: 'imp',
        guaranteedDrops: [
            { itemId: 'imp_ashes', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'ember_rune', minQuantity: 40, maxQuantity: 80 },
        ],
        mainDrops: [
            { itemId: 'brimstone', chance: "1/10", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'flux_rune', chance: "2/5", minQuantity: 15, maxQuantity: 30 },
            { itemId: 'ember_rune', chance: "1/3", minQuantity: 10, maxQuantity: 25 },
            { itemId: 'ashes', chance: "1/3", minQuantity: 1, maxQuantity: 5 },
            { itemId: 'coal', chance: "1/5", minQuantity: 3, maxQuantity: 8, noted: true },
            { itemId: 'iron_ore', chance: "1/8", minQuantity: 2, maxQuantity: 6, noted: true },
            { itemId: 'gold_ore', chance: "1/12", minQuantity: 1, maxQuantity: 4, noted: true },
            { itemId: 'uncut_ruby', chance: "1/100", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Demon, MonsterType.Elemental], attackSpeed: 2, respawnTime: 90000, aggressive: true, alwaysAggressive: true, attackStyle: 'ranged',
        fireImmunity: true,
    },
    {
        id: 'fire_fiend', name: 'Fire Fiend', level: 58, maxHp: 70, attack: 50, strength: 55, defence: 50,
        stabDefence: 40, slashDefence: 40, crushDefence: 40, rangedDefence: 40, magicDefence: 40,
        iconUrl: 'portal',
        guaranteedDrops: [
            { itemId: 'imp_ashes', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'ember_rune', chance: "1/2", minQuantity: 20, maxQuantity: 40 },
            { itemId: 'brimstone', chance: "1/8", minQuantity: 1, maxQuantity: 2 },
            { tableId: 'herb_table', chance: "1/10" },
            { itemId: 'coal', chance: "1/4", minQuantity: 10, maxQuantity: 20, noted: true },
            { itemId: 'gold_bar', chance: "1/15", minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'mithril_ore', chance: "1/20", minQuantity: 1, maxQuantity: 5, noted: true },
            { itemId: 'uncut_ruby', chance: "1/80", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'ember_talisman', chance: "1/256", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Demon, MonsterType.Elemental], attackSpeed: 4, respawnTime: 45000, aggressive: true, attackStyle: 'crush',
        fireImmunity: true,
    },
    {
        id: 'lesser_incubus', name: 'Lesser Incubus', level: 82, maxHp: 79, attack: 68, strength: 70, defence: 71, customMaxHit: 8,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: -10,
        iconUrl: 'horned-skull',
        guaranteedDrops: [
            { itemId: 'imp_ashes', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'steel_full_helm', chance: "1/32" },
            { itemId: 'steel_axe', chance: "1/32" },
            { itemId: 'steel_scimitar', chance: "1/42.67" },
            { itemId: 'mithril_square_shield', chance: "1/128" },
            { itemId: 'mithril_chainbody', chance: "1/128" },
            { itemId: 'runic_med_helm', chance: "1/128" },
            { itemId: 'ember_rune', chance: "1/16", minQuantity: 60, maxQuantity: 60 },
            { itemId: 'flux_rune', chance: "1/25.6", minQuantity: 12, maxQuantity: 12 },
            { itemId: 'nexus_rune', chance: "1/42.67", minQuantity: 3, maxQuantity: 3 },
            { itemId: 'ember_rune', chance: "1/128", minQuantity: 30, maxQuantity: 30 },
            { itemId: 'coins', chance: "1/3.2", minQuantity: 120, maxQuantity: 120 },
            { itemId: 'coins', chance: "1/4.414", minQuantity: 40, maxQuantity: 40 },
            { itemId: 'coins', chance: "1/12.8", minQuantity: 200, maxQuantity: 200 },
            { itemId: 'coins', chance: "1/18.29", minQuantity: 10, maxQuantity: 10 },
            { itemId: 'coins', chance: "1/128", minQuantity: 450, maxQuantity: 450 },
            { itemId: 'coins', chance: "1/128", minQuantity: 10, maxQuantity: 10 },
            { itemId: 'gold_ore', chance: "1/64" },
        ],
        types: [MonsterType.Demon], attackSpeed: 4, respawnTime: 90000, aggressive: true, alwaysAggressive: true, attackStyle: 'slash',
    },
    {
        id: 'greater_incubus', name: 'Greater Incubus', level: 101, maxHp: 87, attack: 76, strength: 78, defence: 81, customMaxHit: 9,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: -10,
        iconUrl: 'brute',
        guaranteedDrops: [
            { itemId: 'imp_ashes', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'ember_rune', chance: "1/16", minQuantity: 75, maxQuantity: 75 },
            { itemId: 'flux_rune', chance: "1/42.67", minQuantity: 15, maxQuantity: 15 },
            { itemId: 'nexus_rune', chance: "1/42.67", minQuantity: 5, maxQuantity: 5 },
            { itemId: 'ember_rune', chance: "1/128", minQuantity: 37, maxQuantity: 37 },
            { itemId: 'uncut_ruby', chance: "1/64", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'steel_greatsword', chance: "1/32" },
            { itemId: 'steel_axe', chance: "1/42.67" },
            { itemId: 'steel_battleaxe', chance: "1/42.67" },
            { itemId: 'mithril_kiteshield', chance: "1/128" },
            { itemId: 'adamantite_platelegs', chance: "1/128" },
            { itemId: 'runic_full_helm', chance: "1/128" },
            { itemId: 'cooked_tuna', chance: "1/42.67" },
            { itemId: 'gold_bar', chance: "1/64" },
            { itemId: 'thread', chance: "1/128", minQuantity: 10, maxQuantity: 10 },
            { itemId: 'coins', chance: "1/3.2", minQuantity: 132, maxQuantity: 132 },
            { itemId: 'coins', chance: "1/4.414", minQuantity: 44, maxQuantity: 44 },
            { itemId: 'coins', chance: "1/12.8", minQuantity: 220, maxQuantity: 220 },
            { itemId: 'coins', chance: "1/18.29", minQuantity: 11, maxQuantity: 11 },
            { itemId: 'coins', chance: "1/128", minQuantity: 460, maxQuantity: 460 },
        ],
        types: [MonsterType.Demon], attackSpeed: 4, respawnTime: 120000, aggressive: true, alwaysAggressive: true, attackStyle: 'slash',
        maxTaskCount: [15, 30],
    },
    {
        id: 'succubus', name: 'Succubus', level: 124, maxHp: 157, attack: 145, strength: 148, defence: 152, customMaxHit: 16,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: -10,
        iconUrl: 'succubus',
        guaranteedDrops: [
            { itemId: 'imp_ashes', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'mithril_sword', chance: "1/32" },
            { itemId: 'steel_battleaxe', chance: "1/42.67" },
            { itemId: 'mithril_axe', chance: "1/64" },
            { itemId: 'mithril_kiteshield', chance: "1/128" },
            { itemId: 'runic_med_helm', chance: "1/128" },
            { itemId: 'runic_chainbody', chance: "1/128" },
            { itemId: 'gust_rune', chance: "1/16", minQuantity: 50, maxQuantity: 50 },
            { itemId: 'flux_rune', chance: "1/18.29", minQuantity: 10, maxQuantity: 10 },
            { itemId: 'anima_rune', chance: "1/32", minQuantity: 7, maxQuantity: 7 },
            { itemId: 'ember_rune', chance: "1/128", minQuantity: 37, maxQuantity: 37 },
            { itemId: 'passage_rune', chance: "1/128", minQuantity: 3, maxQuantity: 3 },
            { itemId: 'coins', chance: "1/3.2", minQuantity: 132, maxQuantity: 132 },
            { itemId: 'coins', chance: "1/18.29", minQuantity: 30, maxQuantity: 30 },
            { itemId: 'coins', chance: "1/21.33", minQuantity: 44, maxQuantity: 44 },
            { itemId: 'coins', chance: "1/21.33", minQuantity: 220, maxQuantity: 220 },
            { itemId: 'coins', chance: "1/128", minQuantity: 460, maxQuantity: 460 },
            { itemId: 'cooked_lobster', chance: "1/42.67" },
            { itemId: 'adamantite_bar', chance: "1/64" },
            { itemId: 'defence_potion', chance: "1/128", doses: 3 },

        ],
        types: [MonsterType.Demon], attackSpeed: 4, respawnTime: 180000, aggressive: true, alwaysAggressive: true, attackStyle: 'slash',
        maxTaskCount: [10, 25],
    },
];