import { Monster, MonsterType, SkillName } from '@/types';

export const frostfang: Monster[] = [
    {
        id: 'frostfang_wolf', name: 'Frostfang Wolf', level: 66, maxHp: 60, attack: 60, strength: 55, defence: 50,
        stabDefence: 50, slashDefence: 55, crushDefence: 45, rangedDefence: 48, magicDefence: 40,
        iconUrl: 'https://api.iconify.design/game-icons:wolf-head.svg',
        guaranteedDrops: [ { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }, { itemId: 'wolf_pelt', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'raw_tuna', chance: '1/4', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'aqua_rune', chance: '1/2', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'mithril_arrow', chance: '1/8', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'mithril_dagger', chance: '1/64' },
            { tableId: 'gem_table', chance: '1/128' },
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Beast], attackSpeed: 3, respawnTime: 25000, aggressive: true, alwaysAggressive: true, attackStyle: 'slash', customMaxHit: 10,
    },
    {
        id: 'glacial_bear', name: 'Glacial Bear', level: 72, maxHp: 90, attack: 65, strength: 68, defence: 75,
        stabDefence: 70, slashDefence: 72, crushDefence: 80, rangedDefence: 70, magicDefence: 65,
        iconUrl: 'https://api.iconify.design/game-icons:bear-head.svg',
        guaranteedDrops: [ { itemId: 'big_bones', minQuantity: 2, maxQuantity: 2 }, { itemId: 'bear_pelt', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'raw_swordfish', chance: '1/4', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'mithril_ore', chance: '1/6', minQuantity: 2, maxQuantity: 4, noted: true },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'adamantite_ore', chance: '1/12', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'mithril_mace', chance: '1/128' },
            { itemId: 'uncut_sapphire', chance: '1/64' },
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Beast], attackSpeed: 6, respawnTime: 45000, aggressive: true, attackStyle: 'crush', customMaxHit: 14,
        fireWeakness: 0.5,
    },
    {
        id: 'ice_imp', name: 'Ice Imp', level: 69, maxHp: 40, attack: 1, magic: 70, strength: 1, defence: 55,
        stabDefence: 40, slashDefence: 40, crushDefence: 40, rangedDefence: 50, magicDefence: 70,
        iconUrl: 'https://api.iconify.design/game-icons:imp-laugh.svg',
        guaranteedDrops: [ { itemId: 'ashes', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/2', minQuantity: 30, maxQuantity: 60 },
            { itemId: 'binding_rune', chance: '1/8', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'ember_rune', chance: '1/10', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'uncut_sapphire', chance: '1/64' },
            { itemId: 'staff_of_aqua', chance: '1/256' },
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Demon], attackSpeed: 3, respawnTime: 20000, aggressive: true, attackStyle: 'magic', customMaxHit: 9,
        fireWeakness: 0.5,
    },
    {
        id: 'rime_coated_serpent', name: 'Rime-Coated Serpent', level: 75, maxHp: 80, attack: 70, strength: 72, defence: 65,
        stabDefence: 65, slashDefence: 70, crushDefence: 60, rangedDefence: 62, magicDefence: 55,
        iconUrl: 'https://api.iconify.design/game-icons:sea-serpent.svg',
        guaranteedDrops: [ { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }, { itemId: 'serpent_scale', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'raw_tuna', chance: '1/5', minQuantity: 2, maxQuantity: 2, noted: true },
            { tableId: 'herb_table', chance: '1/8' },
            { itemId: 'yew_logs', chance: '1/12', minQuantity: 2, maxQuantity: 8, noted: true },
            { itemId: 'mithril_bar', chance: '1/20', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'adamantite_dagger', chance: '1/128' },
        ],
        specialAttacks: [{ name: 'Frostbite', chance: 0.2, effect: 'stat_drain', skill: SkillName.Attack, value: -3 },
                         { name: 'Frosty Gas', chance: 0.1, effect: 'poison', damage: 6, poisonChance: 0.75 }
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Beast], attackSpeed: 4, respawnTime: 35000, aggressive: true, attackStyle: 'slash', customMaxHit: 12,
        fireWeakness: 0.5,
    },
    {
        id: 'frost_golem', name: 'Frost Golem', level: 80, maxHp: 120, attack: 75, strength: 78, defence: 90,
        stabDefence: 100, slashDefence: 100, crushDefence: 70, rangedDefence: 100, magicDefence: 90,
        iconUrl: 'https://api.iconify.design/game-icons:ice-golem.svg',
        guaranteedDrops: [ { itemId: 'golem_core', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'stone_rune', chance: '1/2', minQuantity: 50, maxQuantity: 100 },
            { itemId: 'rune_essence', chance: '1/4', minQuantity: 20, maxQuantity: 40, noted: true },
            { itemId: 'adamantite_ore', chance: '1/8', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'mithril_bar', chance: '1/10', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'uncut_ruby', chance: '1/64' },
            { itemId: 'uncut_diamond', chance: '1/256' },
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Elemental, MonsterType.Armored], attackSpeed: 7, respawnTime: 60000, aggressive: true, attackStyle: 'crush', customMaxHit: 13,
        fireWeakness: 0.5,
    },
    {
        id: 'yeti', name: 'Yeti', level: 85, maxHp: 130, attack: 80, strength: 85, defence: 75,
        stabDefence: 70, slashDefence: 70, crushDefence: 85, rangedDefence: 72, magicDefence: 65,
        iconUrl: 'https://api.iconify.design/game-icons:yeti.svg',
        guaranteedDrops: [ { itemId: 'big_bones', minQuantity: 2, maxQuantity: 3 }, { itemId: 'bear_pelt', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'cooked_swordfish', chance: '1/4', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'mithril_warhammer', chance: '1/64' },
            { itemId: 'adamantite_platelegs', chance: '1/128' },
            { itemId: 'uncut_diamond', chance: '1/128' },
            { itemId: 'runic_bar', chance: '1/512', minQuantity: 1, maxQuantity: 1, noted: true },
        ],
        specialAttacks: [{ name: 'Ground Slam', chance: 0.2, effect: 'damage_multiplier', value: 1.5 }],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Beast], attackSpeed: 5, respawnTime: 70000, aggressive: true, attackStyle: 'crush', customMaxHit: 16,
    },
    {
        id: 'frozen_shade', name: 'Frozen Shade', level: 78, maxHp: 70, attack: 1, magic: 80, strength: 1, defence: 70,
        stabDefence: 50, slashDefence: 50, crushDefence: 50, rangedDefence: 75, magicDefence: 90,
        iconUrl: 'https://api.iconify.design/game-icons:ghost.svg',
        guaranteedDrops: [ { itemId: 'consecrated_dust', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'astral_rune', chance: '1/2', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'aether_rune', chance: '1/6', minQuantity: 8, maxQuantity: 15 },
            { itemId: 'nexus_rune', chance: '1/10', minQuantity: 5, maxQuantity: 10 },
            { itemId: 'mithril_scimitar', chance: '1/128' },
            { itemId: 'wizard_robe_top', chance: '1/256' },
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Undead, MonsterType.Elemental], attackSpeed: 4, respawnTime: 40000, aggressive: true, attackStyle: 'magic', customMaxHit: 15,
    },
    {
        id: 'ice_troll', name: 'Ice Troll', level: 82, maxHp: 150, attack: 78, strength: 80, defence: 70,
        stabDefence: 65, slashDefence: 65, crushDefence: 75, rangedDefence: 68, magicDefence: 60,
        iconUrl: 'https://api.iconify.design/game-icons:troll.svg',
        guaranteedDrops: [ { itemId: 'big_bones', minQuantity: 1, maxQuantity: 2 }, { itemId: 'bear_pelt', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'raw_swordfish', chance: '1/3', minQuantity: 1, maxQuantity: 4 },
            { itemId: 'adamantite_ore', chance: '1/8', minQuantity: 1, maxQuantity: 5, noted: true },
            { itemId: 'mithril_platelegs', chance: '1/128' },
            { itemId: 'uncut_ruby', chance: '1/128' },
            { itemId: 'adamantite_warhammer', chance: '1/256' },
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 65000, aggressive: true, attackStyle: 'crush', customMaxHit: 14,
    },
    {
        id: 'young_frosthide_dragon', name: 'Young Frosthide Dragon', level: 88, maxHp: 100, attack: 85, magic: 80, strength: 85, defence: 85,
        stabDefence: 90, slashDefence: 90, crushDefence: 80, rangedDefence: 85, magicDefence: 75,
        iconUrl: 'https://api.iconify.design/game-icons:dragon-head.svg',
        guaranteedDrops: [ { itemId: 'dragon_bones', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'frost_hide', chance: '1/2', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'mithril_kiteshield', chance: '1/32' },
            { tableId: 'gem_table', chance: '1/48' },
            { itemId: 'yew_logs', chance: '1/8', minQuantity: 20, maxQuantity: 50, noted: true },
            { itemId: 'anima_rune', chance: '1/10', minQuantity: 5, maxQuantity: 15 },
            { itemId: 'adamantite_sword', chance: '1/128' },
            { itemId: 'super_strength_potion', chance: '1/64' },
        ],
        specialAttacks: [{ name: 'Ice Breath', chance: 0.3, effect: 'magic_bypass_defence', maxHit: 16 }],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Beast], attackSpeed: 5, respawnTime: 120000, aggressive: true, alwaysAggressive: true, attackStyle: 'slash', customMaxHit: 14,
    },
    {
        id: 'tundra_stalker', name: 'Tundra Stalker', level: 74, maxHp: 75, attack: 75, strength: 70, defence: 60,
        stabDefence: 55, slashDefence: 65, crushDefence: 50, rangedDefence: 58, magicDefence: 50,
        iconUrl: 'https://api.iconify.design/game-icons:saber-toothed-cat-head.svg',
        guaranteedDrops: [ { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }, { itemId: 'wolf_pelt', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'raw_swordfish', chance: '1/3' },
            { itemId: 'raw_tuna', chance: '1/5', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'aqua_rune', chance: '1/2', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'feathers', chance: '1/4', minQuantity: 20, maxQuantity: 50 },
            { itemId: 'mithril_dagger', chance: '1/64' },
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Beast], attackSpeed: 3, respawnTime: 30000, aggressive: true, attackStyle: 'slash', customMaxHit: 12,
    },
    {
        id: 'cryo_spider', name: 'Cryo-Spider', level: 69, maxHp: 65, attack: 1, ranged: 70, strength: 1, defence: 60,
        stabDefence: 55, slashDefence: 55, crushDefence: 50, rangedDefence: 65, magicDefence: 55,
        iconUrl: 'https://api.iconify.design/game-icons:spider-face.svg',
        guaranteedDrops: [ { itemId: 'spider_silk', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/2', minQuantity: 40, maxQuantity: 80 },
            { itemId: 'spider_eggs', chance: '1/6', minQuantity: 1, maxQuantity: 2 },
            { itemId: 'yew_logs', chance: '1/16', minQuantity: 5, maxQuantity: 15, noted: true },
            { itemId: 'uncut_sapphire', chance: '1/50' },
            { itemId: 'uncut_emerald', chance: '1/100' },
        ],
        specialAttacks: [{ name: 'Chilled', chance: 0.15, effect: 'stun', duration: 2000 }],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Beast], attackSpeed: 3, respawnTime: 28000, aggressive: true, attackStyle: 'ranged', customMaxHit: 9,
        fireWeakness: 0.5,
    },
    {
        id: 'hoarfrost_nomad', name: 'Hoarfrost Nomad', level: 77, maxHp: 85, attack: 72, strength: 75, defence: 70,
        stabDefence: 70, slashDefence: 72, crushDefence: 68, rangedDefence: 65, magicDefence: 60,
        iconUrl: 'https://api.iconify.design/game-icons:hood.svg',
        guaranteedDrops: [ { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'adamantite_arrow', chance: '1/4', minQuantity: 10, maxQuantity: 30 },
            { itemId: 'cooked_swordfish', chance: '1/6', minQuantity: 1, maxQuantity: 2 },
            { itemId: 'super_strength_potion', chance: '1/20' },
            { itemId: 'prayer_potion', chance: '1/30' },
            { itemId: 'mithril_sword', chance: '1/32' },
            { itemId: 'adamantite_axe', chance: '1/64' },
        ],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 40000, aggressive: true, attackStyle: 'slash', customMaxHit: 13,
    },
    {
        id: 'ice_elemental', name: 'Ice Elemental', level: 84, maxHp: 90, attack: 1, magic: 85, strength: 1, defence: 75,
        stabDefence: 60, slashDefence: 60, crushDefence: 60, rangedDefence: 80, magicDefence: 95,
        iconUrl: 'https://api.iconify.design/game-icons:ice-golem.svg',
        guaranteedDrops: [ { itemId: 'ashes', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/1', minQuantity: 50, maxQuantity: 100 },
            { itemId: 'rune_essence', chance: '1/3', minQuantity: 50, maxQuantity: 150, noted: true },
            { itemId: 'astral_rune', chance: '1/4', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'aether_rune', chance: '1/8', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'uncut_diamond', chance: '1/200' },
            { itemId: 'staff_of_aqua', chance: '1/128' },
        ],
        fireWeakness: 0.5,
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Elemental], attackSpeed: 4, respawnTime: 55000, aggressive: true, attackStyle: 'magic', customMaxHit: 16,
    },
    {
        id: 'glacial_wyrm', name: 'Glacial Wyrm', level: 90, maxHp: 180, attack: 90, magic: 88, strength: 90, defence: 95,
        stabDefence: 90, slashDefence: 95, crushDefence: 100, rangedDefence: 85, magicDefence: 80,
        iconUrl: 'https://api.iconify.design/game-icons:sea-dragon.svg',
        guaranteedDrops: [ { itemId: 'dragon_bones', minQuantity: 1, maxQuantity: 1 }, { itemId: 'wyrmscale', minQuantity: 1, maxQuantity: 1 } ],
        mainDrops: [
            { itemId: 'coins', chance: '1/16', minQuantity: 5000, maxQuantity: 15000 },
            { itemId: 'adamantite_bar', chance: '1/2', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'runic_bar', chance: '1/8', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'uncut_diamond', chance: '1/16', minQuantity: 1, maxQuantity: 2 },
            { itemId: 'runic_warhammer', chance: '1/128' },
            { itemId: 'runic_platelegs', chance: '1/256' },
        ],
        specialAttacks: [{ name: 'Ice Breath', chance: 0.25, effect: 'magic_bypass_defence', maxHit: 16 }],
        tertiaryDrops: [
            { itemId: 'frostfang_key', chance: 0.001953125, minQuantity: 1, maxQuantity: 1 },
            { itemId: 'shard_of_true_ice', chance: 1, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Dragon], attackSpeed: 5, respawnTime: 240000, aggressive: true, attackStyle: 'crush', customMaxHit: 16,
        fireWeakness: 0.5,
    },
];