import { Monster, MonsterType, SkillName, SpellElement, MonsterId } from '@/types';

export const humanoids: Monster[] = [
    {
        id: 'abyssal_knight', name: 'Abyssal Knight', level: 65, maxHp: 100, attack: 55, strength: 60, defence: 70,
        stabDefence: 80, slashDefence: 80, crushDefence: 70, rangedDefence: 85, magicDefence: 10,
        iconUrl: 'black-knight-helm',
        guaranteedDrops: [
            { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'adamantite_platebody', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'adamantite_platelegs', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'runic_kiteshield', chance: "1/256", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'cooked_swordfish', chance: "1/4", minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'adamantite_bar', chance: "1/10", minQuantity: 1, maxQuantity: 3, noted: true },
        ],
        tertiaryDrops: [
            { itemId: 'nexus_talisman', chance: 0.0078125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 5, respawnTime: 90000, aggressive: true, alwaysAggressive: true, attackStyle: 'slash',
        maxTaskCount: [20, 35],
    },
    {
        id: 'adventurer', name: 'Adventurer', level: 86, maxHp: 100, attack: 80, customMaxHit: 14, strength: 85, defence: 85,
        stabDefence: 90, slashDefence: 90, crushDefence: 85, rangedDefence: 90, magicDefence: 40,
        iconUrl: 'adventurer',
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'super_attack_potion', chance: "1/20", minQuantity: 1, maxQuantity: 1, doses: 3 },
            { itemId: 'cooked_shark', chance: "1/10", minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'runic_bar', chance: "1/12", minQuantity: 1, maxQuantity: 1, noted: true },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 4, respawnTime: 120000, aggressive: false, attackStyle: 'slash'
    },
    {
        id: 'bandit_bruiser', name: 'Bandit Bruiser', level: 36, maxHp: 61, attack: 37, strength: 40, defence: 35,
        stabDefence: 60, slashDefence: 58, crushDefence: 62, rangedDefence: 58, magicDefence: -10,
        iconUrl: 'ogre',
        guaranteedDrops: [
            { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'gust_rune', chance: "1/5", minQuantity: 10, maxQuantity: 25 },
            { itemId: 'stone_rune', chance: "1/5", minQuantity: 10, maxQuantity: 25 },
            { itemId: 'ember_rune', chance: "1/5", minQuantity: 8, maxQuantity: 20 },
            { itemId: 'binding_rune', chance: "3/20", minQuantity: 6, maxQuantity: 18 },
            { tableId: 'herb_table', chance: "1/10", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'flux_rune', chance: "1/10", minQuantity: 3, maxQuantity: 10 },
            { itemId: 'bandit_brew', chance: "1/20", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 4, respawnTime: 45000, aggressive: true, alwaysAggressive: true, attackStyle: 'crush',
    },
    {
        id: 'bandit_leader', name: 'Bandit Leader', level: 56, maxHp: 75, attack: 42, strength: 50, defence: 50,
        stabDefence: 80, slashDefence: 92, crushDefence: 72, rangedDefence: 88, magicDefence: -10,
        iconUrl: 'overlord-helm',
        guaranteedDrops: [
            { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'stolen_caravan_goods', minQuantity: 1, maxQuantity: 1, questReq: { questId: 'missing_shipment', status: 'not_started' } },
        ],
        mainDrops: [
            { itemId: 'flux_rune', chance: "19/50", minQuantity: 15, maxQuantity: 30 },
            { itemId: 'verdant_rune', chance: "3/10", minQuantity: 10, maxQuantity: 20 },
            { tableId: 'herb_table', chance: "1/5", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bandit_leaders_cutlass', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'spiked_cape', chance: "1/512", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'iron_scimitar', chance: "1/32", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'steel_square_shield', chance: "1/64", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'steel_axe', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
        ],
        tertiaryDrops: [
            { itemId: 'passage_talisman', chance: 0.0078125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 3, respawnTime: 180000, aggressive: true, alwaysAggressive: true, attackStyle: 'slash',
        specialAttacks: [
            { name: 'Crippling Strike', chance: 0.3, effect: 'damage_multiplier', value: 1.5 },
        ],
    },
    {
        id: 'bandit_marksman', name: 'Bandit Marksman', level: 27, maxHp: 30, attack: 1, ranged: 32, strength: 15, defence: 25,
        stabDefence: 24, slashDefence: 26, crushDefence: 50, rangedDefence: 35, magicDefence: 22,
        iconUrl: 'archer',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'iron_arrow', chance: "3/10", minQuantity: 5, maxQuantity: 15 },
            { itemId: 'gust_rune', chance: "1/5", minQuantity: 8, maxQuantity: 18 },
            { itemId: 'stone_rune', chance: "1/5", minQuantity: 8, maxQuantity: 18 },
            { tableId: 'herb_table', chance: "1/10" },
            { itemId: 'ember_rune', chance: "1/10", minQuantity: 6, maxQuantity: 15 },
            { itemId: 'binding_rune', chance: "1/10", minQuantity: 4, maxQuantity: 12 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 3, respawnTime: 45000, aggressive: true, alwaysAggressive: true, attackStyle: 'ranged',
    },
    {
        id: 'cloaked_bandit', name: 'Cloaked Bandit', level: 12, maxHp: 20, attack: 9, strength: 12, defence: 10,
        stabDefence: 13, slashDefence: 14, crushDefence: 12, rangedDefence: 11, magicDefence: -10,
        iconUrl: 'hood',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'gust_rune', chance: "1/5", minQuantity: 2, maxQuantity: 8 },
            { itemId: 'stone_rune', chance: "1/5", minQuantity: 2, maxQuantity: 8 },
            { itemId: 'black_cape', chance: "1/3" },
            { tableId: 'herb_table', chance: "3/20" },
            { itemId: 'verdant_rune', chance: "13/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'flux_rune', chance: "4/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'astral_rune', chance: "1/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'passage_rune', chance: "1/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'nexus_rune', chance: "1/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'grimy_coin_pouch', chance: "1/10" },
            { itemId: 'iron_med_helm', chance: "1/32" },
            { itemId: 'iron_battleaxe', chance: "1/64" },
            { itemId: 'steel_axe', chance: "1/128" },
            { itemId: 'iron_ore', chance: "1/32" },
            { itemId: 'iron_bar', chance: "1/42" },
            { itemId: 'coal', chance: "1/64" },
            { itemId: 'coins', chance: "1/128", minQuantity: 20, maxQuantity: 20 },
            { itemId: 'coins', chance: "1/5", minQuantity: 8, maxQuantity: 8 },
            { itemId: 'coins', chance: "1/10", minQuantity: 15, maxQuantity: 15 },
            { itemId: 'coins', chance: "1/64", minQuantity: 30, maxQuantity: 30 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 45000, aggressive: true, attackStyle: 'slash',
    },
    {
        id: 'dwarf', name: 'Dwarf', level: 28, maxHp: 45, attack: 22, strength: 25, defence: 30,
        stabDefence: 32, slashDefence: 30, crushDefence: 35, rangedDefence: 25, magicDefence: 10,
        iconUrl: 'dwarf-face',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'coins', chance: "1/1", minQuantity: 25, maxQuantity: 60 },
            { itemId: 'beer', chance: "1/5" },
            { itemId: 'coal', chance: "1/10", minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'iron_pickaxe', chance: "1/200" },
            { itemId: 'hammer', chance: "10/128" },
            { itemId: 'bronze_bar', chance: "7/128" },
            { itemId: 'iron_ore', chance: "4/128" },
            { itemId: 'tin_ore', chance: "3/128" },
            { itemId: 'copper_ore', chance: "3/128" },
            { itemId: 'iron_bar', chance: "3/128" },
            { itemId: 'coal', chance: "2/128" },
            { itemId: 'bronze_axe', chance: "1/128" },
            { itemId: 'bronze_pickaxe', chance: "1/128" },
            { itemId: 'bronze_sword', chance: "1/128" },
            { itemId: 'bronze_square_shield', chance: "1/128" },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 5, respawnTime: 60000, aggressive: false, attackStyle: 'crush', alwaysDrops: true
    },
    {
        id: 'elf', name: 'Elf', level: 75, maxHp: 70, attack: 1, ranged: 70, strength: 35, defence: 70,
        stabDefence: 40, slashDefence: 40, crushDefence: 40, rangedDefence: 60, magicDefence: 65,
        iconUrl: 'elf-ear',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'coins', chance: "1/1", minQuantity: 80, maxQuantity: 200 },
            { itemId: 'adamantite_arrow', chance: "1/4", minQuantity: 5, maxQuantity: 15 },
            { itemId: 'yew_logs', chance: "1/10", minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'yew_shortbow', chance: "1/256" },
            { itemId: 'grovehide_vambs', chance: "4/128" },
            { itemId: 'grovehide_legs', chance: "3/128" },
            { itemId: 'mithril_battleaxe', chance: "2/128" },
            { itemId: 'mithril_kiteshield', chance: "1/128" },
            { itemId: 'adamantite_full_helm', chance: "1/128" },
            { itemId: 'runic_dagger', chance: "1/128" },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 3, respawnTime: 90000, aggressive: false, attackStyle: 'ranged', alwaysDrops: true
    },
    {
        id: 'farmer', name: 'Farmer', level: 7, maxHp: 15, attack: 4, strength: 5, defence: 5,
        stabDefence: 2, slashDefence: 3, crushDefence: 2, rangedDefence: 1, magicDefence: 0,
        iconUrl: 'farmer',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'coins', chance: "1/2", minQuantity: 1, maxQuantity: 10 },
            { tableId: 'herb_table', chance: "1/20" },
            { itemId: 'seeds', chance: "1/10", minQuantity: 1, maxQuantity: 5 },
            { itemId: 'stone_rune', chance: "1/64", minQuantity: 4, maxQuantity: 4 },
            { itemId: 'ember_rune', chance: "1/64", minQuantity: 6, maxQuantity: 6 },
            { itemId: 'binding_rune', chance: "1/64", minQuantity: 9, maxQuantity: 9 },
            { itemId: 'flux_rune', chance: "1/128", minQuantity: 2, maxQuantity: 2 },

        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 60000, aggressive: false, attackStyle: 'crush', alwaysDrops: true
    },
    {
        id: 'fouthian_guard', name: 'Fouthian Guard', level: 35, maxHp: 55, attack: 30, strength: 32, defence: 35,
        stabDefence: 40, slashDefence: 38, crushDefence: 35, rangedDefence: 42, magicDefence: 15,
        iconUrl: 'desert-helmet',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'coins', chance: "1/1", minQuantity: 40, maxQuantity: 80 },
            { itemId: 'waterskin', chance: "1/8", doses: 4 },
            { itemId: 'steel_scimitar', chance: "1/128" },
            { itemId: 'iron_bolts', chance: "10/128", minQuantity: 2, maxQuantity: 12 },
            { itemId: 'steel_arrow', chance: "4/128" },
            { itemId: 'bronze_arrow', chance: "3/128" },
            { itemId: 'gust_rune', chance: "2/128", minQuantity: 6, maxQuantity: 6 },
            { itemId: 'stone_rune', chance: "2/128", minQuantity: 3, maxQuantity: 3 },
            { itemId: 'ember_rune', chance: "2/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'bronze_arrow', chance: "2/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'anima_rune', chance: "1/128" },
            { itemId: 'flux_rune', chance: "1/128" },
            { itemId: 'verdant_rune', chance: "1/128" },
            { itemId: 'steel_arrow', chance: "1/128", minQuantity: 5, maxQuantity: 5 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 4, respawnTime: 75000, aggressive: false, attackStyle: 'slash', alwaysDrops: true
    },
    {
        id: 'goblin', name: 'Goblin', level: 2, maxHp: 8, attack: 1, strength: 2, defence: 1,
        stabDefence: 1, slashDefence: 2, crushDefence: 0, rangedDefence: 0, magicDefence: 0,
        iconUrl: 'goblin-head',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'goblin_hide', chance: "1/5" },
            { itemId: 'gust_rune', chance: "3/20", minQuantity: 1, maxQuantity: 5 },
            { itemId: 'stone_rune', chance: "3/20", minQuantity: 1, maxQuantity: 5 },
            { itemId: 'ember_rune', chance: "3/25", minQuantity: 1, maxQuantity: 4 },
            { itemId: 'binding_rune', chance: "3/25", minQuantity: 1, maxQuantity: 4 },
            { tableId: 'herb_table', chance: "1/10" },
            { itemId: 'grimy_coin_pouch', chance: "1/20" },
            { itemId: 'flux_rune', chance: "1/20", minQuantity: 1, maxQuantity: 2 },
            { itemId: 'ember_talisman', chance: "1/32" },
        ],
        tertiaryDrops: [
            { itemId: 'goblin_champion_scroll', chance: 0.0002, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 4, respawnTime: 12000, aggressive: false, attackStyle: 'slash', alwaysDrops: true,
    },
    {
        id: 'goblin_brute', name: 'Goblin Brute', level: 24, maxHp: 40, attack: 18, strength: 25, defence: 20,
        stabDefence: 15, slashDefence: 18, crushDefence: 0, rangedDefence: 10, magicDefence: 5,
        iconUrl: 'orc-head',
        guaranteedDrops: [
            { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'aqua_rune', chance: "3/20", minQuantity: 5, maxQuantity: 12 },
            { itemId: 'stone_rune', chance: "3/20", minQuantity: 5, maxQuantity: 12 },
            { itemId: 'ember_rune', chance: "3/20", minQuantity: 5, maxQuantity: 12 },
            { itemId: 'binding_rune', chance: "3/20", minQuantity: 5, maxQuantity: 12 },
            { itemId: 'goblin_hide', chance: "1/10", minQuantity: 1, maxQuantity: 2 },
            { itemId: 'grimy_coin_pouch', chance: "1/10", minQuantity: 1, maxQuantity: 2 },
            { tableId: 'herb_table', chance: "1/10" },
            { itemId: 'flux_rune', chance: "1/25", minQuantity: 4, maxQuantity: 10 },
            { itemId: 'steel_platebody', chance: "1/100" },
            { itemId: 'steel_full_helm', chance: "1/100" },
            { itemId: 'steel_platelegs', chance: "1/100" },
            { itemId: 'mithril_battleaxe', chance: "1/200" },
            { itemId: 'mithril_full_helm', chance: "1/200" },
            { itemId: 'mithril_platelegs', chance: "1/200" },
            { itemId: 'ember_talisman', chance: "1/32" },
            { itemId: 'nexus_rune', chance: "1/400", minQuantity: 1, maxQuantity: 5 },
        ],
        tertiaryDrops: [
            { itemId: 'goblin_champion_scroll', chance: 0.0002, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 5, respawnTime: 120000, aggressive: true, alwaysAggressive: true, attackStyle: 'crush', alwaysDrops: true,
        specialAttacks: [
            { name: 'Crushing Blow', chance: 0.5, effect: 'damage_multiplier', value: 1.5 },
        ],
    },
    {
        id: 'goblin_scout', name: 'Goblin Scout', level: 7, maxHp: 18, attack: 5, strength: 7, defence: 5,
        stabDefence: 4, slashDefence: 5, crushDefence: 0, rangedDefence: 2, magicDefence: 0,
        iconUrl: 'goblin',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'goblin_hide', chance: "1/5" },
            { itemId: 'gust_rune', chance: "3/20", minQuantity: 2, maxQuantity: 8 },
            { itemId: 'stone_rune', chance: "3/20", minQuantity: 2, maxQuantity: 8 },
            { tableId: 'herb_table', chance: "1/10" },
            { itemId: 'ember_rune', chance: "1/10", minQuantity: 2, maxQuantity: 6 },
            { itemId: 'binding_rune', chance: "1/10", minQuantity: 2, maxQuantity: 6 },
            { itemId: 'oak_shortbow', chance: "1/25" },
            { itemId: 'oak_longbow', chance: "1/25" },
            { itemId: 'feywood_shortbow', chance: "1/50" },
            { itemId: 'feywood_longbow', chance: "1/50" },
            { itemId: 'grimy_coin_pouch', chance: "7/100" },
            { itemId: 'flux_rune', chance: "1/20", minQuantity: 1, maxQuantity: 3 },
            { itemId: 'steel_arrow', chance: "1/20", minQuantity: 1, maxQuantity: 35 },
            { itemId: 'mithril_arrow', chance: "1/40", minQuantity: 1, maxQuantity: 25 },
            { itemId: 'adamantite_arrow', chance: "1/60", minQuantity: 1, maxQuantity: 15 },
            { itemId: 'runic_arrow', chance: "1/100", minQuantity: 1, maxQuantity: 10 },
            { itemId: 'goblin_mail', chance: "1/50" },
            { itemId: 'ember_talisman', chance: "1/32" },
        ],
        tertiaryDrops: [
            { itemId: 'goblin_champion_scroll', chance: 0.0002, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 4, respawnTime: 30000, aggressive: true, alwaysAggressive: true, attackStyle: 'stab', alwaysDrops: true,
    },
    {
        id: 'goblin_thrower', name: 'Goblin Thrower', level: 14, maxHp: 25, attack: 1, ranged: 12, strength: 7, defence: 10,
        stabDefence: 6, slashDefence: 8, crushDefence: 4, rangedDefence: 2, magicDefence: 0,
        iconUrl: 'goblin-head',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'gust_rune', chance: "3/10", minQuantity: 3, maxQuantity: 10 },
            { itemId: 'stone_rune', chance: "3/10", minQuantity: 3, maxQuantity: 10 },
            { itemId: 'goblin_hide', chance: "1/4" },
            { itemId: 'ember_rune', chance: "1/4", minQuantity: 3, maxQuantity: 8 },
            { itemId: 'beer', chance: "1/4" },
            { itemId: 'wolf_pelt_vambraces', chance: "1/25" },
            { itemId: 'wolf_pelt_chaps', chance: "1/25" },
            { itemId: 'wolf_pelt_cloak', chance: "1/25" },
            { itemId: 'wolf_pelt_cowl', chance: "1/25" },
            { itemId: 'wolf_pelt_body', chance: "1/25" },
            { itemId: 'binding_rune', chance: "1/4", minQuantity: 3, maxQuantity: 8 },
            { itemId: 'flux_rune', chance: "3/20", minQuantity: 2, maxQuantity: 5 },
            { tableId: 'herb_table', chance: "3/25" },
            { itemId: 'grimy_coin_pouch', chance: "2/25" },
            { itemId: 'ember_talisman', chance: "1/32" },
        ],
        tertiaryDrops: [
            { itemId: 'goblin_champion_scroll', chance: 0.0002, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 3, respawnTime: 30000, aggressive: true, alwaysAggressive: true, attackStyle: 'ranged', alwaysDrops: true,
    },
    {
        id: 'grumlok_goblin_king', name: 'Grumlok, the Goblin King', level: 82, maxHp: 120, attack: 32, strength: 69, defence: 40,
        stabDefence: 120, slashDefence: 126, crushDefence: -36, rangedDefence: 166, magicDefence: -20,
        iconUrl: 'overlord-helm',
        guaranteedDrops: [
            { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'flux_rune', minQuantity: 20, maxQuantity: 40 },
        ],
        mainDrops: [
            { itemId: 'clean_coin_pouch', chance: "1/4", minQuantity: 5, maxQuantity: 10 },
            { itemId: 'treasure_chest', chance: "1/12" },
            { itemId: 'verdant_rune', chance: "1/5", minQuantity: 15, maxQuantity: 30 },
            { tableId: 'herb_table', chance: "3/20" },
            { itemId: 'cooked_tuna', chance: "1/10", minQuantity: 10, maxQuantity: 20, noted: true },
            { itemId: 'steel_greatsword', chance: "1/20" },
            { itemId: 'goblin_dungeon_map', chance: "1/16" },
            { itemId: 'mithril_platebody', chance: "1/40" },
            { itemId: 'mithril_platelegs', chance: "1/40" },
            { itemId: 'mithril_full_helm', chance: "1/40" },
            { itemId: 'mithril_kiteshield', chance: "1/40" },
            { itemId: 'mithril_longsword', chance: "1/40" },
            { itemId: 'mithril_mace', chance: "1/40" },
            { itemId: 'yew_logs', chance: "1/10", minQuantity: 5, maxQuantity: 10 },
            { itemId: 'hex_rune', chance: "1/10", minQuantity: 8, maxQuantity: 15 },
            { itemId: 'adamantite_chainbody', chance: "1/100" },
            { itemId: 'adamantite_platelegs', chance: "1/100" },
            { itemId: 'adamantite_med_helm', chance: "1/100" },
            { itemId: 'adamantite_square_shield', chance: "1/100" },
            { itemId: 'adamantite_axe', chance: "1/100" },
            { itemId: 'adamantite_mace', chance: "1/100" },
            { itemId: 'nexus_rune', chance: "3/40", minQuantity: 10, maxQuantity: 20 },
            { itemId: 'passage_rune', chance: "1/20", minQuantity: 5, maxQuantity: 12 },
            { itemId: 'anima_rune', chance: "1/40", minQuantity: 2, maxQuantity: 8 },
        ],
        tertiaryDrops: [
            { itemId: 'flux_talisman', chance: 0.01 },
            { itemId: 'goblin_champion_scroll', chance: 0.001, minQuantity: 1, maxQuantity: 1 },
            { itemId: 'strange_key_tooth', chance: 0.01, minQuantity: 1, maxQuantity: 1 },
            { itemId: 'strange_key_loop', chance: 0.01, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 4, respawnTime: 240000, aggressive: true, alwaysAggressive: true, attackStyle: 'crush', alwaysDrops: true,
        specialAttacks: [
            { name: 'Royal Smash', chance: 0.3, effect: 'damage_multiplier', value: 2 },
        ],
    },
    {
        id: 'guard', name: 'Guard', level: 25, maxHp: 40, attack: 20, strength: 25, defence: 25,
        stabDefence: 30, slashDefence: 28, crushDefence: 25, rangedDefence: 28, magicDefence: 5,
        iconUrl: 'guard',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'coins', chance: "1/1", minQuantity: 20, maxQuantity: 50 },
            { itemId: 'bread', chance: "1/10", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'iron_arrow', chance: "1/8", minQuantity: 5, maxQuantity: 15 },
            { itemId: 'iron_sword', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'iron_bolts', chance: "1/12.8", minQuantity: 2, maxQuantity: 12 },
            { itemId: 'steel_arrow', chance: "1/32", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bronze_arrow', chance: "1/42.67", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'gust_rune', chance: "1/64", minQuantity: 6, maxQuantity: 6 },
            { itemId: 'stone_rune', chance: "1/64", minQuantity: 3, maxQuantity: 3 },
            { itemId: 'ember_rune', chance: "1/64", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'bronze_arrow', chance: "1/64", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'anima_rune', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'flux_rune', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'verdant_rune', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'steel_arrow', chance: "1/128", minQuantity: 5, maxQuantity: 5 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 4, respawnTime: 60000, aggressive: false, attackStyle: 'slash', alwaysDrops: true
    },
    {
        id: 'highwayman', name: 'Highwayman', level: 21, maxHp: 35, attack: 16, strength: 20, defence: 18,
        stabDefence: 18, slashDefence: 20, crushDefence: 16, rangedDefence: 15, magicDefence: 0,
        iconUrl: 'cowled',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'stone_rune', chance: "1/4", minQuantity: 5, maxQuantity: 12 },
            { itemId: 'gust_rune', chance: "9/40", minQuantity: 5, maxQuantity: 12 },
            { tableId: 'herb_table', chance: "1/5", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'ember_rune', chance: "1/5", minQuantity: 3, maxQuantity: 10 },
            { itemId: 'grimy_coin_pouch', chance: "3/25", minQuantity: 1, maxQuantity: 2 },
            { itemId: 'blue_cape', chance: "1/10", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'red_cape', chance: "1/10", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'lost_heirloom', chance: "1/200", minQuantity: 1, maxQuantity: 1, questReq: { questId: 'lost_heirloom', status: 'not_started' } },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 3, respawnTime: 60000, aggressive: true, attackStyle: 'slash',
    },
    {
        id: 'knight', name: 'Knight', level: 60, maxHp: 80, attack: 55, strength: 60, defence: 60,
        stabDefence: 80, slashDefence: 75, crushDefence: 70, rangedDefence: 75, magicDefence: 20,
        iconUrl: 'knight-helmet',
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'coins', chance: "1/1", minQuantity: 100, maxQuantity: 250 },
            { itemId: 'steel_platelegs', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'mithril_sword', chance: "1/256", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid, MonsterType.Armored], attackSpeed: 4, respawnTime: 90000, aggressive: false, attackStyle: 'slash', alwaysDrops: true
    },
    {
        id: 'man', name: 'Man', level: 2, maxHp: 7, attack: 1, strength: 1, defence: 1,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0,
        iconUrl: 'person',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'gust_rune', chance: "3/10", minQuantity: 1, maxQuantity: 6 },
            { itemId: 'aqua_rune', chance: "1/5", minQuantity: 1, maxQuantity: 3 },
            { itemId: 'stone_rune', chance: "1/5", minQuantity: 1, maxQuantity: 3 },
            { itemId: 'binding_rune', chance: "3/20", minQuantity: 1, maxQuantity: 2 },
            { tableId: 'herb_table', chance: "1/10", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bronze_square_shield', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'copper_ore', chance: "1/50", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'tin_ore', chance: "1/50", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bucket', chance: "3/200", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'knife', chance: "1/100", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'stone_talisman', chance: "1/32", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 60000, aggressive: false, attackStyle: 'crush', alwaysDrops: true,
    },
    {
        id: 'siren', name: 'Siren', level: 44, maxHp: 90, attack: 1, ranged: 55, strength: 20, defence: 40,
        stabDefence: 30, slashDefence: 30, crushDefence: 30, rangedDefence: 35, magicDefence: 35,
        iconUrl: 'siren',
        guaranteedDrops: [
            { itemId: 'sirens_hair', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'aqua_rune', minQuantity: 30, maxQuantity: 50 },
        ],
        mainDrops: [
            { itemId: 'eldritch_pearl', chance: "3/100", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'astral_rune', chance: "1/5", minQuantity: 5, maxQuantity: 12 },
            { itemId: 'anima_rune', chance: "3/25", minQuantity: 3, maxQuantity: 8 },
            { tableId: 'affinity_robes_table', chance: "1/128", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'astral_talisman', chance: "16/625", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 3, respawnTime: 240000, aggressive: true, alwaysAggressive: true, attackStyle: 'ranged',
        specialAttacks: [{ name: 'Deafening Shriek', chance: 0.2, effect: 'damage_multiplier', value: 1.5 }],
        elementalWeakness: 'earth',
    },
    {
        id: 'training_dummy', name: 'Training Dummy', level: 1, maxHp: 1000, attack: 0, customMaxHit: 0, strength: 0, defence: 1,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0,
        iconUrl: 'wooden-sign',
        types: [MonsterType.Humanoid], attackSpeed: 1000, respawnTime: 1000, aggressive: false, attackStyle: 'crush',
    },
    {
        id: 'warrior', name: 'Warrior', level: 18, maxHp: 22, attack: 8, customMaxHit: 3, strength: 15, defence: 15,
        stabDefence: 12, slashDefence: 10, crushDefence: 15, rangedDefence: 12, magicDefence: -1,
        iconUrl: 'swordman',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'bronze_full_helm', chance: '1/64', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'iron_dagger', chance: '1/128', minQuantity: 1, maxQuantity: 1 },
            { tableId: 'herb_table', chance: '23/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bronze_arrow', chance: '1/42', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'stone_rune', chance: '1/64', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'ember_rune', chance: '1/64', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bronze_square_shield', chance: '1/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'flux_rune', chance: '1/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'binding_rune', chance: '1/64', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'fishing_bait', chance: '1/25', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'stone_talisman', chance: '1/64', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'copper_ore', chance: '1/64', minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 20000, aggressive: false, attackStyle: 'slash',
    },
    {
        id: 'wizard', name: 'Wizard', level: 13, maxHp: 30, attack: 1, magic: 15, strength: 5, defence: 10,
        stabDefence: 5, slashDefence: 5, crushDefence: 5, rangedDefence: 8, magicDefence: 12,
        iconUrl: 'wizard-face',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'wizard_hat', chance: "1/20", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'wizard_robe_top', chance: "1/25", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'wizard_robe_skirt', chance: "1/25", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'wizard_boots', chance: "1/25", minQuantity: 1, maxQuantity: 1 },
            { tableId: 'herb_table', chance: "7/100", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'gust_rune', chance: "1/4", minQuantity: 10, maxQuantity: 25 },
            { itemId: 'aqua_rune', chance: "1/5", minQuantity: 8, maxQuantity: 20 },
            { itemId: 'stone_rune', chance: "1/5", minQuantity: 8, maxQuantity: 20 },
            { itemId: 'binding_rune', chance: "3/20", minQuantity: 5, maxQuantity: 15 },
            { itemId: 'flux_rune', chance: "1/16", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'verdant_rune', chance: "1/16", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'gust_rune', chance: "1/42", minQuantity: 5, maxQuantity: 5 },
            { itemId: 'hex_rune', chance: "1/42", minQuantity: 5, maxQuantity: 5 },
            { itemId: 'stone_rune', chance: "1/42", minQuantity: 5, maxQuantity: 5 },
            { itemId: 'ember_rune', chance: "1/42", minQuantity: 5, maxQuantity: 5 },
            { itemId: 'binding_rune', chance: "1/42", minQuantity: 5, maxQuantity: 5 },
            { itemId: 'aqua_rune', chance: "1/42", minQuantity: 5, maxQuantity: 5 },
            { itemId: 'gust_rune', chance: "1/64", minQuantity: 12, maxQuantity: 12 },
            { itemId: 'hex_rune', chance: "1/64", minQuantity: 12, maxQuantity: 12 },
            { itemId: 'stone_rune', chance: "1/64", minQuantity: 12, maxQuantity: 12 },
            { itemId: 'ember_rune', chance: "1/64", minQuantity: 12, maxQuantity: 12 },
            { itemId: 'binding_rune', chance: "1/64", minQuantity: 12, maxQuantity: 12 },
            { itemId: 'aqua_rune', chance: "1/64", minQuantity: 12, maxQuantity: 12 },
            { itemId: 'anima_rune', chance: "1/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'passage_rune', chance: "1/128", minQuantity: 2, maxQuantity: 2 },
            { itemId: 'binding_talisman', chance: "1/32", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'aqua_talisman', chance: "1/42", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 60000, aggressive: false, attackStyle: 'magic',
    },
    {
        id: 'woman', name: 'Woman', level: 2, maxHp: 7, attack: 1, strength: 1, defence: 1,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0,
        iconUrl: 'woman-elf-face',
        guaranteedDrops: [
            { itemId: 'bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'gust_rune', chance: "3/10", minQuantity: 7, maxQuantity: 7 },
            { itemId: 'aqua_rune', chance: "1/5", minQuantity: 3, maxQuantity: 3 },
            { itemId: 'stone_rune', chance: "1/5", minQuantity: 3, maxQuantity: 3 },
            { itemId: 'binding_rune', chance: "3/20", minQuantity: 2, maxQuantity: 2 },
            { tableId: 'herb_table', chance: "1/10", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bronze_square_shield', chance: '1/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'copper_ore', chance: "1/50", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'tin_ore', chance: "1/50", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'bucket', chance: "3/200", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'knife', chance: "1/100", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'stone_talisman', chance: "1/32", minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 60000, aggressive: false, attackStyle: 'crush', alwaysDrops: true,
    },
    {
        id: 'yeoman', name: 'Yeoman', level: 30, maxHp: 26, attack: 14, strength: 20, defence: 9,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0,
        iconUrl: 'yeoman-archer',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'seeds', chance: '1/2', minQuantity: 5, maxQuantity: 25 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 4, respawnTime: 60000, aggressive: false, attackStyle: 'slash'
    },
    {
        id: 'young_hill_giant', name: 'Young Hill Giant', level: 22, maxHp: 45, attack: 20, strength: 25, defence: 20,
        stabDefence: 18, slashDefence: 18, crushDefence: 22, rangedDefence: 15, magicDefence: -5,
        iconUrl: 'giant',
        guaranteedDrops: [
            { itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 },
        ],
        mainDrops: [
            { itemId: 'titan_fat', chance: '1/50', minQuantity: 1, maxQuantity: 3 },
            { itemId: 'iron_med_helm', chance: '5/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'iron_full_helm', chance: '5/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'iron_dagger', chance: '4/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'iron_kiteshield', chance: '3/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'steel_scimitar', chance: '2/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'steel_longsword', chance: '2/128', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'iron_arrow', chance: '6/128', minQuantity: 3, maxQuantity: 3 },
            { itemId: 'ember_rune', chance: '3/128', minQuantity: 15, maxQuantity: 15 },
            { itemId: 'aqua_rune', chance: '3/128', minQuantity: 7, maxQuantity: 7 },
            { itemId: 'passage_rune', chance: '3/128', minQuantity: 2, maxQuantity: 2 },
            { itemId: 'steel_arrow', chance: '2/128', minQuantity: 10, maxQuantity: 10 },
            { itemId: 'binding_rune', chance: '2/128', minQuantity: 3, maxQuantity: 3 },
            { itemId: 'astral_rune', chance: '2/128', minQuantity: 2, maxQuantity: 2 },
            { itemId: 'verdant_rune', chance: '2/128', minQuantity: 6, maxQuantity: 6 },
            { itemId: 'flux_rune', chance: '1/128', minQuantity: 2, maxQuantity: 2 },
            { itemId: 'nexus_rune', chance: '1/128', minQuantity: 2, maxQuantity: 2 },
            { itemId: 'boar_tusk', chance: '1/11', minQuantity: 1, maxQuantity: 1 },
        ],
        tertiaryDrops: [
            { itemId: 'gust_talisman', chance: 0.03125, minQuantity: 1, maxQuantity: 1 },
        ],
        types: [MonsterType.Humanoid], attackSpeed: 6, respawnTime: 60000, aggressive: true, attackStyle: 'crush',
    },
];
