import { Monster, MonsterType, MonsterId } from '@/types';

export const respiteMonsters: Monster[] = [
    // --- The Thornveil (Jungle) ---
    {
        id: 'canopy_stalker',
        source: 'respite',
        name: 'Canopy Stalker',
        level: 38,
        maxHp: 50,
        attack: 32, strength: 35, defence: 30,
        stabDefence: 25, slashDefence: 35, crushDefence: 30, rangedDefence: 40, magicDefence: 20,
        iconUrl: 'spider-alt',
        types: [MonsterType.Beast],
        attackSpeed: 4, respawnTime: 25000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'verdant_rune', chance: '1/3', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'spider_silk', chance: '1/5', minQuantity: 1, maxQuantity: 3 },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'cooked_tuna', chance: '1/12', minQuantity: 1, maxQuantity: 2 },
            { itemId: 'mithril_arrow', chance: '1/40', minQuantity: 25, maxQuantity: 50 },
            { itemId: 'mithril_dagger', chance: '1/64' }
        ],
    },
    {
        id: 'thorn_hulk',
        source: 'respite',
        name: 'Thorn Hulk',
        level: 52,
        maxHp: 75,
        attack: 45, strength: 50, defence: 55,
        stabDefence: 50, slashDefence: 60, crushDefence: 40, rangedDefence: 55, magicDefence: 30,
        iconUrl: 'beast-eye',
        types: [MonsterType.Beast],
        attackSpeed: 5, respawnTime: 35000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'verdant_rune', chance: '1/4', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'yew_logs', chance: '1/6', minQuantity: 5, maxQuantity: 15, noted: true },
            { tableId: 'herb_table', chance: '1/8' },
            { itemId: 'adamantite_ore', chance: '1/25', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'adamantite_axe', chance: '1/64' },
            { itemId: 'runic_axe', chance: '1/128' }
        ],
    },

    // --- The Bonemarsh (Swamp) ---
    {
        id: 'risen_shambler',
        source: 'respite',
        name: 'Risen Shambler',
        level: 28,
        maxHp: 40,
        attack: 25, strength: 28, defence: 20,
        stabDefence: 15, slashDefence: 20, crushDefence: 25, rangedDefence: 30, magicDefence: 10,
        iconUrl: 'zombie-face',
        types: [MonsterType.Undead],
        attackSpeed: 4, respawnTime: 20000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'nexus_rune', chance: '1/5', minQuantity: 5, maxQuantity: 15 },
            { itemId: 'fishing_bait', chance: '1/8', minQuantity: 10, maxQuantity: 30 },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'cooked_pike', chance: '1/15', minQuantity: 1, maxQuantity: 2 },
            { itemId: 'mithril_platelegs', chance: '1/50' },
            { itemId: 'mithril_mace', chance: '1/64' }
        ],
    },
    {
        id: 'marsh_lurker',
        source: 'respite',
        name: 'Marsh Lurker',
        level: 45,
        maxHp: 65,
        attack: 40, magic: 40, strength: 40, defence: 45,
        stabDefence: 45, slashDefence: 45, crushDefence: 45, rangedDefence: 40, magicDefence: 55,
        iconUrl: 'ghost',
        types: [MonsterType.Undead, MonsterType.Elemental],
        attackSpeed: 4, respawnTime: 30000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'astral_rune', chance: '1/6', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'vial_of_water', chance: '1/8', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'nexus_rune', chance: '1/10', minQuantity: 10, maxQuantity: 25 },
            { tableId: 'herb_table', chance: '1/12' },
            { itemId: 'charged_staff_of_stone', chance: '1/40' },
            { tableId: 'affinity_robes', chance: '1/128' }
        ],
    },

    // --- The Scorched Hollow (Volcanic) ---
    {
        source: 'respite',
        id: 'cinder_wisp', name: 'Cinder Wisp',
        level: 42, maxHp: 45, attack: 0, strength: 0, magic: 45, defence: 35,
        stabDefence: 30, slashDefence: 30, crushDefence: 30, rangedDefence: 35, magicDefence: 60,
        iconUrl: 'ember-shot',
        types: [MonsterType.Elemental],
        attackSpeed: 3, respawnTime: 15000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'ember_rune', chance: '1/3', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'coal', chance: '1/6', minQuantity: 3, maxQuantity: 8, noted: true },
            { itemId: 'flux_rune', chance: '1/15', minQuantity: 5, maxQuantity: 15 },
            { itemId: 'gold_ore', chance: '1/20', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'uncut_ruby', chance: '1/40', minQuantity: 1, maxQuantity: 2 },
            { itemId: 'charged_staff_of_ember', chance: '1/80' }
        ],
    },
    {
        id: 'magma_slug',
        source: 'respite',
        name: 'Magma Slug',
        level: 58,
        maxHp: 85,
        attack: 52, strength: 58, defence: 65,
        stabDefence: 60, slashDefence: 60, crushDefence: 60, rangedDefence: 70, magicDefence: 50,
        iconUrl: 'slug',
        types: [MonsterType.Beast, MonsterType.Elemental],
        attackSpeed: 5, respawnTime: 40000, alwaysDrops: true, aggressive: false, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'coal', chance: '1/4', minQuantity: 10, maxQuantity: 25, noted: true },
            { itemId: 'ember_rune', chance: '1/5', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'adamantite_ore', chance: '1/10', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'cooked_swordfish', chance: '1/15', minQuantity: 1, maxQuantity: 3 },
            { itemId: 'adamantite_warhammer', chance: '1/80' }
        ],
    },

    // --- The Shattered Coast ---
    {
        id: 'coast_prowler',
        source: 'respite',
        name: 'Coast Prowler',
        level: 35,
        maxHp: 48,
        attack: 30, strength: 34, defence: 28,
        stabDefence: 25, slashDefence: 30, crushDefence: 35, rangedDefence: 30, magicDefence: 20,
        iconUrl: 'wave-crest',
        types: [MonsterType.Beast],
        attackSpeed: 4, respawnTime: 22000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/4', minQuantity: 12, maxQuantity: 24 },
            { itemId: 'raw_tuna', chance: '1/6', minQuantity: 2, maxQuantity: 4, noted: true },
            { itemId: 'seaweed', chance: '1/10', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'raw_lobster', chance: '1/12', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'mithril_scimitar', chance: '1/64' }
        ],
    },

    // --- Frostspine Ridge ---
    {
        id: 'frost_crawler',
        source: 'respite',
        name: 'Frost Crawler',
        level: 65,
        maxHp: 95,
        attack: 60, strength: 65, defence: 70,
        stabDefence: 70, slashDefence: 70, crushDefence: 50, rangedDefence: 75, magicDefence: 40,
        iconUrl: 'spider-alt',
        types: [MonsterType.Beast, MonsterType.Elemental],
        attackSpeed: 4, respawnTime: 45000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        fireWeakness: 1.0,
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/4', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'mithril_ore', chance: '1/8', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'mithril_bar', chance: '1/12', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'raw_shark', chance: '1/20', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'uncut_sapphire', chance: '1/40', minQuantity: 2, maxQuantity: 4 },
            { itemId: 'runic_dagger', chance: '1/64' },
            { itemId: 'adamantite_square_shield', chance: '1/64' },
            { itemId: 'adamantite_med_helm', chance: '1/64' }
        ],
    },

    // --- Abyssal Rift Monsters ---
    {
        id: 'void_walker',
        source: 'respite',
        name: 'Void Walker',
        level: 75,
        maxHp: 110,
        attack: 70, strength: 75, defence: 65,
        stabDefence: 60, slashDefence: 65, crushDefence: 70, rangedDefence: 75, magicDefence: 85,
        iconUrl: 'ghost',
        types: [MonsterType.Demon],
        attackSpeed: 4, respawnTime: 40000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'nexus_rune', chance: '1/5', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'adamantite_arrow', chance: '1/8', minQuantity: 20, maxQuantity: 50 },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'adamantite_ore', chance: '1/20', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'runic_bar', chance: '1/40', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'adamantite_longsword', chance: '1/64' }
        ],
    },
    {
        id: 'abyssal_horror',
        source: 'respite',
        name: 'Abyssal Horror',
        level: 88,
        maxHp: 140,
        attack: 85, magic: 80, strength: 80, defence: 90,
        stabDefence: 90, slashDefence: 90, crushDefence: 85, rangedDefence: 95, magicDefence: 100,
        iconUrl: 'terror',
        types: [MonsterType.Demon],
        attackSpeed: 4, respawnTime: 55000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'nexus_rune', chance: '1/4', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'cooked_shark', chance: '1/10', minQuantity: 1, maxQuantity: 3 },
            { itemId: 'anima_rune', chance: '1/12', minQuantity: 5, maxQuantity: 15 },
            { itemId: 'runic_bar', chance: '1/25', minQuantity: 2, maxQuantity: 4, noted: true },
            { itemId: 'runic_battleaxe', chance: '1/80' }
        ],
    },
    {
        id: 'void_reaper',
        source: 'respite',
        name: 'Void Reaper',
        level: 105,
        maxHp: 180,
        attack: 95, strength: 105, defence: 95,
        stabDefence: 95, slashDefence: 100, crushDefence: 90, rangedDefence: 105, magicDefence: 95,
        iconUrl: 'reaper-scythe',
        types: [MonsterType.Demon],
        attackSpeed: 3, respawnTime: 70000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'anima_rune', chance: '1/6', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'passage_rune', chance: '1/8', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'astral_rune', chance: '1/8', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'adamantite_bar', chance: '1/15', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'yew_logs', chance: '1/20', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'adamantite_platebody', chance: '1/64' },
            { itemId: 'runic_longsword', chance: '1/128' }
        ],
    },
    {
        id: 'rift_guardian',
        source: 'respite',
        name: 'Rift Guardian',
        level: 125,
        maxHp: 250,
        attack: 110, magic: 105, strength: 115, defence: 120,
        stabDefence: 120, slashDefence: 120, crushDefence: 110, rangedDefence: 125, magicDefence: 115,
        iconUrl: 'guardian',
        types: [MonsterType.Demon, MonsterType.Elemental],
        attackSpeed: 4, respawnTime: 120000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'astral_rune', chance: '1/4', minQuantity: 50, maxQuantity: 100 },
            { itemId: 'runic_bar', chance: '1/8', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'runic_bar', chance: '1/12', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'cooked_shark', chance: '1/15', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'runic_greatsword', chance: '1/64' },
            { itemId: 'runic_kiteshield', chance: '1/64' }
        ],
    },

    // --- Dungeon Specifics ---
    {
        source: 'respite',
        id: 'steam_sprite', name: 'Steam Sprite',
        level: 32, maxHp: 38, attack: 0, strength: 0, magic: 35, defence: 25,
        stabDefence: 20, slashDefence: 20, crushDefence: 20, rangedDefence: 30, magicDefence: 45,
        iconUrl: 'cloud',
        types: [MonsterType.Elemental],
        attackSpeed: 3, respawnTime: 18000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        guaranteedDrops: [{ itemId: 'vial_of_water', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/3', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'ember_rune', chance: '1/4', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'vial_of_water', chance: '1/10', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'silver_ore', chance: '1/15', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'charged_staff_of_aqua', chance: '1/64' }
        ],
    },
    {
        id: 'obsidian_golem',
        source: 'respite',
        name: 'Obsidian Golem',
        level: 62,
        maxHp: 115,
        attack: 55, strength: 68, defence: 90,
        stabDefence: 85, slashDefence: 95, crushDefence: 45, rangedDefence: 90, magicDefence: 40,
        iconUrl: 'stone-guardian',
        types: [MonsterType.Elemental, MonsterType.Armored],
        attackSpeed: 6, respawnTime: 45000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'coal', chance: '1/5', minQuantity: 15, maxQuantity: 30, noted: true },
            { itemId: 'adamantite_ore', chance: '1/8', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'golem_core_shard', chance: '1/8', minQuantity: 5, maxQuantity: 15 },
            { itemId: 'adamantite_bar', chance: '1/12', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'runic_bar', chance: '1/25', minQuantity: 1, maxQuantity: 3, noted: true }
        ],
    },

    // --- Respite Roads ---
    {
        source: 'respite',
        id: 'respite_prowler', name: 'Respite Prowler', level: 52, maxHp: 65,
        attack: 46, strength: 50, defence: 42,
        stabDefence: 38, slashDefence: 48, crushDefence: 42, rangedDefence: 44, magicDefence: 25,
        iconUrl: 'wolf-head', types: [MonsterType.Beast],
        attackSpeed: 4, respawnTime: 22000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'wolf_pelt', chance: '1/4' },
            { itemId: 'verdant_rune', chance: '1/5', minQuantity: 8, maxQuantity: 20 },
            { itemId: 'iron_ore', chance: '1/10', minQuantity: 5, maxQuantity: 10, noted: true },
            { tableId: 'herb_table', chance: '1/12' },
            { itemId: 'cooked_tuna', chance: '1/15', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'mithril_arrow', chance: '1/20', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'mithril_dagger', chance: '1/64' },
            { itemId: 'uncut_ruby', chance: '1/128' },
        ],
    },
    {
        source: 'respite',
        id: 'driftwood_golem', name: 'Driftwood Golem', level: 57, maxHp: 78,
        attack: 50, strength: 54, defence: 60,
        stabDefence: 55, slashDefence: 60, crushDefence: 35, rangedDefence: 55, magicDefence: 30,
        iconUrl: 'wood-frame', types: [MonsterType.Elemental],
        attackSpeed: 5, respawnTime: 30000, alwaysDrops: true, aggressive: false, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'driftwood_logs', minQuantity: 2, maxQuantity: 5 }],
        mainDrops: [
            { itemId: 'coal', chance: '1/4', minQuantity: 5, maxQuantity: 15, noted: true },
            { itemId: 'stone_rune', chance: '1/6', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'mithril_ore', chance: '1/12', minQuantity: 2, maxQuantity: 5, noted: true },
            { tableId: 'herb_table', chance: '1/14' },
            { tableId: 'gem_table', chance: '1/80' },
            { itemId: 'mithril_mace', chance: '1/64' },
            { itemId: 'mithril_warhammer', chance: '1/128' },
            { itemId: 'adamantite_ore', chance: '1/80', minQuantity: 1, maxQuantity: 3, noted: true },
        ],
    },

    // --- The Bonemarsh (additional) ---
    {
        source: 'respite',
        id: 'bone_scavenger', name: 'Bone Scavenger', level: 55, maxHp: 68,
        attack: 48, strength: 52, defence: 44,
        stabDefence: 40, slashDefence: 50, crushDefence: 44, rangedDefence: 55, magicDefence: 30,
        iconUrl: 'vulture', types: [MonsterType.Undead, MonsterType.Beast],
        attackSpeed: 4, respawnTime: 25000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'nexus_rune', chance: '1/4', minQuantity: 8, maxQuantity: 20 },
            { itemId: 'feathers', chance: '1/5', minQuantity: 30, maxQuantity: 80 },
            { itemId: 'raw_eel', chance: '1/10', minQuantity: 1, maxQuantity: 3, noted: true },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'mithril_arrow', chance: '1/12', minQuantity: 25, maxQuantity: 50 },
            { itemId: 'mithril_kiteshield', chance: '1/64' },
            { itemId: 'uncut_ruby', chance: '1/128' },
            { tableId: 'gem_table', chance: '1/96' },
        ],
    },
    {
        source: 'respite',
        id: 'marshlight_wraith', name: 'Marshlight Wraith', level: 62, maxHp: 70,
        attack: 1, magic: 58, strength: 1, defence: 55,
        stabDefence: 50, slashDefence: 50, crushDefence: 50, rangedDefence: 55, magicDefence: 70,
        iconUrl: 'will-o-wisp', types: [MonsterType.Undead],
        attackSpeed: 4, respawnTime: 32000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'astral_rune', chance: '1/4', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'nexus_rune', chance: '1/6', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'coins', chance: '1/8', minQuantity: 1500, maxQuantity: 3000 },
            { itemId: 'vial_of_water', chance: '1/8', minQuantity: 5, maxQuantity: 10, noted: true },
            { tableId: 'herb_table', chance: '1/8', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'mithril_full_helm', chance: '1/64' },
            { itemId: 'prayer_potion', chance: '1/64' },
            { itemId: 'uncut_diamond', chance: '1/256' },
        ],
    },
    {
        source: 'respite',
        id: 'bog_shamble', name: 'Bog Shamble', level: 72, maxHp: 95,
        attack: 64, strength: 68, defence: 65,
        stabDefence: 60, slashDefence: 65, crushDefence: 70, rangedDefence: 60, magicDefence: 40,
        iconUrl: 'zombie-face', types: [MonsterType.Undead, MonsterType.Elemental],
        attackSpeed: 5, respawnTime: 40000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'nexus_rune', chance: '1/4', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'aqua_rune', chance: '1/5', minQuantity: 20, maxQuantity: 40 },
            { tableId: 'herb_table', chance: '1/8', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'adamantite_ore', chance: '1/20', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'cooked_lobster', chance: '1/15', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'adamantite_mace', chance: '1/64' },
            { tableId: 'gem_table', chance: '1/80' },
            { itemId: 'super_attack_potion', chance: '1/64' },
        ],
    },

    // --- The Thornveil (additional) ---
    {
        source: 'respite',
        id: 'razortusk_boar', name: 'Razortusk Boar', level: 54, maxHp: 67,
        attack: 47, strength: 51, defence: 43,
        stabDefence: 40, slashDefence: 50, crushDefence: 44, rangedDefence: 40, magicDefence: 20,
        iconUrl: 'boar-tusks', types: [MonsterType.Beast],
        attackSpeed: 3, respawnTime: 20000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'verdant_rune', chance: '1/4', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'yew_logs', chance: '1/8', minQuantity: 5, maxQuantity: 15, noted: true },
            { itemId: 'mithril_ore', chance: '1/16', minQuantity: 2, maxQuantity: 4, noted: true },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'cooked_tuna', chance: '1/12', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'mithril_battleaxe', chance: '1/64' },
            { itemId: 'uncut_ruby', chance: '1/128' },
            { itemId: 'adamantite_ore', chance: '1/48', minQuantity: 1, maxQuantity: 2, noted: true },
        ],
    },
    {
        source: 'respite',
        id: 'thornback_beetle', name: 'Thornback Beetle', level: 60, maxHp: 82,
        attack: 53, strength: 56, defence: 68,
        stabDefence: 65, slashDefence: 70, crushDefence: 30, rangedDefence: 65, magicDefence: 35,
        iconUrl: 'scarab', types: [MonsterType.Beast, MonsterType.Armored],
        attackSpeed: 6, respawnTime: 35000, alwaysDrops: true, aggressive: false, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'verdant_rune', chance: '1/5', minQuantity: 12, maxQuantity: 28 },
            { itemId: 'chisel', chance: '1/8', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'mithril_ore', chance: '1/10', minQuantity: 3, maxQuantity: 6, noted: true },
            { tableId: 'herb_table', chance: '1/12' },
            { tableId: 'gem_table', chance: '1/80' },
            { itemId: 'yew_logs', chance: '1/12', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'mithril_warhammer', chance: '1/64' },
            { itemId: 'adamantite_full_helm', chance: '1/128' },
        ],
    },
    {
        source: 'respite',
        id: 'jungle_serpent', name: 'Jungle Serpent', level: 68, maxHp: 75,
        attack: 60, strength: 65, defence: 55,
        stabDefence: 52, slashDefence: 55, crushDefence: 58, rangedDefence: 60, magicDefence: 40,
        iconUrl: 'snake', types: [MonsterType.Beast],
        attackSpeed: 4, respawnTime: 28000, alwaysDrops: true, aggressive: true, attackStyle: 'stab',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'verdant_rune', chance: '1/4', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'antipoison_potion', chance: '1/8', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'yew_logs', chance: '1/10', minQuantity: 10, maxQuantity: 20, noted: true },
            { tableId: 'herb_table', chance: '1/8' },
            { itemId: 'uncut_ruby', chance: '1/64' },
            { itemId: 'mithril_scimitar', chance: '1/64' },
            { tableId: 'gem_table', chance: '1/96' },
            { itemId: 'adamantite_longsword', chance: '1/256' },
        ],
        specialAttacks: [{ name: 'Poison Spit', chance: 0.4, effect: 'poison', damage: 5, poisonChance: 0.75 }],
    },

    // --- The Scorched Hollow (additional) ---
    {
        source: 'respite',
        id: 'cinder_imp', name: 'Cinder Imp', level: 53, maxHp: 58,
        attack: 0, magic: 50, strength: 0, defence: 40,
        stabDefence: 35, slashDefence: 35, crushDefence: 35, rangedDefence: 40, magicDefence: 60,
        iconUrl: 'imp', types: [MonsterType.Demon],
        attackSpeed: 3, respawnTime: 16000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'ember_rune', chance: '1/3', minQuantity: 12, maxQuantity: 28 },
            { itemId: 'flux_rune', chance: '1/10', minQuantity: 5, maxQuantity: 15 },
            { itemId: 'coal', chance: '1/6', minQuantity: 3, maxQuantity: 8, noted: true },
            { itemId: 'gold_ore', chance: '1/20', minQuantity: 1, maxQuantity: 3, noted: true },
            { tableId: 'herb_table', chance: '1/12' },
            { itemId: 'uncut_ruby', chance: '1/48' },
            { itemId: 'mithril_scimitar', chance: '1/80' },
            { itemId: 'charged_staff_of_ember', chance: '1/128' },
        ],
    },
    {
        source: 'respite',
        id: 'char_elemental', name: 'Char Elemental', level: 66, maxHp: 82,
        attack: 58, strength: 62, defence: 60,
        stabDefence: 55, slashDefence: 60, crushDefence: 65, rangedDefence: 55, magicDefence: 30,
        iconUrl: 'fire-ace', types: [MonsterType.Elemental],
        attackSpeed: 4, respawnTime: 35000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'ember_rune', chance: '1/3', minQuantity: 18, maxQuantity: 36 },
            { itemId: 'flux_rune', chance: '1/8', minQuantity: 8, maxQuantity: 20 },
            { itemId: 'coal', chance: '1/5', minQuantity: 8, maxQuantity: 20, noted: true },
            { itemId: 'gold_ore', chance: '1/16', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'adamantite_ore', chance: '1/25', minQuantity: 1, maxQuantity: 3, noted: true },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'mithril_platebody', chance: '1/96' },
            { itemId: 'adamantite_warhammer', chance: '1/192' },
        ],
    },

    {
        source: 'respite',
        id: 'magma_crawler', name: 'Magma Crawler', level: 75, maxHp: 98,
        attack: 66, strength: 72, defence: 68,
        stabDefence: 65, slashDefence: 70, crushDefence: 75, rangedDefence: 60, magicDefence: 35,
        iconUrl: 'slug', types: [MonsterType.Demon, MonsterType.Elemental],
        attackSpeed: 6, respawnTime: 45000, alwaysDrops: true, aggressive: false, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'ember_rune', chance: '1/3', minQuantity: 20, maxQuantity: 45 },
            { itemId: 'flux_rune', chance: '1/6', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'adamantite_ore', chance: '1/10', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'gold_ore', chance: '1/12', minQuantity: 3, maxQuantity: 8, noted: true },
            { itemId: 'cooked_swordfish', chance: '1/14', minQuantity: 1, maxQuantity: 3, noted: true },
            { tableId: 'gem_table', chance: '1/64' },
            { itemId: 'adamantite_warhammer', chance: '1/96' },
            { itemId: 'runic_bar', chance: '1/192', minQuantity: 1, maxQuantity: 2, noted: true },
        ],
    },
    {
        source: 'respite',
        id: 'ash_wraith', name: 'Ash Wraith', level: 80, maxHp: 90,
        attack: 1, magic: 74, strength: 1, defence: 70,
        stabDefence: 65, slashDefence: 65, crushDefence: 65, rangedDefence: 70, magicDefence: 85,
        iconUrl: 'ghost', types: [MonsterType.Demon, MonsterType.Undead],
        attackSpeed: 4, respawnTime: 48000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 2, maxQuantity: 4 }],
        mainDrops: [
            { itemId: 'nexus_rune', chance: '1/4', minQuantity: 15, maxQuantity: 35 },
            { itemId: 'ember_rune', chance: '1/5', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'coins', chance: '1/8', minQuantity: 4000, maxQuantity: 8000 },
            { tableId: 'herb_table', chance: '1/6', minQuantity: 2, maxQuantity: 4, noted: true },
            { itemId: 'adamantite_platelegs', chance: '1/96' },
            { itemId: 'super_defence_potion', chance: '1/48' },
            { tableId: 'gem_table', chance: '1/64' },
            { itemId: 'runic_dagger', chance: '1/256' },
        ],
    },

    // --- The Shattered Coast (additional) ---
    {
        source: 'respite',
        id: 'tide_hunter', name: 'Tide Hunter', level: 58, maxHp: 72,
        attack: 51, strength: 55, defence: 62,
        stabDefence: 58, slashDefence: 60, crushDefence: 30, rangedDefence: 58, magicDefence: 40,
        iconUrl: 'crab-claw', types: [MonsterType.Beast],
        attackSpeed: 5, respawnTime: 28000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/4', minQuantity: 12, maxQuantity: 28 },
            { itemId: 'raw_lobster', chance: '1/6', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'raw_tuna', chance: '1/8', minQuantity: 2, maxQuantity: 4, noted: true },
            { itemId: 'seaweed', chance: '1/6', minQuantity: 5, maxQuantity: 10, noted: true },
            { tableId: 'herb_table', chance: '1/12' },
            { itemId: 'mithril_mace', chance: '1/64' },
            { itemId: 'mithril_kiteshield', chance: '1/96' },
            { tableId: 'gem_table', chance: '1/128' },
        ],
    },
    {
        source: 'respite',
        id: 'reef_lurker', name: 'Reef Lurker', level: 65, maxHp: 78,
        attack: 57, strength: 62, defence: 58,
        stabDefence: 55, slashDefence: 60, crushDefence: 62, rangedDefence: 58, magicDefence: 35,
        iconUrl: 'wave-crest', types: [MonsterType.Beast],
        attackSpeed: 3, respawnTime: 30000, alwaysDrops: true, aggressive: true, attackStyle: 'stab',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/4', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'raw_shark', chance: '1/10', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'raw_lobster', chance: '1/8', minQuantity: 2, maxQuantity: 4, noted: true },
            { itemId: 'antipoison_potion', chance: '1/12', minQuantity: 1, maxQuantity: 2, noted: true },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'mithril_scimitar', chance: '1/64' },
            { tableId: 'gem_table', chance: '1/80' },
            { itemId: 'adamantite_kiteshield', chance: '1/192' },
        ],
    },
    {
        source: 'respite',
        id: 'storm_elemental', name: 'Storm Elemental', level: 74, maxHp: 85,
        attack: 1, magic: 68, strength: 1, defence: 65,
        stabDefence: 60, slashDefence: 60, crushDefence: 60, rangedDefence: 65, magicDefence: 75,
        iconUrl: 'lightning-trio', types: [MonsterType.Elemental],
        attackSpeed: 4, respawnTime: 38000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/3', minQuantity: 20, maxQuantity: 45 },
            { itemId: 'gust_rune', chance: '1/4', minQuantity: 15, maxQuantity: 35 },
            { itemId: 'flux_rune', chance: '1/8', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'nexus_rune', chance: '1/16', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'coins', chance: '1/8', minQuantity: 2500, maxQuantity: 5000 },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'prayer_potion', chance: '1/48' },
            { itemId: 'adamantite_kiteshield', chance: '1/128' },
            { tableId: 'gem_table', chance: '1/80' },
        ],
    },

    // --- Frostspine Ridge (additional) ---
    {
        source: 'respite',
        id: 'snowpeak_ram', name: 'Snowpeak Ram', level: 56, maxHp: 72,
        attack: 49, strength: 53, defence: 48,
        stabDefence: 44, slashDefence: 48, crushDefence: 55, rangedDefence: 44, magicDefence: 25,
        iconUrl: 'goat', types: [MonsterType.Beast],
        attackSpeed: 4, respawnTime: 25000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        fireWeakness: 1.0,
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/4', minQuantity: 10, maxQuantity: 25 },
            { itemId: 'mithril_ore', chance: '1/8', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'mithril_bar', chance: '1/16', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'raw_shark', chance: '1/20', minQuantity: 1, maxQuantity: 2, noted: true },
            { tableId: 'herb_table', chance: '1/12' },
            { itemId: 'cooked_swordfish', chance: '1/14', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'mithril_warhammer', chance: '1/64' },
            { itemId: 'uncut_ruby', chance: '1/96' },
        ],
    },
    {
        source: 'respite',
        id: 'frost_stalker', name: 'Frost Stalker', level: 63, maxHp: 74,
        attack: 56, strength: 60, defence: 52,
        stabDefence: 48, slashDefence: 58, crushDefence: 52, rangedDefence: 55, magicDefence: 30,
        iconUrl: 'wolf-howl', types: [MonsterType.Beast],
        attackSpeed: 3, respawnTime: 28000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        fireWeakness: 1.0,
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/4', minQuantity: 12, maxQuantity: 28 },
            { itemId: 'mithril_ore', chance: '1/8', minQuantity: 4, maxQuantity: 8, noted: true },
            { itemId: 'wolf_pelt', chance: '1/6', minQuantity: 1, maxQuantity: 2 },
            { itemId: 'raw_shark', chance: '1/15', minQuantity: 1, maxQuantity: 2, noted: true },
            { tableId: 'herb_table', chance: '1/10' },
            { itemId: 'mithril_scimitar', chance: '1/64' },
            { itemId: 'uncut_sapphire', chance: '1/48', minQuantity: 2, maxQuantity: 4 },
            { itemId: 'adamantite_sword', chance: '1/192' },
        ],
    },
    {
        source: 'respite',
        id: 'glacial_horror', name: 'Glacial Horror', level: 78, maxHp: 108,
        attack: 70, strength: 75, defence: 76,
        stabDefence: 72, slashDefence: 76, crushDefence: 80, rangedDefence: 68, magicDefence: 45,
        iconUrl: 'ice-golem', types: [MonsterType.Elemental, MonsterType.Undead],
        attackSpeed: 6, respawnTime: 55000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        fireWeakness: 1.0,
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/3', minQuantity: 25, maxQuantity: 50 },
            { itemId: 'mithril_bar', chance: '1/8', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'adamantite_ore', chance: '1/10', minQuantity: 4, maxQuantity: 8, noted: true },
            { tableId: 'herb_table', chance: '1/8', minQuantity: 2, maxQuantity: 4, noted: true },
            { itemId: 'prayer_potion', chance: '1/48' },
            { itemId: 'adamantite_platebody', chance: '1/128' },
            { itemId: 'uncut_diamond', chance: '1/128' },
            { tableId: 'gem_table', chance: '1/64' },
        ],
    },
    {
        source: 'respite',
        id: 'frostspine_drake', name: 'Frostspine Drake', level: 88, maxHp: 130,
        attack: 1, magic: 82, strength: 1, defence: 82,
        stabDefence: 78, slashDefence: 78, crushDefence: 78, rangedDefence: 82, magicDefence: 40,
        iconUrl: 'dragon-head', types: [MonsterType.Dragon],
        attackSpeed: 5, respawnTime: 90000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        fireWeakness: 1.0,
        guaranteedDrops: [{ itemId: 'dragon_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/4', minQuantity: 40, maxQuantity: 80 },
            { itemId: 'gust_rune', chance: '1/5', minQuantity: 30, maxQuantity: 60 },
            { itemId: 'wyvern_claw', chance: '1/8', minQuantity: 1, maxQuantity: 1 },
            { itemId: 'adamantite_bar', chance: '1/16', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'runic_bar', chance: '1/32', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'cooked_shark', chance: '1/8', minQuantity: 2, maxQuantity: 4, noted: true },
            { tableId: 'herb_table', chance: '1/8', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'uncut_diamond', chance: '1/96' },
            { tableId: 'gem_table', chance: '1/48' },
            { itemId: 'runic_kiteshield', chance: '1/256' },
        ],
    },
];
