import { Monster, MonsterType, SkillName } from '@/types';
export const slayer: Monster[] = [
    {
        id: 'grasping_limb',
        name: 'Grasping Limb',
        level: 8,
        // slayerLevel: 5,
        maxHp: 15,
        attack: 5, strength: 7, defence: 5,
        stabDefence: 5, slashDefence: 5, crushDefence: 8, rangedDefence: 5, magicDefence: 0,
        iconUrl: 'zombie-hand',
        types: [MonsterType.Undead],
        attackSpeed: 4, respawnTime: 15000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'tattered_cloth', chance: '1/4' },
            { tableId: 'herb_table', chance: '1/20' },
            { itemId: 'iron_ore', chance: '1/16', noted: true },
            { itemId: 'mithril_sword', chance: '1/128' },
            { itemId: 'gust_rune', chance: '1/10', minQuantity: 5, maxQuantity: 15 },
            { itemId: 'uncut_sapphire', chance: '1/256' },
            { itemId: 'fishing_bait', chance: '1/8', minQuantity: 10, maxQuantity: 20 },
            //{ itemId: 'bronze_boots', chance: '1/64' },
            { itemId: 'mithril_dagger', chance: '1/128' },
            // { itemId: 'severed_zombie_hand', chance: '1/1024' },
        ],
    },
    {
        id: 'stonehide_slug',
        name: 'Stonehide Slug',
        level: 15,
        // slayerLevel: 7,
        // requiredSlayerItem: 'bag_of_salt',
        maxHp: 25,
        attack: 10, strength: 12, defence: 20,
        stabDefence: 20, slashDefence: 20, crushDefence: 20, rangedDefence: 25, magicDefence: 25,
        iconUrl: 'slug',
        types: [MonsterType.Beast],
        attackSpeed: 5, respawnTime: 20000, alwaysDrops: true, aggressive: false, attackStyle: 'crush',
        mainDrops: [
            { itemId: 'iron_ore', chance: '1/8', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'uncut_sapphire', chance: '1/128' },
            { tableId: 'herb_table', chance: '1/16' },
            { itemId: 'mithril_axe', chance: '1/256' },
            { itemId: 'stone_rune', chance: '1/10', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'coal', chance: '1/20', minQuantity: 2, maxQuantity: 4, noted: true },
            { itemId: 'mithril_full_helm', chance: '1/128' },
            // { itemId: 'salt_crusted_hide', chance: '1/32' },
        ],
    },
    {
        id: 'gaze_fiend',
        name: 'Gaze Fiend',
        level: 25,
        // slayerLevel: 15,
        // requiredSlayerItem: 'reflective_shield',
        maxHp: 35,
        attack: 20, strength: 22, defence: 25,
        stabDefence: 25, slashDefence: 25, crushDefence: 28, rangedDefence: 20, magicDefence: 20,
        iconUrl: 'eye-shield',
        types: [MonsterType.Beast],
        attackSpeed: 4, respawnTime: 25000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        mainDrops: [
            { itemId: 'mithril_ore', chance: '1/16', noted: true },
            { tableId: 'herb_table', chance: '1/16' },
            { tableId: 'gem_table', chance: '1/128' },
            { itemId: 'mithril_chainbody', chance: '1/128' },
            // { itemId: 'petrifying_flail', chance: '1/512' },
            { itemId: 'binding_rune', chance: '1/10', minQuantity: 10, maxQuantity: 30 },
            { itemId: 'cooked_tuna', chance: '1/20', minQuantity: 1, maxQuantity: 1, noted: true },
            // { itemId: 'basilisk_scale', chance: '1/4' },
            // { itemId: 'petrifying_eye', chance: '1/512' }
        ],
    },
    {
        id: 'ember_demon',
        name: 'Ember Demon',
        level: 32,
        // slayerLevel: 20,
        maxHp: 40,
        attack: 28, strength: 30, defence: 30,
        stabDefence: 30, slashDefence: 30, crushDefence: 30, rangedDefence: 25, magicDefence: 35,
        iconUrl: 'ember-shot',
        types: [MonsterType.Demon, MonsterType.Elemental],
        attackSpeed: 4, respawnTime: 30000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'ember_rune', chance: '1/2', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'flux_rune', chance: '1/20', minQuantity: 2, maxQuantity: 8 },
            { itemId: 'gold_ore', chance: '1/16', minQuantity: 1, maxQuantity: 5, noted: true },
            { itemId: 'staff_of_ember', chance: '1/128' },
            { itemId: 'mithril_scimitar', chance: '1/64' },
            { itemId: 'adamantite_full_helm', chance: '1/128' },
            // { itemId: 'infernal_key_fragment', chance: '1/128' },
            { itemId: 'uncut_ruby', chance: '1/256' },
            { itemId: 'coal', chance: '1/10', minQuantity: 5, maxQuantity: 10, noted: true },
        ],
    },
    {
        id: 'leaf_beast',
        name: 'Leaf Beast',
        level: 40,
        // slayerLevel: 45,
        // requiredSlayerItem: 'broad_bladed_sword',
        maxHp: 55,
        attack: 35, strength: 40, defence: 40,
        stabDefence: 40, slashDefence: 45, crushDefence: 35, rangedDefence: 40, magicDefence: 30,
        iconUrl: 'leaf-swirl',
        types: [MonsterType.Beast],
        attackSpeed: 4, respawnTime: 35000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        mainDrops: [
            { tableId: 'herb_table', chance: '1/8', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'verdant_rune', chance: '1/4', minQuantity: 15, maxQuantity: 25 },
            { itemId: 'mithril_ore', chance: '1/32', noted: true },
            { itemId: 'mithril_battleaxe', chance: '1/128' },
            { itemId: 'adamantite_platelegs', chance: '1/128' },
            { itemId: 'yew_logs', chance: '1/16', minQuantity: 10, maxQuantity: 20, noted: true },
            { tableId: 'gem_table', chance: '1/16' },
            // { itemId: 'verdant_crest', chance: '1/512' },
        ],
    },
    {
        id: 'howling_terror',
        name: 'Howling Terror',
        level: 45,
        // slayerLevel: 30,
        // requiredSlayerItem: 'earthen_charm',
        maxHp: 60,
        attack: 40, strength: 45, defence: 40,
        stabDefence: 40, slashDefence: 40, crushDefence: 45, rangedDefence: 35, magicDefence: 45,
        iconUrl: 'terror',
        types: [MonsterType.Beast, MonsterType.Demon],
        attackSpeed: 4, respawnTime: 40000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'adamantite_ore', chance: '1/32', noted: true },
            { itemId: 'uncut_ruby', chance: '1/128' },
            { itemId: 'mithril_kiteshield', chance: '1/64' },
            { itemId: 'adamantite_sword', chance: '1/128' },
            { tableId: 'herb_table', chance: '1/10', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'coal', chance: '1/8', minQuantity: 10, maxQuantity: 30, noted: true },
            // { itemId: 'wraith_talons', chance: '1/64' },
            // { itemId: 'ailment_echo', chance: '1/256' },
        ],
    },
    {
        id: 'dust_fiend',
        name: 'Dust Fiend',
        level: 50,
        // slayerLevel: 35,
        // requiredSlayerItem: 'filtered_mask',
        maxHp: 65,
        attack: 45, strength: 48, defence: 45,
        stabDefence: 45, slashDefence: 45, crushDefence: 45, rangedDefence: 40, magicDefence: 50,
        iconUrl: 'dust-cloud',
        types: [MonsterType.Elemental],
        attackSpeed: 3, respawnTime: 28000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        guaranteedDrops: [{ itemId: 'ashes', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'mithril_bar', chance: '1/64', noted: true },
            { itemId: 'adamantite_scimitar', chance: '1/128' },
            // { itemId: 'sandstorm_staff', chance: '1/256' },
            { itemId: 'flux_rune', chance: '1/10', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'uncut_ruby', chance: '1/256' },
            { itemId: 'cooked_lobster', chance: '1/20', minQuantity: 1, maxQuantity: 1, noted: true },
            { tableId: 'herb_table', chance: '1/12' },
        ],
    },
    {
        id: 'gelatinous_abomination',
        name: 'Gelatinous Abomination',
        level: 55,
        // slayerLevel: 40,
        maxHp: 80,
        attack: 50, strength: 55, defence: 60,
        stabDefence: 60, slashDefence: 60, crushDefence: 30, rangedDefence: 60, magicDefence: 60,
        iconUrl: 'gooey-molecule',
        types: [MonsterType.Elemental],
        attackSpeed: 5, respawnTime: 30000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        mainDrops: [
            { itemId: 'aqua_rune', chance: '1/2', minQuantity: 30, maxQuantity: 60 },
            { itemId: 'mithril_kiteshield', chance: '1/128' },
            { tableId: 'gem_table', chance: '1/64' },
            { itemId: 'mithril_bar', chance: '1/32', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'adamantite_mace', chance: '1/128' },
            { itemId: 'yew_logs', chance: '1/16', minQuantity: 20, maxQuantity: 40, noted: true },
            { itemId: 'cooked_swordfish', chance: '1/20', minQuantity: 1, maxQuantity: 1, noted: true },
            // { itemId: 'viscous_orb', chance: '1/128' },
            { itemId: 'super_attack_potion', chance: '1/64' },
        ],
    },
    {
        id: 'gargantuan_tusker',
        name: 'Gargantuan Tusker',
        level: 60,
        // slayerLevel: 45,
        maxHp: 90,
        attack: 55, strength: 60, defence: 60,
        stabDefence: 55, slashDefence: 65, crushDefence: 60, rangedDefence: 55, magicDefence: 45,
        iconUrl: 'boar-tusks',
        types: [MonsterType.Beast],
        attackSpeed: 5, respawnTime: 45000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        guaranteedDrops: [{ itemId: 'big_bones', minQuantity: 1, maxQuantity: 1 }],
        mainDrops: [
            { itemId: 'mithril_bar', chance: '1/32', noted: true },
            { itemId: 'adamantite_ore', chance: '1/64', noted: true },
            { itemId: 'adamantite_warhammer', chance: '1/128' },
            { tableId: 'herb_table', chance: '1/8', minQuantity: 2, maxQuantity: 4, noted: true },
            { itemId: 'uncut_ruby', chance: '1/128' },
            { itemId: 'yew_logs', chance: '1/10', minQuantity: 30, maxQuantity: 60, noted: true },
            { itemId: 'cooked_swordfish', chance: '1/10', minQuantity: 2, maxQuantity: 3, noted: true },
        ],
    },
    {
        id: 'blighted_spectre',
        name: 'Blighted Spectre',
        level: 65,
        // slayerLevel: 50,
        // requiredSlayerItem: 'nose_clamp',
        maxHp: 70,
        attack: 1, magic: 60, strength: 1, defence: 55,
        stabDefence: 50, slashDefence: 50, crushDefence: 50, rangedDefence: 55, magicDefence: -20,
        iconUrl: 'ghost',
        types: [MonsterType.Undead, MonsterType.Elemental],
        attackSpeed: 4, respawnTime: 38000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        mainDrops: [
            { itemId: 'coins', chance: '1/16', minQuantity: 2000, maxQuantity: 4000 },
            { tableId: 'herb_table', chance: '1/4', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'mithril_platelegs', chance: '1/128' },
            { itemId: 'adamantite_full_helm', chance: '1/128' },
            { itemId: 'uncut_diamond', chance: '1/256' },
            { itemId: 'nexus_rune', chance: '1/8', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'super_defence_potion', chance: '1/64' },
            { itemId: 'cooked_shark', chance: '1/20' },
            // { itemId: 'wraithwalkers', chance: '1/512' },
        ],
    },
    {
        id: 'ethereal_phantom',
        name: 'Ethereal Phantom',
        level: 70,
        // slayerLevel: 55,
        maxHp: 75,
        attack: 1, magic: 65, strength: 1, defence: 60,
        stabDefence: 55, slashDefence: 55, crushDefence: 55, rangedDefence: 60, magicDefence: 65,
        iconUrl: 'spooky-house',
        types: [MonsterType.Undead],
        attackSpeed: 4, respawnTime: 42000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        mainDrops: [
            { itemId: 'coins', chance: '1/16', minQuantity: 3000, maxQuantity: 5000 },
            { itemId: 'astral_rune', chance: '1/5', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'adamantite_kiteshield', chance: '1/128' },
            { itemId: 'runic_dagger', chance: '1/256' },
            { tableId: 'herb_table', chance: '1/6', minQuantity: 3, maxQuantity: 5, noted: true },
            { itemId: 'uncut_diamond', chance: '1/256' },
            { itemId: 'prayer_potion', chance: '1/64' },
            { itemId: 'yew_logs', chance: '1/10', minQuantity: 50, maxQuantity: 100, noted: true },
            // { itemId: 'ghostweave_chain', chance: '1/512' },
        ],
    },
    {
        id: 'stone_guardian',
        name: 'Stone Guardian',
        level: 75,
        // slayerLevel: 60,
        // requiredSlayerItem: 'stonecracker_hammer',
        maxHp: 110,
        attack: 68, strength: 72, defence: 80,
        stabDefence: 80, slashDefence: 80, crushDefence: 40, rangedDefence: 80, magicDefence: 30,
        iconUrl: 'stone-guardian',
        types: [MonsterType.Elemental, MonsterType.Armored],
        attackSpeed: 6, respawnTime: 55000, alwaysDrops: true, aggressive: true, attackStyle: 'crush',
        mainDrops: [
            { itemId: 'coins', chance: '1/16', minQuantity: 5000, maxQuantity: 8000 },
            { itemId: 'adamantite_bar', chance: '1/32', noted: true },
            { tableId: 'gem_table', chance: '1/64' },
            { itemId: 'runic_bar', chance: '1/128' },
            { itemId: 'adamantite_platebody', chance: '1/128' },
            { itemId: 'cooked_shark', chance: '1/10', minQuantity: 2, maxQuantity: 3, noted: true },
            { tableId: 'herb_table', chance: '1/8', minQuantity: 4, maxQuantity: 8, noted: true },
            { itemId: 'yew_logs', chance: '1/8', minQuantity: 100, maxQuantity: 150, noted: true },
            // { itemId: 'basalt_crusher', chance: '1/512' },
        ],
    },
    {
        id: 'shadow_weaver',
        name: 'Shadow Weaver',
        level: 85,
        // slayerLevel: 70,
        maxHp: 100,
        attack: 1, magic: 80, strength: 1, defence: 75,
        stabDefence: 70, slashDefence: 70, crushDefence: 70, rangedDefence: 75, magicDefence: 80,
        iconUrl: 'spider-web',
        types: [MonsterType.Demon],
        attackSpeed: 4, respawnTime: 50000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        mainDrops: [
            { itemId: 'coins', chance: '1/16', minQuantity: 8000, maxQuantity: 12000 },
            { itemId: 'nexus_rune', chance: '1/4', minQuantity: 30, maxQuantity: 60 },
            { tableId: 'herb_table', chance: '1/4', minQuantity: 2, maxQuantity: 5, noted: true },
            { itemId: 'runic_bar', chance: '1/64', noted: true },
            { itemId: 'runic_longsword', chance: '1/256' },
            { itemId: 'uncut_diamond', chance: '1/128' },
            { itemId: 'prayer_potion', chance: '1/32', minQuantity: 1, maxQuantity: 2, noted: true },
            { itemId: 'yew_logs', chance: '1/5', minQuantity: 100, maxQuantity: 250, noted: true },
            // { itemId: 'voidsilk_hood', chance: '1/512' },
        ],
    },
    {
        id: 'void_stalker',
        name: 'Void Stalker',
        level: 90,
        // slayerLevel: 75,
        maxHp: 130,
        attack: 85, strength: 90, defence: 80,
        stabDefence: 80, slashDefence: 85, crushDefence: 75, rangedDefence: 80, magicDefence: 80,
        iconUrl: 'evil-fork',
        types: [MonsterType.Demon],
        attackSpeed: 3, respawnTime: 60000, alwaysDrops: true, aggressive: true, attackStyle: 'slash',
        mainDrops: [
            { itemId: 'coins', chance: '1/16', minQuantity: 10000, maxQuantity: 15000 },
            { itemId: 'runic_bar', chance: '1/64' },
            { itemId: 'runic_platelegs', chance: '1/256' },
            { tableId: 'herb_table', chance: '1/5', minQuantity: 3, maxQuantity: 6, noted: true },
            { itemId: 'uncut_diamond', chance: '1/128' },
            { itemId: 'adamantite_bar', chance: '1/10', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'aether_rune', chance: '1/10', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'cooked_shark', chance: '1/5', minQuantity: 5, maxQuantity: 5, noted: true },
            // { itemId: 'demonic_whip', chance: '1/512' },
        ],
    },
    {
        id: 'frost_wyvern',
        name: 'Frost Wyvern',
        level: 95,
        // slayerLevel: 80,
        maxHp: 150,
        attack: 1, magic: 90, strength: 1, defence: 90,
        stabDefence: 85, slashDefence: 85, crushDefence: 85, rangedDefence: 90, magicDefence: 45,
        iconUrl: 'ice-dragon',
        types: [MonsterType.Dragon],
        attackSpeed: 5, respawnTime: 180000, alwaysDrops: true, aggressive: true, attackStyle: 'magic',
        guaranteedDrops: [{ itemId: 'frost_dragon_bones', minQuantity: 1, maxQuantity: 1 }],
        fireWeakness: 1.0,
        mainDrops: [
            { itemId: 'wyvern_claw', chance: "1/4", minQuantity: 1, maxQuantity: 1 },
            { itemId: 'coins', chance: '1/16', minQuantity: 12000, maxQuantity: 18000 },
            { itemId: 'uncut_diamond', chance: '1/128' },
            { itemId: 'runic_platelegs', chance: '1/256' },
            { itemId: 'runic_bar', chance: '1/32', minQuantity: 1, maxQuantity: 3, noted: true },
            { itemId: 'yew_logs', chance: '1/4', minQuantity: 150, maxQuantity: 300, noted: true },
            { tableId: 'herb_table', chance: '1/5', minQuantity: 5, maxQuantity: 10, noted: true },
            { itemId: 'anima_rune', chance: '1/5', minQuantity: 20, maxQuantity: 40 },
            { itemId: 'aether_rune', chance: '1/8', minQuantity: 15, maxQuantity: 30 },
            { itemId: 'flaming_gullet', chance: '1/10000' },
            { itemId: 'adamantite_platebody', chance: '1/32.5' },
            { itemId: 'adamantite_warhammer', chance: '1/32.5' },
            { itemId: 'runic_greatsword', chance: '1/65' },
            { itemId: 'runic_kiteshield', chance: '1/65' },
            { itemId: 'runic_longsword', chance: '1/65' },
            { itemId: 'runic_pickaxe', chance: '1/65' },
            { itemId: 'gust_rune', chance: '1/11.82', minQuantity: 100, maxQuantity: 200 },
            { itemId: 'aqua_rune', chance: '1/13', minQuantity: 100, maxQuantity: 200 },
            { itemId: 'flux_rune', chance: '1/16.25', minQuantity: 60, maxQuantity: 80 },
            { itemId: 'nexus_rune', chance: '1/26', minQuantity: 20, maxQuantity: 30 },
            { itemId: 'anima_rune', chance: '1/26', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'verdant_rune', chance: '1/32.5', minQuantity: 10, maxQuantity: 20 },
            { itemId: 'apple_pie', chance: '1/26' },
            { itemId: 'titanium_ore', chance: '1/43.33', minQuantity: 6, maxQuantity: 15, noted: true },
            { itemId: 'adamantite_ore', chance: '1/43.33', minQuantity: 12, maxQuantity: 25, noted: true },
        ],
    },
];
