import { Item } from '../../types';

export const resources: Item[] = [
    // Ores
    { id: 'copper_ore', itemNum: 401, name: 'Copper Ore', description: 'A lump of copper ore.', stackable: false, value: 10, iconUrl: 'ore', material: 'copper' },
    { id: 'tin_ore', itemNum: 402, name: 'Tin Ore', description: 'A lump of tin ore.', stackable: false, value: 10, iconUrl: 'ore', material: 'tin' },
    { id: 'iron_ore', itemNum: 403, name: 'Iron Ore', description: 'A lump of iron ore.', stackable: false, value: 30, iconUrl: 'ore', material: 'iron-ore' },
    { id: 'coal', itemNum: 404, name: 'Coal', description: 'A lump of coal, essential for smelting high-grade metals.', stackable: false, value: 30, iconUrl: 'coal-wagon', material: 'burnt' },
    { id: 'silver_ore', itemNum: 405, name: 'Silver Ore', description: 'A chunk of rock containing veins of silver.', stackable: false, value: 40, iconUrl: 'ore', material: 'silver' },
    { id: 'gold_ore', itemNum: 406, name: 'Gold Ore', description: 'A lump of gold ore.', stackable: false, value: 120, iconUrl: 'ore', material: 'gold' },
    { id: 'mithril_ore', itemNum: 407, name: 'Mithril Ore', description: 'A chunk of raw, silvery-blue mithril ore.', stackable: false, value: 300, iconUrl: 'ore', material: 'mithril-ore' },
    { id: 'adamantite_ore', itemNum: 408, name: 'Adamantite Ore', description: 'A chunk of raw, dark green adamantite ore.', stackable: false, value: 400, iconUrl: 'ore', material: 'adamantite-ore' },
    { id: 'titanium_ore', itemNum: 409, name: 'Titanium Ore', description: 'A chunk of incredibly rare, purplish titanium ore.', stackable: false, value: 600, iconUrl: 'ore', material: 'titanium-ore' },
    { id: 'rune_essence', itemNum: 410, name: 'Rune Essence', description: 'A fragment of rock containing pure magical energy.', stackable: false, value: 5, iconUrl: 'rock', material: 'mithril' },

    // Bars
    { id: 'bronze_bar', itemNum: 411, name: 'Bronze Bar', description: 'A bar of bronze, ready for smithing.', stackable: false, value: 20, iconUrl: 'metal-bar', material: 'bronze' },
    { id: 'iron_bar', itemNum: 412, name: 'Iron Bar', description: 'A bar of iron, ready for smithing.', stackable: false, value: 100, iconUrl: 'metal-bar', material: 'iron' },
    { id: 'steel_bar', itemNum: 413, name: 'Steel Bar', description: 'A bar of steel, ready for smithing.', stackable: false, value: 300, iconUrl: 'metal-bar', material: 'steel' },
    { id: 'silver_bar', itemNum: 414, name: 'Silver Bar', description: 'A bar of pure silver.', stackable: false, value: 130, iconUrl: 'gold-bar', material: 'silver' },
    { id: 'gold_bar', itemNum: 415, name: 'Gold Bar', description: 'A bar of pure gold.', stackable: false, value: 250, iconUrl: 'gold-bar', material: 'gold' },
    { id: 'mithril_bar', itemNum: 416, name: 'Mithril Bar', description: 'A bar of refined mithril.', stackable: false, value: 1400, iconUrl: 'metal-bar', material: 'mithril' },
    { id: 'adamantite_bar', itemNum: 417, name: 'Adamantite Bar', description: 'A bar of refined adamantite.', stackable: false, value: 2000, iconUrl: 'metal-bar', material: 'adamantite' },
    { id: 'runic_bar', itemNum: 418, name: 'Runic Bar', description: 'A bar of refined, durable runic metal.', stackable: false, value: 5000, iconUrl: 'metal-bar', material: 'runic' },

    // Logs
    { id: 'logs', itemNum: 419, name: 'Logs', description: 'Standard logs from a tree.', stackable: false, value: 5, iconUrl: 'wood-pile', material: 'wood-normal' },
    { id: 'oak_logs', itemNum: 420, name: 'Oak Logs', description: 'Sturdy logs from a mighty oak tree.', stackable: false, value: 20, iconUrl: 'wood-pile', material: 'wood-oak' },
    { id: 'willow_logs', itemNum: 421, name: 'Willow Logs', description: 'Flexible logs from a willow tree.', stackable: false, value: 35, iconUrl: 'wood-pile', material: 'wood-willow' },
    { id: 'maple_logs', itemNum: 422, name: 'Maple Logs', description: 'Hard logs from a maple tree, excellent for strong bows.', stackable: false, value: 60, iconUrl: 'wood-pile', material: 'wood-oak' },
    { id: 'feywood_logs', itemNum: 423, name: 'Feywood Logs', description: 'Logs from a Feywood tree. They shimmer with a faint, magical light.', stackable: false, value: 120, iconUrl: 'wood-pile', material: 'wood-feywood' },
    { id: 'yew_logs', itemNum: 424, name: 'Yew Logs', description: 'Logs from an ancient yew tree, perfect for powerful bows.', stackable: false, value: 300, iconUrl: 'wood-pile', material: 'wood-yew' },
    { id: 'driftwood_logs', itemNum: 425, name: 'Driftwood Logs', description: 'Weathered logs, hardened by the sea.', stackable: false, value: 5, iconUrl: 'wood-pile', material: 'wood-driftwood' },
    { id: 'mahogany_logs', itemNum: 426, name: 'Mahogany Logs', description: 'Rich, dark red logs from a tropical tree.', stackable: false, value: 120, iconUrl: 'wood-pile', material: 'wood-mahogany' },

    // Gems
    { id: 'uncut_sapphire', itemNum: 427, name: 'Uncut Sapphire', description: 'A raw, uncut sapphire. Could be cut with a chisel.', stackable: false, value: 50, iconUrl: 'emerald', material: 'uncut-sapphire' },
    { id: 'sapphire', itemNum: 428, name: 'Sapphire', description: 'A beautiful blue gemstone.', stackable: false, value: 100, iconUrl: 'rupee', material: 'sapphire' },
    { id: 'uncut_emerald', itemNum: 429, name: 'Uncut Emerald', description: 'A raw, uncut emerald. Could be cut with a chisel.', stackable: false, value: 100, iconUrl: 'emerald', material: 'uncut-emerald' },
    { id: 'emerald', itemNum: 430, name: 'Emerald', description: 'A brilliant green gemstone.', stackable: false, value: 200, iconUrl: 'rupee', material: 'emerald' },
    { id: 'uncut_ruby', itemNum: 431, name: 'Uncut Ruby', description: 'A raw, uncut ruby. Could be cut with a chisel.', stackable: false, value: 200, iconUrl: 'emerald', material: 'uncut-ruby' },
    { id: 'ruby', itemNum: 432, name: 'Ruby', description: 'A deep red gemstone.', stackable: false, value: 400, iconUrl: 'rupee', material: 'ruby' },
    { id: 'uncut_diamond', itemNum: 433, name: 'Uncut Diamond', description: 'A raw, uncut diamond. Could be cut with a chisel.', stackable: false, value: 1000, iconUrl: 'emerald', material: 'uncut-diamond' },
    { id: 'diamond', itemNum: 434, name: 'Diamond', description: 'A brilliant, clear gemstone.', stackable: false, value: 2000, iconUrl: 'rupee', material: 'diamond' },
    { id: 'uncut_sunstone', itemNum: 435, name: 'Uncut Sunstone', description: "A raw, uncut sunstone. It seems to glow with an inner warmth. Could be cut with a chisel.", stackable: false, value: 5000, iconUrl: 'emerald', material: 'uncut-sunstone' },
    { id: 'sunstone', itemNum: 436, name: 'Sunstone', description: 'A brilliant yellow gemstone that seems to capture the light of the sun.', stackable: false, value: 10000, iconUrl: 'rupee', material: 'sunstone' },
    { id: 'uncut_tenebrite', itemNum: 437, name: 'Uncut Tenebrite', description: "A raw, uncut piece of tenebrite. It seems to absorb light. Could be cut with a chisel.", stackable: false, value: 20000, iconUrl: 'emerald', material: 'uncut-tenebrite' },
    { id: 'tenebrite', itemNum: 438, name: 'Tenebrite', description: 'A perfectly cut, deep black gemstone that seems to drink the light around it.', stackable: false, value: 40000, iconUrl: 'rupee', material: 'tenebrite' },

    // Monster Drops & Crafting Materials
    { id: 'crystal_shard', itemNum: 439, name: 'Crystal Shard', description: 'A sharp, resonating shard of pure crystal.', stackable: true, value: 75, iconUrl: 'gold-nuggets', material: 'diamond' },
    { id: 'resonating_crystal', itemNum: 440, name: 'Resonating Crystal', description: 'A larger crystal that hums with a powerful, stored energy.', stackable: false, value: 350, iconUrl: 'crystal-cluster', material: 'diamond' },
    { id: 'scuttler_shell_fragment', itemNum: 441, name: 'Scuttler Shell Fragment', description: 'A hard, sharp fragment from a Crystal Scuttler\'s shell.', stackable: false, value: 40, iconUrl: 'sharp-halberd', material: 'steel' },
    { id: 'goblin_hide', itemNum: 442, name: 'Goblin Hide', description: 'Tough hide from a goblin.', stackable: false, value: 5, iconUrl: 'animal-hide' },
    { id: 'rat_tail', itemNum: 443, name: 'Rat Tail', description: 'A grim trophy from a slain rodent.', stackable: false, value: 1, iconUrl: 'rat' },
    { id: 'spider_silk', itemNum: 444, name: 'Spider Silk', description: 'Tough, sticky silk from a giant spider.', stackable: false, value: 8, iconUrl: 'spider-web' },
    { id: 'wool', itemNum: 445, name: 'Wool', description: 'Raw, unspun wool from a sheep.', stackable: false, value: 2, iconUrl: 'fluffy-cloud' },
    { id: 'ball_of_wool', itemNum: 446, name: 'Ball of Wool', description: 'A ball of fluffy wool, ready for crafting.', stackable: false, value: 3, iconUrl: 'wool' },
    { id: 'bones', itemNum: 447, name: 'Bones', description: 'A set of ordinary bones. Can be buried for Prayer experience.', stackable: false, value: 2, iconUrl: 'crossed-bones', buryable: { prayerXp: 5 } },
    { id: 'big_bones', itemNum: 448, name: 'Big Bones', description: 'Larger bones from a tougher creature. Can be buried for Prayer experience.', stackable: false, value: 10, iconUrl: 'crossed-bones', buryable: { prayerXp: 15 } },
    { id: 'dragon_bones', itemNum: 449, name: 'Dragon Bones', description: 'Large, scorched bones from a dragon. Bury them for a large amount of Prayer experience.', stackable: false, value: 200, iconUrl: 'dinosaur-bones', buryable: { prayerXp: 100 } },
    { id: 'frost_dragon_bones', itemNum: 450, name: 'Frost Dragon Bones', description: 'The bones of a Frost Dragon. They are cold to the touch and radiate a faint magical aura.', stackable: false, value: 2500, iconUrl: 'dinosaur-bones', material: 'rune-aqua', buryable: { prayerXp: 200 } },
    { id: 'eggs', itemNum: 451, name: 'Chicken Egg', description: 'A fresh egg. A simple cooking ingredient.', stackable: false, value: 2, iconUrl: 'egg-clutch' },
    { id: 'cowhide', itemNum: 452, name: 'Cowhide', description: 'The unprocessed hide of a cow. It needs to be tanned.', stackable: false, value: 6, iconUrl: 'animal-hide' },
    { id: 'leather', itemNum: 453, name: 'Leather', description: 'A piece of tanned leather, ready for crafting.', stackable: false, value: 10, iconUrl: 'animal-hide', material: 'leather' },
    { id: 'flax', itemNum: 454, name: 'Flax', description: 'A plant that can be spun into a bow string.', stackable: false, value: 1, iconUrl: 'flax' },
    { id: 'bow_string', itemNum: 455, name: 'Bow String', description: 'A string for a bow.', stackable: false, value: 5, iconUrl: 'whiplash' },
    { id: 'rope', itemNum: 456, name: 'Rope', description: 'A sturdy length of rope.', stackable: false, value: 15, iconUrl: 'rope-coil' },
    { id: 'mystic_page', itemNum: 457, name: 'Mystic Page', description: 'A page from an arcane text, humming with magical potential.', stackable: true, value: 20, iconUrl: 'scroll-unfurled', material: 'rune-aqua' },
    { id: 'harpy_feather', itemNum: 458, name: 'Harpy Feather', description: 'A large, sharp feather from a harpy. Could be used in fletching.', stackable: true, value: 50, iconUrl: 'feather', material: 'uncut-sapphire' },
    { id: 'golem_core', itemNum: 459, name: 'Golem Core', description: 'A faintly glowing stone that was the heart of a stone golem. Can be shattered with a hammer.', stackable: false, value: 500, iconUrl: 'glowing-artifact' },
    { id: 'straw', itemNum: 460, name: 'Straw', description: 'A bundle of dry straw. It smells faintly of hay and old magic.', stackable: false, value: 1, iconUrl: 'wheat' },
    { id: 'boar_hide', itemNum: 461, name: 'Boar Hide', description: 'The tough, bristly hide of a wild boar. It needs to be tanned.', stackable: false, value: 8, iconUrl: 'animal-hide' },
    { id: 'boar_leather', itemNum: 462, name: 'Boar Leather', description: 'Tanned hide from a wild boar, ready for crafting.', stackable: false, value: 12, iconUrl: 'animal-hide', material: 'leather' },
    { id: 'fey_dust', itemNum: 463, name: 'Fey Dust', description: 'A pinch of glittering, magical dust with a faint lavender scent.', stackable: false, value: 75, iconUrl: 'powder' },
    { id: 'serpent_scale_dust', itemNum: 464, name: 'Serpent Scale Dust', description: 'Fine, iridescent dust ground from the scales of a powerful swamp serpent.', stackable: false, value: 150, iconUrl: 'powder' },
    { id: 'giant_crab_claw', itemNum: 465, name: 'Giant Crab Claw', description: 'A massive claw from a giant crab. It could probably take a finger off.', stackable: false, value: 20, iconUrl: 'crab-claw' },
    { id: 'enchanted_bark', itemNum: 466, name: 'Enchanted Bark', description: 'Bark from a Feywood tree that hums with a faint magical energy.', stackable: false, value: 60, iconUrl: 'planks' },
    { id: 'brimstone', itemNum: 467, name: 'Brimstone', description: 'A chunk of yellow, sulfuric rock that is warm to the touch.', stackable: false, value: 180, iconUrl: 'rock', material: 'gold' },
    { id: 'wolf_pelt', itemNum: 468, name: 'Wolf Pelt', description: 'The fur of a wolf. It needs to be tanned.', stackable: false, value: 25, iconUrl: 'animal-hide' },
    { id: 'wolf_leather', itemNum: 469, name: 'Wolf Leather', description: 'Tanned pelt from a wolf, ready for crafting.', stackable: false, value: 35, iconUrl: 'animal-hide', material: 'leather' },
    { id: 'bear_pelt', itemNum: 470, name: 'Bear Pelt', description: 'The thick fur of a bear. It needs to be tanned.', stackable: false, value: 40, iconUrl: 'animal-hide' },
    { id: 'bear_leather', itemNum: 471, name: 'Bear Leather', description: 'Tanned pelt from a bear, ready for crafting.', stackable: false, value: 60, iconUrl: 'animal-hide', material: 'leather' },
    { id: 'harpy_talon', itemNum: 472, name: 'Harpy Talon', description: 'A sharp, resilient talon from a harpy. It seems to resonate with a strange energy.', stackable: false, value: 250, iconUrl: 'bird-claw' },
    { id: 'crystalline_chitin', itemNum: 473, name: 'Crystalline Chitin', description: 'A fragment of exoskeleton from a Salt Flats creature, encrusted with shimmering salt crystals.', stackable: false, value: 400, iconUrl: 'insect-jaws', material: 'silver' },
    { id: 'eldritch_pearl', itemNum: 474, name: 'Eldritch Pearl', description: 'A swirling, dark pearl that seems to whisper secrets when held to the ear. It feels ancient.', stackable: false, value: 1200, iconUrl: 'mineral-pearls', material: 'burnt' },
    // New baking resources
    { id: 'wheat', itemNum: 475, name: 'Wheat', description: 'A stalk of wheat.', stackable: false, value: 1, iconUrl: 'grain-bundle' },
    { id: 'flour', itemNum: 476, name: 'Sack of Flour', description: 'A sack filled with finely milled flour.', stackable: false, value: 3, iconUrl: 'grain' },
    { id: 'bucket_of_water', itemNum: 477, name: 'Bucket of Water', description: 'A bucket filled with water.', stackable: false, value: 2, iconUrl: 'full-wood-bucket', emptyable: { emptyItemId: 'bucket' }, material: 'vial-water' },
    { id: 'bucket_of_milk', itemNum: 478, name: 'Bucket of Milk', description: 'A bucket filled with fresh milk.', stackable: false, value: 4, iconUrl: 'full-wood-bucket', emptyable: { emptyItemId: 'bucket' } },
    // New Salt Flats resources
    { id: 'rock_salt', itemNum: 479, name: 'Rock Salt', description: 'A sharp, crystalline chunk of salt.', stackable: false, value: 15, iconUrl: 'salt-shaker', material: 'tin' },
    { id: 'brine_crystal', itemNum: 480, name: 'Brine Crystal', description: 'A perfectly formed crystal, saturated with magical brine.', stackable: false, value: 100, iconUrl: 'crystal-cluster', material: 'sapphire' },
    { id: 'crystalline_shell_shard', itemNum: 481, name: 'Crystalline Shell Shard', description: "A shard from a Crystalline Tortoise. It's surprisingly light and sharp.", stackable: false, value: 120, iconUrl: 'oyster', material: 'steel' },
    { id: 'ancient_fossil', itemNum: 482, name: 'Ancient Fossil', description: 'The fossilized remains of an ancient sea creature.', stackable: false, value: 250, iconUrl: 'ammonite-fossil' },
    // Dragonhides
    { id: 'grove_hide', itemNum: 483, name: 'Grove Hide', description: 'A flexible hide cut from a Grove Dragon', stackable: false, value: 300, iconUrl: 'animal-hide', material: 'uncut-emerald' },
    { id: 'frost_hide', itemNum: 484, name: 'Frost Hide', description: 'A tough hide cut from a Frosthide Dragon', stackable: false, value: 400, iconUrl: 'animal-hide', material: 'uncut-sapphire' },
    { id: 'emberscale_hide', itemNum: 485, name: 'Emberscale Hide', description: 'A scaley hide cut from a Emberscale Dragon', stackable: false, value: 600, iconUrl: 'animal-hide', material: 'uncut-ruby' },
    { id: 'deathscythe_hide', itemNum: 486, name: 'Deathscythe Hide', description: 'An ominous hide cut from a Deathscythe Dragon', stackable: false, value: 800, iconUrl: 'animal-hide', material: 'rune-nexus' },
    //Dragon Leather
    { id: 'grove_hide_leather', itemNum: 487, name: 'Grove Leather', description: 'A tough chunk of leather tanned from a dragon hide', stackable: false, value: 400, iconUrl: 'animal-hide', material: 'emerald' },
    { id: 'frost_hide_leather', itemNum: 488, name: 'Frosthide Leather', description: 'A tough chunk of leather tanned from a dragon hide', stackable: false, value: 500, iconUrl: 'animal-hide', material: 'sapphire' },
    { id: 'emberscale_hide_leather', itemNum: 489, name: 'Emberscale Leather', description: 'A tough chunk of leather tanned from a dragon hide', stackable: false, value: 700, iconUrl: 'animal-hide', material: 'ruby' },
    { id: 'deathscythe_hide_leather', itemNum: 490, name: 'Deathscythe Leather', description: 'A tough chunk of leather tanned from a dragon hide', stackable: false, value: 900, iconUrl: 'animal-hide', material: 'burnt' },

    // Crossbow Components
    { id: 'crossbow_string', itemNum: 491, name: 'Crossbow String', description: 'A sturdy string for a crossbow.', stackable: false, value: 10, iconUrl: 'knot' },
    // Stocks
    { id: 'wood_stock', itemNum: 492, name: 'Wooden Stock', description: 'A stock for a crossbow, made from normal wood.', stackable: false, value: 10, iconUrl: 'gun-stock', material: 'wood-normal' },
    { id: 'oak_stock', itemNum: 493, name: 'Oak Stock', description: 'A stock for a crossbow, made from oak.', stackable: false, value: 25, iconUrl: 'gun-stock', material: 'wood-oak' },
    { id: 'willow_stock', itemNum: 494, name: 'Willow Stock', description: 'A stock for a crossbow, made from willow.', stackable: false, value: 50, iconUrl: 'gun-stock', material: 'wood-willow' },
    { id: 'feywood_stock', itemNum: 495, name: 'Feywood Stock', description: 'A stock for a crossbow, made from feywood.', stackable: false, value: 80, iconUrl: 'gun-stock', material: 'wood-feywood' },
    { id: 'mahogany_stock', itemNum: 496, name: 'Mahogany Stock', description: 'A stock for a crossbow, made from mahogany.', stackable: false, value: 120, iconUrl: 'gun-stock', material: 'wood-mahogany' },
    { id: 'yew_stock', itemNum: 497, name: 'Yew Stock', description: 'A stock for a crossbow, made from yew.', stackable: false, value: 180, iconUrl: 'gun-stock', material: 'wood-yew' },
    // Limbs
    { id: 'bronze_limbs', itemNum: 498, name: 'Bronze Limbs', description: 'The metal limbs for a bronze crossbow.', stackable: false, value: 20, iconUrl: 'lead-pipe', material: 'bronze' },
    { id: 'iron_limbs', itemNum: 499, name: 'Iron Limbs', description: 'The metal limbs for an iron crossbow.', stackable: false, value: 50, iconUrl: 'lead-pipe', material: 'iron' },
    { id: 'steel_limbs', itemNum: 500, name: 'Steel Limbs', description: 'The metal limbs for a steel crossbow.', stackable: false, value: 100, iconUrl: 'lead-pipe', material: 'steel' },
    { id: 'mithril_limbs', itemNum: 501, name: 'Mithril Limbs', description: 'The metal limbs for a mithril crossbow.', stackable: false, value: 250, iconUrl: 'lead-pipe', material: 'mithril' },
    { id: 'adamantite_limbs', itemNum: 502, name: 'Adamantite Limbs', description: 'The metal limbs for an adamantite crossbow.', stackable: false, value: 500, iconUrl: 'lead-pipe', material: 'adamantite' },
    { id: 'runic_limbs', itemNum: 503, name: 'Runic Limbs', description: 'The metal limbs for a runic crossbow.', stackable: false, value: 8200, iconUrl: 'lead-pipe', material: 'runic' },
    // Unfinished Bolts
    { id: 'bronze_bolts_unf', itemNum: 504, name: 'Bronze Bolts (unf)', description: 'Unfinished bronze bolts. They need feathers.', stackable: true, value: 1, iconUrl: 'spears', material: 'bronze' },
    { id: 'iron_bolts_unf', itemNum: 505, name: 'Iron Bolts (unf)', description: 'Unfinished iron bolts. They need feathers.', stackable: true, value: 3, iconUrl: 'spears', material: 'iron' },
    { id: 'steel_bolts_unf', itemNum: 506, name: 'Steel Bolts (unf)', description: 'Unfinished steel bolts. They need feathers.', stackable: true, value: 6, iconUrl: 'spears', material: 'steel' },
    { id: 'mithril_bolts_unf', itemNum: 507, name: 'Mithril Bolts (unf)', description: 'Unfinished mithril bolts. They need feathers.', stackable: true, value: 12, iconUrl: 'spears', material: 'mithril' },
    { id: 'adamantite_bolts_unf', itemNum: 508, name: 'Adamantite Bolts (unf)', description: 'Unfinished adamantite bolts. They need feathers.', stackable: true, value: 20, iconUrl: 'spears', material: 'adamantite' },
    { id: 'runic_bolts_unf', itemNum: 509, name: 'Runic Bolts (unf)', description: 'Unfinished runic bolts. They need feathers.', stackable: true, value: 250, iconUrl: 'spears', material: 'runic' },
    // Glassblowing Resources
    { id: 'seaweed', itemNum: 510, name: 'Seaweed', description: 'A slimy piece of seaweed. Can be cooked into soda ash.', stackable: false, value: 1, iconUrl: 'algae', material: 'clean-herb' },
    { id: 'soda_ash', itemNum: 511, name: 'Soda Ash', description: 'A key ingredient in glassmaking.', stackable: false, value: 5, iconUrl: 'powder' },
    { id: 'bucket_of_sand', itemNum: 512, name: 'Bucket of Sand', description: 'A bucket filled with fine sand.', stackable: false, value: 3, iconUrl: 'full-wood-bucket', material: 'gold' },
    { id: 'molten_glass', itemNum: 513, name: 'Molten Glass', description: 'A glowing glob of molten glass, ready to be shaped.', stackable: false, value: 20, iconUrl: 'bubbles', material: 'rune-ember' },
    { id: 'un_tuned_orb', itemNum: 514, name: 'Un-tuned Orb', description: 'A solid glass orb that hums with potential. It needs to be attuned at a magical altar.', stackable: false, value: 100, iconUrl: 'crystal-ball' },
    { id: 'lantern_lens', itemNum: 515, name: 'Lantern Lens', description: 'A perfectly clear glass lens, ready to be fitted into a lantern.', stackable: false, value: 80, iconUrl: 'glass-shot' },
    { id: 'light_orb', itemNum: 516, name: 'Light Orb', description: 'A delicate glass orb that can hold a powerful light source.', stackable: false, value: 200, iconUrl: 'glass-ball' },
];
