import { Item, EquipmentSlot, SkillName, WeaponType } from '../../types';

// These items are required to fight specific Slayer monsters.
export const slayerGear: Item[] = [
    { id: 'bag_of_salt', itemNum: 724, name: 'Bag of Salt', description: 'A bag of coarse salt, effective against certain slimy creatures.', stackable: true, value: 5, iconUrl: 'salt-shaker' },
    { id: 'reflective_shield', itemNum: 725, name: 'Reflective Shield', description: 'A highly polished shield that can reflect a monster\'s gaze.', stackable: false, value: 2500, iconUrl: 'shield-reflect', material: 'steel', equipment: { slot: EquipmentSlot.Shield, stabDefence: 15, slashDefence: 20, crushDefence: 18, rangedDefence: 15, magicDefence: 5, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    { id: 'broad_bladed_sword', itemNum: 726, name: 'Broad-bladed Sword', description: 'A sword with an unusually wide blade, specifically designed for harming tough-skinned beasts.', stackable: false, value: 15000, iconUrl: 'broadsword', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Sword, speed: 4, stabAttack: 20, slashAttack: 35, crushAttack: -2, strengthBonus: 32, requiredLevels: [{ skill: SkillName.Attack, level: 40 }, { skill: SkillName.Slayer, level: 55 }], } },
    { id: 'earthen_charm', itemNum: 727, name: 'Earthen Charm', description: 'A simple clay charm that seems to absorb sound.', stackable: false, value: 150, iconUrl: 'echo-ripples', equipment: { slot: EquipmentSlot.Necklace, magicDefence: 2 } },
    { id: 'filtered_mask', itemNum: 728, name: 'Filtered Mask', description: 'A mask with a thick filter, designed to protect the wearer from noxious dust and spores.', stackable: false, value: 80, iconUrl: 'gas-mask', equipment: { slot: EquipmentSlot.Head, stabDefence: 1, slashDefence: 1, crushDefence: 1 } },
    { id: 'nose_clamp', itemNum: 729, name: 'Nose Clamp', description: 'A simple clamp worn on the nose to block out foul smells.', stackable: false, value: 2, iconUrl: 'nose-front', equipment: { slot: EquipmentSlot.Head } },
    { id: 'stonecracker_hammer', itemNum: 730, name: 'Stonecracker Hammer', description: 'A heavy hammer specially designed to shatter the tough hides of rock-like creatures.', stackable: false, value: 3000, iconUrl: 'flat-hammer', material: 'adamantite' },
    { id: 'slayers_lantern', itemNum: 731, name: "Slayer's Lantern", description: "A specially crafted lantern that burns with anti-void flame. Protects the bearer from shadow disorientation in void-touched areas.", stackable: false, value: 15000, iconUrl: 'lantern-flame', equipment: { slot: EquipmentSlot.Shield, magicDefence: 3, requiredLevels: [{ skill: SkillName.Slayer, level: 65 }, { skill: SkillName.Firemaking, level: 60 }] } },
];
