import { Item, EquipmentSlot, SkillName, WeaponType, ToolType } from '../../types';

export const tools: Item[] = [
    // Axes
    { id: 'bronze_axe', itemNum: 741, name: 'Bronze Axe', description: 'A simple bronze axe, mainly used for chopping trees.', stackable: false, value: 10, iconUrl: 'wood-axe', equipment: { slot: EquipmentSlot.Weapon, stabAttack: -2, slashAttack: 4, crushAttack: 2, strengthBonus: 5, weaponType: WeaponType.Axe, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], }, tool: { type: ToolType.Axe, power: 10, requiredLevels: [{ skill: SkillName.Woodcutting, level: 1 }] }, material: 'bronze', },
    { id: 'iron_axe', itemNum: 742, name: 'Iron Axe', description: 'A sturdy iron axe.', stackable: false, value: 90, iconUrl: 'wood-axe', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, stabAttack: -2, slashAttack: 5, crushAttack: 3, slashDefence: 1, strengthBonus: 7, weaponType: WeaponType.Axe, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], }, tool: { type: ToolType.Axe, power: 20, requiredLevels: [{ skill: SkillName.Woodcutting, level: 1 }] } },
    { id: 'steel_axe', itemNum: 743, name: 'Steel Axe', description: 'A well-balanced steel axe.', stackable: false, value: 220, iconUrl: 'wood-axe', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: -2, slashAttack: 8, crushAttack: 6, slashDefence: 1, strengthBonus: 9, weaponType: WeaponType.Axe, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], }, tool: { type: ToolType.Axe, power: 30, requiredLevels: [{ skill: SkillName.Woodcutting, level: 6 }] } },
    { id: 'mithril_axe', itemNum: 744, name: 'Mithril Axe', description: 'A well-balanced mithril axe.', stackable: false, value: 550, iconUrl: 'wood-axe', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Axe, speed: 4, stabAttack: -2, slashAttack: 12, crushAttack: 10, slashDefence: 1, strengthBonus: 15, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], }, tool: { type: ToolType.Axe, power: 60, requiredLevels: [{ skill: SkillName.Woodcutting, level: 21 }] } },
    { id: 'adamantite_axe', itemNum: 745, name: 'Adamantite Axe', description: 'A well-balanced adamantite axe.', stackable: false, value: 1100, iconUrl: 'wood-axe', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Axe, speed: 4, stabAttack: -2, slashAttack: 17, crushAttack: 15, slashDefence: 1, strengthBonus: 19, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], }, tool: { type: ToolType.Axe, power: 100, requiredLevels: [{ skill: SkillName.Woodcutting, level: 31 }] } },
    { id: 'runic_axe', itemNum: 746, name: 'Runic Axe', description: 'A well-balanced runic axe.', stackable: false, value: 12800, iconUrl: 'wood-axe', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Axe, speed: 4, stabAttack: -2, slashAttack: 26, crushAttack: 24, slashDefence: 1, strengthBonus: 29, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], }, tool: { type: ToolType.Axe, power: 160, requiredLevels: [{ skill: SkillName.Woodcutting, level: 41 }] } },

    // Pickaxes
    { id: 'bronze_pickaxe', itemNum: 747, name: 'Bronze Pickaxe', description: 'A simple pickaxe for mining rocks.', stackable: false, value: 10, iconUrl: 'war-pick', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 4, crushAttack: 2, strengthBonus: 5, weaponType: WeaponType.Pickaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], }, tool: { type: ToolType.Pickaxe, power: 10, requiredLevels: [{ skill: SkillName.Mining, level: 1 }] }, material: 'bronze', },
    { id: 'iron_pickaxe', itemNum: 748, name: 'Iron Pickaxe', description: 'A sturdy pickaxe for mining rocks.', stackable: false, value: 90, iconUrl: 'war-pick', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 6, slashAttack: -2, crushAttack: 3, strengthBonus: 7, weaponType: WeaponType.Pickaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], }, tool: { type: ToolType.Pickaxe, power: 20, requiredLevels: [{ skill: SkillName.Mining, level: 1 }] }, material: 'iron', },
    { id: 'steel_pickaxe', itemNum: 749, name: 'Steel Pickaxe', description: 'A strong steel pickaxe for mining rocks.', stackable: false, value: 220, iconUrl: 'war-pick', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 8, slashAttack: -2, crushAttack: 6, strengthBonus: 9, weaponType: WeaponType.Pickaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], }, tool: { type: ToolType.Pickaxe, power: 30, requiredLevels: [{ skill: SkillName.Mining, level: 6 }] } },
    { id: 'mithril_pickaxe', itemNum: 750, name: 'Mithril Pickaxe', description: 'A strong mithril pickaxe for mining rocks.', stackable: false, value: 550, iconUrl: 'war-pick', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 12, slashAttack: -2, crushAttack: 10, strengthBonus: 13, weaponType: WeaponType.Pickaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], }, tool: { type: ToolType.Pickaxe, power: 40, requiredLevels: [{ skill: SkillName.Mining, level: 21 }] } },
    { id: 'adamantite_pickaxe', itemNum: 751, name: 'Adamantite Pickaxe', description: 'A very strong adamantite pickaxe for mining rocks.', stackable: false, value: 1100, iconUrl: 'war-pick', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 17, slashAttack: -2, crushAttack: 15, strengthBonus: 19, weaponType: WeaponType.Pickaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], }, tool: { type: ToolType.Pickaxe, power: 50, requiredLevels: [{ skill: SkillName.Mining, level: 31 }] } },
    { id: 'runic_pickaxe', itemNum: 752, name: 'Runic Pickaxe', description: 'A powerful runic pickaxe for mining rocks.', stackable: false, value: 32000, iconUrl: 'war-pick', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 26, slashAttack: -2, crushAttack: 24, strengthBonus: 29, weaponType: WeaponType.Pickaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], }, tool: { type: ToolType.Pickaxe, power: 60, requiredLevels: [{ skill: SkillName.Mining, level: 41 }] } },
    { id: 'crystal_tipped_runic_pickaxe', itemNum: 753, name: 'Crystal-Tipped Runic Pickaxe', description: 'A Runic pickaxe, enhanced with a crystalline tip that never dulls.', stackable: false, value: 35000, iconUrl: 'war-pick', material: 'aquatite', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 38, slashAttack: -2, crushAttack: 32, strengthBonus: 36, weaponType: WeaponType.Pickaxe, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], }, tool: { type: ToolType.Pickaxe, power: 80, requiredLevels: [{ skill: SkillName.Mining, level: 51 }] } },

    // Gathering/Crafting Tools
    { id: 'tinderbox', itemNum: 754, name: 'Tinderbox', description: 'Used to light fires.', stackable: false, value: 1, iconUrl: 'matchbox' },
    { id: 'shears', itemNum: 755, name: 'Shears', description: 'Used for shearing sheep.', stackable: false, value: 10, iconUrl: 'shears' },
    { id: 'knife', itemNum: 756, name: 'Knife', description: 'A simple knife. Useful for fletching.', stackable: false, value: 5, iconUrl: 'bone-knife' },
    { id: 'hammer', itemNum: 757, name: 'Hammer', description: 'A standard smithing hammer.', stackable: false, value: 5, iconUrl: 'hammer-drop' },
    { id: 'chisel', itemNum: 758, name: 'Chisel', description: 'A sharp chisel for cutting gems.', stackable: false, value: 10, iconUrl: 'chisel' },
    { id: 'needle', itemNum: 759, name: 'Needle', description: 'A small needle for crafting.', stackable: false, value: 1, iconUrl: 'sewing-needle' },
    { id: 'thread', itemNum: 760, name: 'Thread', description: 'A spool of sturdy thread.', stackable: true, value: 1, iconUrl: 'sewing-string' },
    { id: 'tiara_mould', itemNum: 761, name: 'Tiara Mould', description: 'A mould for crafting tiaras from metal bars.', stackable: false, value: 5, iconUrl: 'tiara' },
    { id: 'ring_mould', itemNum: 762, name: 'Ring Mould', description: 'A mould for making rings.', stackable: false, value: 5, iconUrl: 'ring' },
    { id: 'necklace_mould', itemNum: 763, name: 'Necklace Mould', description: 'A mould for making necklaces.', stackable: false, value: 5, iconUrl: 'necklace' },
    { id: 'amulet_mould', itemNum: 764, name: 'Amulet Mould', description: 'A mould for making amulets.', stackable: false, value: 5, iconUrl: 'gem-pendant' },

    // Cooking Containers
    { id: 'bucket', itemNum: 765, name: 'Bucket', description: 'An empty bucket. Can be filled with water or milk.', stackable: false, value: 2, iconUrl: 'empty-wood-bucket', material: 'wood-normal' },
    { id: 'pie_dish', itemNum: 766, name: 'Pie Dish', description: 'An empty dish for making pies.', stackable: false, value: 4, iconUrl: 'meal' },
    { id: 'cake_tin', itemNum: 767, name: 'Cake Tin', description: 'An empty tin for baking cakes.', stackable: false, value: 4, iconUrl: 'round-silo' },

    // Fishing Tools
    { id: 'small_fishing_net', itemNum: 768, name: 'Small Fishing Net', description: 'A net for catching small fish like shrimp.', stackable: false, value: 15, iconUrl: 'fishing-net', tool: { type: ToolType.FishingNet, power: 5 } },
    { id: 'fishing_rod', itemNum: 769, name: 'Fishing Rod', description: 'A rod for catching fish with bait.', stackable: false, value: 20, iconUrl: 'fishing-pole', tool: { type: ToolType.FishingRod, power: 10 } },
    { id: 'fly_fishing_rod', itemNum: 770, name: 'Fly Fishing Rod', description: 'A rod for catching fish with feathers as lures.', stackable: false, value: 35, iconUrl: 'fishing-pole', tool: { type: ToolType.FlyFishingRod, power: 20 } },
    { id: 'basket_trap', itemNum: 771, name: 'Basket Trap', description: 'A woven basket for catching eels and other freshwater creatures.', stackable: false, value: 25, iconUrl: 'fishing-lure', tool: { type: ToolType.BasketTrap, power: 15 } },
    { id: 'harpoon', itemNum: 772, name: 'Harpoon', description: 'A heavy spear for catching large sea creatures.', stackable: false, value: 75, iconUrl: 'harpoon-chain', tool: { type: ToolType.Harpoon, power: 30 } },
    { id: 'ocean_box_trap', itemNum: 773, name: 'Ocean Box Trap', description: 'A sturdy baited cage for catching lobsters and crabs.', stackable: false, value: 40, iconUrl: 'cage', tool: { type: ToolType.OceanBoxTrap, power: 25 } },

    // Fishing Baits
    { id: 'feathers', itemNum: 774, name: 'Feathers', description: 'A soft feather of an avian.', stackable: true, value: 1, iconUrl: 'feather' },
    { id: 'fishing_bait', itemNum: 775, name: 'Fishing Bait', description: 'A wriggling worm, perfect for catching fish.', stackable: true, value: 1, iconUrl: 'worms' },

    //Herblore Tools
    { id: 'pestle_and_mortar', itemNum: 776, name: 'Pestle and Mortar', description: 'Used to grind ingredients for Herblore.', stackable: false, value: 100, iconUrl: 'apothecary' },

    // Thieving Tools
    { id: 'bobby_pin', itemNum: 777, name: 'Bobby Pin', description: 'A thin piece of metal, suitable for simple locks.', stackable: false, value: 5, iconUrl: 'safety-pin', lockpick: { level: 1, breakChance: 0.5, power: 0 } },
    { id: 'lockpick', itemNum: 778, name: 'Lockpick', description: 'A sturdy iron lockpick for more complex locks.', stackable: false, value: 50, iconUrl: 'lockpicks', lockpick: { level: 20, breakChance: 0.2, power: 5 } },
    { id: 'diamond_lockpick', itemNum: 779, name: 'Diamond Lockpick', description: 'A masterfully crafted lockpick with a diamond tip. Very durable.', stackable: false, value: 5000, iconUrl: 'lockpicks', material: 'diamond', lockpick: { level: 50, breakChance: 0.05, power: 10 } },
    { id: 'skeleton_key', itemNum: 780, name: 'Skeleton Key', description: 'An ancient, unbreakable key said to open any lock.', stackable: false, value: 100000, iconUrl: 'skeleton-key', lockpick: { level: 80, breakChance: 0, unbreakable: true, power: 15 } },

    // Glassblowing
    { id: 'glassblowing_apparatus', itemNum: 781, name: 'Glassblowing Apparatus', description: 'A pipe used for shaping molten glass.', stackable: false, value: 50, iconUrl: 'bagpipes' },
];