import { Item, EquipmentSlot, SkillName, WeaponType, ToolType } from '../../types';

export const tools: Item[] = [
    // Axes
    { id: 'bronze_axe', name: 'Bronze Axe', description: 'A simple bronze axe, mainly used for chopping trees.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:wood-axe.svg', equipment: { slot: EquipmentSlot.Weapon, slashAttack: 2, crushAttack: 1, strengthBonus: 3, weaponType: WeaponType.Axe, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], }, tool: { type: ToolType.Axe, power: 10, requiredLevels: [{ skill: SkillName.Woodcutting, level: 1 }] }, material: 'bronze', },
    { id: 'iron_axe', name: 'Iron Axe', description: 'A sturdy iron axe.', stackable: false, value: 90, iconUrl: 'https://api.iconify.design/game-icons:wood-axe.svg', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, stabAttack: -2, slashAttack: 8, crushAttack: 6, slashDefence: 1, strengthBonus: 9, weaponType: WeaponType.Axe, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], }, tool: { type: ToolType.Axe, power: 20, requiredLevels: [{ skill: SkillName.Woodcutting, level: 1 }] } },
    { id: 'steel_axe', name: 'Steel Axe', description: 'A well-balanced steel axe.', stackable: false, value: 220, iconUrl: 'https://api.iconify.design/game-icons:wood-axe.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: -2, slashAttack: 12, crushAttack: 8, slashDefence: 1, strengthBonus: 13, weaponType: WeaponType.Axe, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], }, tool: { type: ToolType.Axe, power: 30, requiredLevels: [{ skill: SkillName.Woodcutting, level: 6 }] } },
    { id: 'mithril_axe', name: 'Mithril Axe', description: 'A well-balanced mithril axe.', stackable: false, value: 550, iconUrl: 'https://api.iconify.design/game-icons:wood-axe.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Axe, speed: 4, stabAttack: -2, slashAttack: 18, crushAttack: 14, slashDefence: 1, strengthBonus: 20, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], }, tool: { type: ToolType.Axe, power: 60, requiredLevels: [{ skill: SkillName.Woodcutting, level: 21 }] } },
    { id: 'adamantite_axe', name: 'Adamantite Axe', description: 'A well-balanced adamantite axe.', stackable: false, value: 1100, iconUrl: 'https://api.iconify.design/game-icons:wood-axe.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Axe, speed: 4, stabAttack: -2, slashAttack: 25, crushAttack: 18, slashDefence: 1, strengthBonus: 26, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], }, tool: { type: ToolType.Axe, power: 100, requiredLevels: [{ skill: SkillName.Woodcutting, level: 31 }] } },
    { id: 'runic_axe', name: 'Runic Axe', description: 'A well-balanced runic axe.', stackable: false, value: 12800, iconUrl: 'https://api.iconify.design/game-icons:wood-axe.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Axe, speed: 4, stabAttack: -2, slashAttack: 33, crushAttack: 24, slashDefence: 1, strengthBonus: 35, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], }, tool: { type: ToolType.Axe, power: 160, requiredLevels: [{ skill: SkillName.Woodcutting, level: 41 }] } },

    // Pickaxes
    { id: 'bronze_pickaxe', name: 'Bronze Pickaxe', description: 'A simple pickaxe for mining rocks.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:war-pick.svg', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 2, crushAttack: 1, strengthBonus: 3, weaponType: WeaponType.Unarmed, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], }, tool: { type: ToolType.Pickaxe, power: 10, requiredLevels: [{ skill: SkillName.Mining, level: 1 }] }, material: 'bronze', },
    { id: 'iron_pickaxe', name: 'Iron Pickaxe', description: 'A sturdy pickaxe for mining rocks.', stackable: false, value: 90, iconUrl: 'https://api.iconify.design/game-icons:war-pick.svg', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 4, slashAttack: -2, crushAttack: 2, strengthBonus: 5, weaponType: WeaponType.Unarmed, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], }, tool: { type: ToolType.Pickaxe, power: 20, requiredLevels: [{ skill: SkillName.Mining, level: 1 }] }, material: 'iron', },
    { id: 'steel_pickaxe', name: 'Steel Pickaxe', description: 'A strong steel pickaxe for mining rocks.', stackable: false, value: 220, iconUrl: 'https://api.iconify.design/game-icons:war-pick.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 6, slashAttack: -2, crushAttack: 3, strengthBonus: 7, weaponType: WeaponType.Unarmed, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], }, tool: { type: ToolType.Pickaxe, power: 30, requiredLevels: [{ skill: SkillName.Mining, level: 6 }] } },
    { id: 'mithril_pickaxe', name: 'Mithril Pickaxe', description: 'A strong mithril pickaxe for mining rocks.', stackable: false, value: 550, iconUrl: 'https://api.iconify.design/game-icons:war-pick.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 6, slashAttack: -2, crushAttack: 3, strengthBonus: 8, weaponType: WeaponType.Unarmed, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], }, tool: { type: ToolType.Pickaxe, power: 40, requiredLevels: [{ skill: SkillName.Mining, level: 21 }] } },
    { id: 'adamantite_pickaxe', name: 'Adamantite Pickaxe', description: 'A very strong adamantite pickaxe for mining rocks.', stackable: false, value: 1100, iconUrl: 'https://api.iconify.design/game-icons:war-pick.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 9, slashAttack: -2, crushAttack: 4, strengthBonus: 12, weaponType: WeaponType.Unarmed, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], }, tool: { type: ToolType.Pickaxe, power: 50, requiredLevels: [{ skill: SkillName.Mining, level: 31 }] } },
    { id: 'runic_pickaxe', name: 'Runic Pickaxe', description: 'A powerful runic pickaxe for mining rocks.', stackable: false, value: 32000, iconUrl: 'https://api.iconify.design/game-icons:war-pick.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 12, slashAttack: -2, crushAttack: 5, strengthBonus: 16, weaponType: WeaponType.Unarmed, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], }, tool: { type: ToolType.Pickaxe, power: 60, requiredLevels: [{ skill: SkillName.Mining, level: 41 }] } },
    { id: 'crystal_tipped_runic_pickaxe', name: 'Crystal-Tipped Runic Pickaxe', description: 'A Runic pickaxe, enhanced with a crystalline tip that never dulls.', stackable: false, value: 35000, iconUrl: 'https://api.iconify.design/game-icons:war-pick.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 15, slashAttack: -2, crushAttack: 6, strengthBonus: 18, weaponType: WeaponType.Unarmed, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], }, tool: { type: ToolType.Pickaxe, power: 80, requiredLevels: [{ skill: SkillName.Mining, level: 51 }] } },
 
    // Gathering/Crafting Tools
    { id: 'tinderbox', name: 'Tinderbox', description: 'Used to light fires.', stackable: false, value: 1, iconUrl: 'https://api.iconify.design/game-icons:matchbox.svg' },
    { id: 'shears', name: 'Shears', description: 'Used for shearing sheep.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:shears.svg' },
    { id: 'knife', name: 'Knife', description: 'A simple knife. Useful for fletching.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:bone-knife.svg' },
    { id: 'hammer', name: 'Hammer', description: 'A standard smithing hammer.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:hammer-drop.svg' },
    { id: 'chisel', name: 'Chisel', description: 'A sharp chisel for cutting gems.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:chisel.svg' },
    { id: 'needle', name: 'Needle', description: 'A small needle for crafting.', stackable: false, value: 1, iconUrl: 'https://api.iconify.design/game-icons:sewing-needle.svg' },
    { id: 'thread', name: 'Thread', description: 'A spool of sturdy thread.', stackable: true, value: 1, iconUrl: 'https://api.iconify.design/game-icons:sewing-string.svg' },
    { id: 'tiara_mould', name: 'Tiara Mould', description: 'A mould for crafting tiaras from metal bars.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg' },
    { id: 'ring_mould', name: 'Ring Mould', description: 'A mould for making rings.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:ring.svg' },
    { id: 'necklace_mould', name: 'Necklace Mould', description: 'A mould for making necklaces.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg' },
    { id: 'amulet_mould', name: 'Amulet Mould', description: 'A mould for making amulets.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg' },

    // Cooking Containers
    { id: 'bucket', name: 'Bucket', description: 'An empty bucket. Can be filled with water or milk.', stackable: false, value: 2, iconUrl: 'https://api.iconify.design/game-icons:full-wood-bucket.svg', material: 'wood-normal' },
    { id: 'pie_dish', name: 'Pie Dish', description: 'An empty dish for making pies.', stackable: false, value: 4, iconUrl: 'https://api.iconify.design/game-icons:meal.svg' },
    { id: 'cake_tin', name: 'Cake Tin', description: 'An empty tin for baking cakes.', stackable: false, value: 4, iconUrl: 'https://api.iconify.design/game-icons:round-silo.svg' },
 
    // Fishing Tools
    { id: 'small_fishing_net', name: 'Small Fishing Net', description: 'A net for catching small fish like shrimp.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:fishing-net.svg', tool: { type: ToolType.FishingNet, power: 5 } },
    { id: 'fishing_rod', name: 'Fishing Rod', description: 'A rod for catching fish with bait.', stackable: false, value: 20, iconUrl: 'https://api.iconify.design/game-icons:fishing-pole.svg', tool: { type: ToolType.FishingRod, power: 10 } },
    { id: 'fly_fishing_rod', name: 'Fly Fishing Rod', description: 'A rod for catching fish with feathers as lures.', stackable: false, value: 35, iconUrl: 'https://api.iconify.design/game-icons:fishing-pole.svg', tool: { type: ToolType.FlyFishingRod, power: 20 } },
    { id: 'basket_trap', name: 'Basket Trap', description: 'A woven basket for catching eels and other freshwater creatures.', stackable: false, value: 25, iconUrl: 'https://api.iconify.design/game-icons:fishing-lure.svg', tool: { type: ToolType.BasketTrap, power: 15 } },
    { id: 'harpoon', name: 'Harpoon', description: 'A heavy spear for catching large sea creatures.', stackable: false, value: 75, iconUrl: 'https://api.iconify.design/game-icons:harpoon-chain.svg', tool: { type: ToolType.Harpoon, power: 30 } },
    { id: 'ocean_box_trap', name: 'Ocean Box Trap', description: 'A sturdy baited cage for catching lobsters and crabs.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:cage.svg', tool: { type: ToolType.OceanBoxTrap, power: 25 } },

    // Fishing Baits
    { id: 'feathers', name: 'Feathers', description: 'A soft feather of an avian.', stackable: true, value: 1, iconUrl: 'https://api.iconify.design/game-icons:feather.svg' },
    { id: 'fishing_bait', name: 'Fishing Bait', description: 'A wriggling worm, perfect for catching fish.', stackable: true, value: 1, iconUrl: 'https://api.iconify.design/game-icons:worms.svg' },

    //Herblore Tools
    { id: 'pestle_and_mortar', name: 'Pestle and Mortar', description: 'Used to grind ingredients for Herblore.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:apothecary.svg' },

    // Thieving Tools
    { id: 'bobby_pin', name: 'Bobby Pin', description: 'A thin piece of metal, suitable for simple locks.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:safety-pin.svg', lockpick: { level: 1, breakChance: 0.5, power: 0} },
    { id: 'lockpick', name: 'Lockpick', description: 'A sturdy iron lockpick for more complex locks.', stackable: false, value: 50, iconUrl: 'https://api.iconify.design/game-icons:lockpicks.svg', lockpick: { level: 20, breakChance: 0.2, power: 5 } },
    { id: 'diamond_lockpick', name: 'Diamond Lockpick', description: 'A masterfully crafted lockpick with a diamond tip. Very durable.', stackable: false, value: 5000, iconUrl: 'https://api.iconify.design/game-icons:lockpicks.svg', material: 'diamond', lockpick: { level: 50, breakChance: 0.05, power: 10 } },
    { id: 'skeleton_key', name: 'Skeleton Key', description: 'An ancient, unbreakable key said to open any lock.', stackable: false, value: 100000, iconUrl: 'https://api.iconify.design/game-icons:skeleton-key.svg', lockpick: { level: 80, breakChance: 0, unbreakable: true, power: 15 } },

    // Glassblowing
    { id: 'glassblowing_apparatus', name: 'Glassblowing Apparatus', description: 'A pipe used for shaping molten glass.', stackable: false, value: 50, iconUrl: 'https://api.iconify.design/game-icons:glass-pipe.svg' },
];