import { Item, EquipmentSlot, WeaponType, SkillName } from '../../types';

export const weaponsAndTools: Item[] = [
    // Weapons
    { id: 'bronze_dagger', name: 'Bronze Dagger', description: 'A short, sharp dagger. Very fast.', stackable: false, value: 12, iconUrl: 'https://api.iconify.design/game-icons:stiletto.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 4, slashAttack: 2, crushAttack: -4, strengthBonus: 2, weaponType: WeaponType.Dagger, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], } },
    { id: 'iron_dagger', name: 'Iron Dagger', description: 'A sharp iron dagger.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:stiletto.svg', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 7, slashAttack: 4, crushAttack: -4, strengthBonus: 6, weaponType: WeaponType.Dagger, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], } },
    { id: 'steel_dagger', name: 'Steel Dagger', description: 'A sharp steel dagger.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:stiletto.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 10, slashAttack: 6, crushAttack: -4, strengthBonus: 9, weaponType: WeaponType.Dagger, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], } },
    { id: 'mithril_dagger', name: 'Mithril Dagger', description: 'A sharp mithril dagger.', stackable: false, value: 500, iconUrl: 'https://api.iconify.design/game-icons:stiletto.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Dagger, speed: 4, stabAttack: 15, slashAttack: 9, crushAttack: -4, strengthBonus: 14, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], } },
    { id: 'adamantite_dagger', name: 'Adamantite Dagger', description: 'A sharp adamantite dagger.', stackable: false, value: 1000, iconUrl: 'https://api.iconify.design/game-icons:stiletto.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Dagger, speed: 4, stabAttack: 22, slashAttack: 14, crushAttack: -4, strengthBonus: 20, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], } },
    { id: 'runic_dagger', name: 'Runic Dagger', description: 'A sharp runic dagger.', stackable: false, value: 8000, iconUrl: 'https://api.iconify.design/game-icons:stiletto.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Dagger, speed: 4, stabAttack: 30, slashAttack: 20, crushAttack: -4, strengthBonus: 28, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], } },
    { id: 'bronze_sword', name: 'Bronze Sword', description: 'A basic sword made of bronze.', stackable: false, value: 20, iconUrl: 'https://api.iconify.design/game-icons:broadsword.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 3, slashAttack: 5, crushAttack: -2, slashDefence: 1, strengthBonus: 4, weaponType: WeaponType.Sword, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], } },
    { id: 'iron_sword', name: 'Iron Sword', description: 'A well-balanced sword, restored from a rusty relic.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:broadsword.svg', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 6, slashAttack: 8, crushAttack: -2, slashDefence: 2, crushDefence: 1, strengthBonus: 7, weaponType: WeaponType.Sword, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], } },
    { id: 'steel_sword', name: 'Steel Sword', description: 'A sword made of high quality steel.', stackable: false, value: 300, iconUrl: 'https://api.iconify.design/game-icons:broadsword.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 10, slashAttack: 14, crushAttack: -2, slashDefence: 3, crushDefence: 2, strengthBonus: 13, weaponType: WeaponType.Sword, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], } },
    { id: 'mithril_sword', name: 'Mithril Sword', description: 'A beautifully crafted sword made from lightweight mithril.', stackable: false, value: 750, iconUrl: 'https://api.iconify.design/game-icons:broadsword.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Sword, speed: 4, stabAttack: 18, slashAttack: 24, crushAttack: -2, slashDefence: 4, crushDefence: 3, strengthBonus: 22, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], } },
    { id: 'adamantite_sword', name: 'Adamantite Sword', description: 'A well-balanced adamantite sword.', stackable: false, value: 1500, iconUrl: 'https://api.iconify.design/game-icons:broadsword.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Sword, speed: 4, stabAttack: 24, slashAttack: 30, crushAttack: -2, slashDefence: 3, crushDefence: 2, strengthBonus: 28, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], } },
    { id: 'runic_sword', name: 'Runic Sword', description: 'A powerful and well-balanced runic sword.', stackable: false, value: 20800, iconUrl: 'https://api.iconify.design/game-icons:broadsword.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Sword, speed: 4, stabAttack: 32, slashAttack: 40, crushAttack: -2, slashDefence: 4, crushDefence: 3, strengthBonus: 38, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], } },
    { id: 'aquatite_sword', name: 'Aquatite Sword', description: 'A beautifully crafted sword that seems to ripple like water.', stackable: false, value: 85000, iconUrl: 'https://api.iconify.design/game-icons:broadsword.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 58, slashAttack: 62, crushAttack: -2, slashDefence: 3, crushDefence: 2, strengthBonus: 60, weaponType: WeaponType.Sword, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 60 }], } },
    { id: 'bronze_scimitar', name: 'Bronze Scimitar', description: 'A curved blade that sacrifices defence for power.', stackable: false, value: 22, iconUrl: 'https://api.iconify.design/game-icons:curvy-knife.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 1, slashAttack: 5, crushAttack: -2, strengthBonus: 6, weaponType: WeaponType.Scimitar, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], } },
    { id: 'iron_scimitar', name: 'Iron Scimitar', description: 'A sharp, curved iron blade.', stackable: false, value: 140, iconUrl: 'https://api.iconify.design/game-icons:curvy-knife.svg', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 2, slashAttack: 9, crushAttack: -2, slashDefence: 1, strengthBonus: 11, weaponType: WeaponType.Scimitar, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], } },
    { id: 'steel_scimitar', name: 'Steel Scimitar', description: 'A sharp, curved steel blade.', stackable: false, value: 340, iconUrl: 'https://api.iconify.design/game-icons:curvy-knife.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 3, slashAttack: 13, crushAttack: -2, slashDefence: 1, strengthBonus: 16, weaponType: WeaponType.Scimitar, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], } },
    { id: 'mithril_scimitar', name: 'Mithril Scimitar', description: 'A sharp, curved mithril blade.', stackable: false, value: 850, iconUrl: 'https://api.iconify.design/game-icons:curvy-knife.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Scimitar, speed: 4, stabAttack: 5, slashAttack: 20, crushAttack: -2, slashDefence: 1, strengthBonus: 24, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], } },
    { id: 'adamantite_scimitar', name: 'Adamantite Scimitar', description: 'A sharp, curved adamantite blade.', stackable: false, value: 1700, iconUrl: 'https://api.iconify.design/game-icons:curvy-knife.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Scimitar, speed: 4, stabAttack: 7, slashAttack: 28, crushAttack: -2, slashDefence: 1, strengthBonus: 32, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], } },
    { id: 'runic_scimitar', name: 'Runic Scimitar', description: 'A sharp, curved runic blade.', stackable: false, value: 25600, iconUrl: 'https://api.iconify.design/game-icons:curvy-knife.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Scimitar, speed: 4, stabAttack: 10, slashAttack: 38, crushAttack: -2, slashDefence: 1, strengthBonus: 42, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], } },
    { id: 'bronze_mace', name: 'Bronze Mace', description: 'A blunt-force weapon. Slow but accurate.', stackable: false, value: 14, iconUrl: 'https://api.iconify.design/game-icons:flanged-mace.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 2, slashAttack: -2, crushAttack: 6, strengthBonus: 4, weaponType: WeaponType.Mace, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], } },
    { id: 'iron_mace', name: 'Iron Mace', description: 'A heavy iron mace.', stackable: false, value: 95, iconUrl: 'https://api.iconify.design/game-icons:flanged-mace.svg', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 4, slashAttack: -2, crushAttack: 10, strengthBonus: 8, weaponType: WeaponType.Mace, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], } },
    { id: 'steel_mace', name: 'Steel Mace', description: 'A heavy steel mace.', stackable: false, value: 230, iconUrl: 'https://api.iconify.design/game-icons:flanged-mace.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 6, slashAttack: -2, crushAttack: 15, strengthBonus: 12, weaponType: WeaponType.Mace, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], } },
    { id: 'mithril_mace', name: 'Mithril Mace', description: 'A heavy mithril mace.', stackable: false, value: 575, iconUrl: 'https://api.iconify.design/game-icons:flanged-mace.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Mace, speed: 4, stabAttack: 9, slashAttack: -2, crushAttack: 22, strengthBonus: 20, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], } },
    { id: 'adamantite_mace', name: 'Adamantite Mace', description: 'A heavy adamantite mace.', stackable: false, value: 1150, iconUrl: 'https://api.iconify.design/game-icons:flanged-mace.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Mace, speed: 4, stabAttack: 12, slashAttack: -2, crushAttack: 32, strengthBonus: 26, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], } },
    { id: 'runic_mace', name: 'Runic Mace', description: 'A heavy runic mace.', stackable: false, value: 14400, iconUrl: 'https://api.iconify.design/game-icons:flanged-mace.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, weaponType: WeaponType.Mace, speed: 4, stabAttack: 18, slashAttack: -2, crushAttack: 42, strengthBonus: 35, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], } },
    { id: 'bronze_warhammer', name: 'Bronze Warhammer', description: 'A heavy bronze warhammer. Slow, but hits hard.', stackable: false, value: 26, iconUrl: 'https://api.iconify.design/game-icons:warhammer.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, stabAttack: -4, slashAttack: -4, crushAttack: 12, strengthBonus: 14, weaponType: WeaponType.Warhammer, speed: 5, requiredLevels: [{ skill: SkillName.Strength, level: 1 }], } },
    { id: 'iron_warhammer', name: 'Iron Warhammer', description: 'A heavy iron warhammer. Slow, but hits very hard.', stackable: false, value: 180, iconUrl: 'https://api.iconify.design/game-icons:warhammer.svg', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, stabAttack: -4, slashAttack: -4, crushAttack: 22, strengthBonus: 28, weaponType: WeaponType.Warhammer, speed: 5, requiredLevels: [{ skill: SkillName.Strength, level: 5 }], } },
    { id: 'steel_warhammer', name: 'Steel Warhammer', description: 'A formidable steel warhammer. Slow, but crushes armor effectively.', stackable: false, value: 420, iconUrl: 'https://api.iconify.design/game-icons:warhammer.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, stabAttack: -4, slashAttack: -4, crushAttack: 35, strengthBonus: 40, weaponType: WeaponType.Warhammer, speed: 5, requiredLevels: [{ skill: SkillName.Strength, level: 10 }], } },
    { id: 'mithril_warhammer', name: 'Mithril Warhammer', description: 'A formidable mithril warhammer.', stackable: false, value: 1050, iconUrl: 'https://api.iconify.design/game-icons:warhammer.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, weaponType: WeaponType.Warhammer, speed: 5, stabAttack: -4, slashAttack: -4, crushAttack: 42, strengthBonus: 48, requiredLevels: [{ skill: SkillName.Strength, level: 20 }], } },
    { id: 'adamantite_warhammer', name: 'Adamantite Warhammer', description: 'A formidable adamantite warhammer.', stackable: false, value: 2100, iconUrl: 'https://api.iconify.design/game-icons:warhammer.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, weaponType: WeaponType.Warhammer, speed: 5, stabAttack: -4, slashAttack: -4, crushAttack: 52, strengthBonus: 58, requiredLevels: [{ skill: SkillName.Strength, level: 30 }], } },
    { id: 'runic_warhammer', name: 'Runic Warhammer', description: 'A formidable runic warhammer.', stackable: false, value: 41800, iconUrl: 'https://api.iconify.design/game-icons:warhammer.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, weaponType: WeaponType.Warhammer, speed: 5, stabAttack: -4, slashAttack: -4, crushAttack: 68, strengthBonus: 72, requiredLevels: [{ skill: SkillName.Strength, level: 40 }], } },
    { id: 'bronns_warhammer', name: 'Bronn\'s Warhammer', description: 'A very dense warhammer, that feels exceptionally sturdy and an almost perfect fit for your hands.', stackable: false, value: 2500, iconUrl: 'https://api.iconify.design/game-icons:warhammer.svg', material: 'burnt', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, weaponType: WeaponType.Warhammer, speed: 5, stabAttack: -4, slashAttack: -4, crushAttack: 46, strengthBonus: 52, requiredLevels: [{ skill: SkillName.Strength, level: 20 }], } },
    { id: 'bronze_battleaxe', name: 'Bronze Battleaxe', description: 'A heavy, two-handed axe. Slow but powerful.', stackable: false, value: 28, iconUrl: 'https://api.iconify.design/game-icons:battle-axe.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, stabAttack: -2, slashAttack: 7, crushAttack: 5, strengthBonus: 8, weaponType: WeaponType.Battleaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 1 }], } },
    { id: 'iron_battleaxe', name: 'Iron Battleaxe', description: 'A powerful iron battleaxe.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:battle-axe.svg', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, stabAttack: -2, slashAttack: 12, crushAttack: 10, strengthBonus: 14, weaponType: WeaponType.Battleaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 5 }], } },
    { id: 'steel_battleaxe', name: 'Steel Battleaxe', description: 'A powerful steel battleaxe.', stackable: false, value: 480, iconUrl: 'https://api.iconify.design/game-icons:battle-axe.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, stabAttack: -2, slashAttack: 17, crushAttack: 15, strengthBonus: 19, weaponType: WeaponType.Battleaxe, speed: 5, requiredLevels: [{ skill: SkillName.Attack, level: 10 }], } },
    { id: 'mithril_battleaxe', name: 'Mithril Battleaxe', description: 'A powerful mithril battleaxe.', stackable: false, value: 1200, iconUrl: 'https://api.iconify.design/game-icons:battle-axe.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, weaponType: WeaponType.Battleaxe, speed: 5, stabAttack: -2, slashAttack: 26, crushAttack: 23, strengthBonus: 28, requiredLevels: [{ skill: SkillName.Attack, level: 20 }], } },
    { id: 'adamantite_battleaxe', name: 'Adamantite Battleaxe', description: 'A powerful adamantite battleaxe.', stackable: false, value: 2400, iconUrl: 'https://api.iconify.design/game-icons:battle-axe.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, weaponType: WeaponType.Battleaxe, speed: 5, stabAttack: -2, slashAttack: 36, crushAttack: 32, strengthBonus: 38, requiredLevels: [{ skill: SkillName.Attack, level: 30 }], } },
    { id: 'runic_battleaxe', name: 'Runic Battleaxe', description: 'A powerful runic battleaxe.', stackable: false, value: 41600, iconUrl: 'https://api.iconify.design/game-icons:battle-axe.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, weaponType: WeaponType.Battleaxe, speed: 5, stabAttack: -2, slashAttack: 48, crushAttack: 42, strengthBonus: 50, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], } },
    { id: 'bandit_leaders_cutlass', name: 'Bandit Leader\'s Cutlass', description: 'A well-used but high-quality steel scimitar. Faster than a standard scimitar.', stackable: false, value: 500, iconUrl: 'https://api.iconify.design/game-icons:curvy-knife.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 4, slashAttack: 25, crushAttack: -2, strengthBonus: 30, weaponType: WeaponType.Scimitar, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 25 }], } },
    { id: 'trident_of_the_depths', name: 'Trident of the Depths', description: 'A powerful trident recovered from the Sunken Labyrinth. It hums with an ancient, watery energy.', stackable: false, value: 28000, iconUrl: 'https://api.iconify.design/game-icons:trident.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, stabAttack: 55, slashAttack: 25, crushAttack: 10, strengthBonus: 48, weaponType: WeaponType.Spear, speed: 4, requiredLevels: [{ skill: SkillName.Attack, level: 40 }], } },
    { id: 'shortbow', name: 'Shortbow', description: 'A basic wooden shortbow.', stackable: false, value: 50, iconUrl: 'https://api.iconify.design/game-icons:high-shot.svg', material: 'wood-normal', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 8, weaponType: WeaponType.Bow, speed: 4, requiredLevels: [{ skill: SkillName.Ranged, level: 1 }], ammoTier: 'iron' } },
    { id: 'longbow', name: 'Longbow', description: 'A basic wooden longbow. Slower but more accurate than a shortbow.', stackable: false, value: 60, iconUrl: 'https://api.iconify.design/game-icons:pocket-bow.svg', material: 'wood-normal', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 10, weaponType: WeaponType.Bow, speed: 5, requiredLevels: [{ skill: SkillName.Ranged, level: 1 }], ammoTier: 'iron' } },
    { id: 'oak_shortbow', name: 'Oak Shortbow', description: 'A shortbow made from oak.', stackable: false, value: 90, iconUrl: 'https://api.iconify.design/game-icons:high-shot.svg', material: 'wood-oak', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 14, weaponType: WeaponType.Bow, speed: 4, requiredLevels: [{ skill: SkillName.Ranged, level: 10 }], ammoTier: 'steel' } },
    { id: 'oak_longbow', name: 'Oak Longbow', description: 'A longbow made from oak.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:pocket-bow.svg', material: 'wood-oak', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 18, weaponType: WeaponType.Bow, speed: 5, requiredLevels: [{ skill: SkillName.Ranged, level: 10 }], ammoTier: 'steel' } },
    { id: 'willow_shortbow', name: 'Willow Shortbow', description: 'A shortbow made from willow.', stackable: false, value: 180, iconUrl: 'https://api.iconify.design/game-icons:high-shot.svg', material: 'wood-willow', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 20, weaponType: WeaponType.Bow, speed: 4, requiredLevels: [{ skill: SkillName.Ranged, level: 20 }], ammoTier: 'mithril' } },
    { id: 'willow_longbow', name: 'Willow Longbow', description: 'A longbow made from willow.', stackable: false, value: 240, iconUrl: 'https://api.iconify.design/game-icons:pocket-bow.svg', material: 'wood-willow', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 26, weaponType: WeaponType.Bow, speed: 5, requiredLevels: [{ skill: SkillName.Ranged, level: 20 }], ammoTier: 'mithril' } },
    { id: 'feywood_shortbow', name: 'Feywood Shortbow', description: 'A magical shortbow made from feywood.', stackable: false, value: 300, iconUrl: 'https://api.iconify.design/game-icons:high-shot.svg', material: 'wood-feywood', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 28, weaponType: WeaponType.Bow, speed: 4, requiredLevels: [{ skill: SkillName.Ranged, level: 30 }], ammoTier: 'adamantite' } },
    { id: 'feywood_longbow', name: 'Feywood Longbow', description: 'A magical longbow made from feywood.', stackable: false, value: 360, iconUrl: 'https://api.iconify.design/game-icons:pocket-bow.svg', material: 'wood-feywood', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 36, weaponType: WeaponType.Bow, speed: 5, requiredLevels: [{ skill: SkillName.Ranged, level: 30 }], ammoTier: 'adamantite' } },
    { id: 'yew_shortbow', name: 'Yew Shortbow', description: 'A shortbow made from yew.', stackable: false, value: 450, iconUrl: 'https://api.iconify.design/game-icons:high-shot.svg', material: 'wood-yew', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 42, weaponType: WeaponType.Bow, speed: 4, requiredLevels: [{ skill: SkillName.Ranged, level: 40 }], ammoTier: 'runic' } },
    { id: 'yew_longbow', name: 'Yew Longbow', description: 'A longbow made from yew.', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:pocket-bow.svg', material: 'wood-yew', equipment: { slot: EquipmentSlot.Weapon, isTwoHanded: true, rangedAttack: 50, weaponType: WeaponType.Bow, speed: 5, requiredLevels: [{ skill: SkillName.Ranged, level: 40 }], ammoTier: 'runic' } },
    // Staves
    {
        id: 'staff', name: 'Staff', description: 'A basic wooden staff.', stackable: false, value: 100,
        iconUrl: 'https://api.iconify.design/game-icons:wizard-staff.svg', material: 'wood-normal',
        equipment: {
            slot: EquipmentSlot.Weapon, weaponType: WeaponType.Staff, speed: 4,
            stabAttack: 2, slashAttack: 2, crushAttack: 7, magicAttack: 4,
            stabDefence: 2, slashDefence: 3, crushDefence: 1, magicDefence: 2,
            strengthBonus: 3,
            requiredLevels: [{ skill: SkillName.Attack, level: 1 }],
        }
    },
    {
        id: 'staff_of_gusts', name: 'Staff of Gusts', description: 'A magical staff that provides an infinite supply of Gust runes.', stackable: false, value: 2000,
        iconUrl: 'https://api.iconify.design/game-icons:wizard-staff.svg', material: 'rune-gust',
        equipment: {
            slot: EquipmentSlot.Weapon, weaponType: WeaponType.Staff, speed: 4,
            stabAttack: 2, slashAttack: 2, crushAttack: 7, magicAttack: 10,
            stabDefence: 2, slashDefence: 3, crushDefence: 1, magicDefence: 4,
            strengthBonus: 3,
            requiredLevels: [{ skill: SkillName.Attack, level: 1 }, { skill: SkillName.Magic, level: 1 }],
            providesRune: 'gust_rune'
        }
    },
    {
        id: 'staff_of_aqua', name: 'Staff of Aqua', description: 'A magical staff that provides an infinite supply of Aqua runes.', stackable: false, value: 2000,
        iconUrl: 'https://api.iconify.design/game-icons:wizard-staff.svg', material: 'rune-aqua',
        equipment: {
            slot: EquipmentSlot.Weapon, weaponType: WeaponType.Staff, speed: 4,
            stabAttack: 2, slashAttack: 2, crushAttack: 7, magicAttack: 10,
            stabDefence: 2, slashDefence: 3, crushDefence: 1, magicDefence: 4,
            strengthBonus: 3,
            requiredLevels: [{ skill: SkillName.Attack, level: 1 }, { skill: SkillName.Magic, level: 1 }],
            providesRune: 'aqua_rune'
        }
    },
    {
        id: 'staff_of_stone', name: 'Staff of Stone', description: 'A magical staff that provides an infinite supply of Stone runes.', stackable: false, value: 2000,
        iconUrl: 'https://api.iconify.design/game-icons:wizard-staff.svg', material: 'rune-stone',
        equipment: {
            slot: EquipmentSlot.Weapon, weaponType: WeaponType.Staff, speed: 4,
            stabAttack: 2, slashAttack: 2, crushAttack: 7, magicAttack: 10,
            stabDefence: 2, slashDefence: 3, crushDefence: 1, magicDefence: 4,
            strengthBonus: 3,
            requiredLevels: [{ skill: SkillName.Attack, level: 1 }, { skill: SkillName.Magic, level: 1 }],
            providesRune: 'stone_rune'
        }
    },
    {
        id: 'staff_of_ember', name: 'Staff of Ember', description: 'A magical staff that provides an infinite supply of Ember runes.', stackable: false, value: 2000,
        iconUrl: 'https://api.iconify.design/game-icons:wizard-staff.svg', material: 'rune-ember',
        equipment: {
            slot: EquipmentSlot.Weapon, weaponType: WeaponType.Staff, speed: 4,
            stabAttack: 2, slashAttack: 2, crushAttack: 7, magicAttack: 10,
            stabDefence: 2, slashDefence: 3, crushDefence: 1, magicDefence: 4,
            strengthBonus: 3,
            requiredLevels: [{ skill: SkillName.Attack, level: 1 }, { skill: SkillName.Magic, level: 1 }],
            providesRune: 'ember_rune'
        }
    },
    // Ammo
    { id: 'bronze_arrow', name: 'Bronze Arrow', description: 'A bronze-tipped arrow.', stackable: true, value: 3, iconUrl: 'https://api.iconify.design/game-icons:broadhead-arrow.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 7, weaponType: WeaponType.Arrow } },
    { id: 'iron_arrow', name: 'Iron Arrow', description: 'An iron-tipped arrow.', stackable: true, value: 6, iconUrl: 'https://api.iconify.design/game-icons:broadhead-arrow.svg', material: 'iron', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 10, weaponType: WeaponType.Arrow } },
    { id: 'steel_arrow', name: 'Steel Arrow', description: 'A steel-tipped arrow.', stackable: true, value: 12, iconUrl: 'https://api.iconify.design/game-icons:broadhead-arrow.svg', material: 'steel', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 16, weaponType: WeaponType.Arrow } },
    { id: 'mithril_arrow', name: 'Mithril Arrow', description: 'A mithril-tipped arrow.', stackable: true, value: 25, iconUrl: 'https://api.iconify.design/game-icons:broadhead-arrow.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 22, weaponType: WeaponType.Arrow } },
    { id: 'adamantite_arrow', name: 'Adamantite Arrow', description: 'An adamantite-tipped arrow.', stackable: true, value: 40, iconUrl: 'https://api.iconify.design/game-icons:broadhead-arrow.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 31, weaponType: WeaponType.Arrow } },
    { id: 'runic_arrow', name: 'Runic Arrow', description: 'A runic-tipped arrow.', stackable: true, value: 400, iconUrl: 'https://api.iconify.design/game-icons:broadhead-arrow.svg', material: 'runic', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 42, weaponType: WeaponType.Arrow } },
    // Crossbows
    { id: 'bronze_crossbow', name: 'Bronze Crossbow', description: 'A simple bronze crossbow.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Weapon, rangedAttack: 18, weaponType: WeaponType.Crossbow, speed: 6, requiredLevels: [{ skill: SkillName.Ranged, level: 1 }] } },
    { id: 'iron_crossbow', name: 'Iron Crossbow', description: 'A sturdy iron crossbow.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'iron', equipment: { slot: EquipmentSlot.Weapon, rangedAttack: 42, weaponType: WeaponType.Crossbow, speed: 6, requiredLevels: [{ skill: SkillName.Ranged, level: 26 }], ammoTier: 'iron' } },
    { id: 'steel_crossbow', name: 'Steel Crossbow', description: 'A reliable steel crossbow.', stackable: false, value: 500, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'steel', equipment: { slot: EquipmentSlot.Weapon, rangedAttack: 54, weaponType: WeaponType.Crossbow, speed: 6, requiredLevels: [{ skill: SkillName.Ranged, level: 31 }], ammoTier: 'steel' } },
    { id: 'mithril_crossbow', name: 'Mithril Crossbow', description: 'A lightweight and powerful mithril crossbow.', stackable: false, value: 1600, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Weapon, rangedAttack: 66, weaponType: WeaponType.Crossbow, speed: 6, requiredLevels: [{ skill: SkillName.Ranged, level: 41 }], ammoTier: 'mithril' } },
    { id: 'adamantite_crossbow', name: 'Adamantite Crossbow', description: 'A strong adamantite crossbow.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Weapon, rangedAttack: 78, weaponType: WeaponType.Crossbow, speed: 6, requiredLevels: [{ skill: SkillName.Ranged, level: 51 }], ammoTier: 'adamantite' } },
    { id: 'runic_crossbow', name: 'Runic Crossbow', description: 'A powerful runic crossbow.', stackable: false, value: 16200, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'runic', equipment: { slot: EquipmentSlot.Weapon, rangedAttack: 90, weaponType: WeaponType.Crossbow, speed: 6, requiredLevels: [{ skill: SkillName.Ranged, level: 61 }], ammoTier: 'runic' } },

    //Unfinished Crossbows
    { id: 'bronze_crossbow_unstrung', name: 'Bronze Crossbow (unf)', description: 'An unstrung bronze crossbow.', stackable: false, value: 90, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'bronze'},
    { id: 'iron_crossbow_unstrung', name: 'Iron Crossbow (unf)', description: 'An unstrung iron crossbow.', stackable: false, value: 225, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'iron'},
    { id: 'steel_crossbow_unstrung', name: 'Steel Crossbow (unf)', description: 'An unstrung steel crossbow.', stackable: false, value: 450, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'steel'},
    { id: 'mithril_crossbow_unstrung', name: 'Mithril Crossbow (unf)', description: 'An unstrung mithril crossbow.', stackable: false, value: 1440, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'mithril'},
    { id: 'adamantite_crossbow_unstrung', name: 'Adamantite Crossbow (unf)', description: 'An unstrung adamantite crossbow.', stackable: false, value: 2250, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'adamantite'},
    { id: 'runic_crossbow_unstrung', name: 'Runic Crossbow (unf)', description: 'An unstrung runic crossbow.', stackable: false, value: 8900, iconUrl: 'https://api.iconify.design/game-icons:crossbow.svg', material: 'runic'},

    // Bolts
    { id: 'bronze_bolts', name: 'Bronze Bolts', description: 'Bronze crossbow bolts.', stackable: true, value: 2, iconUrl: 'https://api.iconify.design/game-icons:spears.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 10, weaponType: WeaponType.Bolt } },
    { id: 'iron_bolts', name: 'Iron Bolts', description: 'Iron crossbow bolts.', stackable: true, value: 5, iconUrl: 'https://api.iconify.design/game-icons:spears.svg', material: 'iron', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 46, weaponType: WeaponType.Bolt } },
    { id: 'steel_bolts', name: 'Steel Bolts', description: 'Steel crossbow bolts.', stackable: true, value: 10, iconUrl: 'https://api.iconify.design/game-icons:spears.svg', material: 'steel', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 64, weaponType: WeaponType.Bolt } },
    { id: 'mithril_bolts', name: 'Mithril Bolts', description: 'Mithril crossbow bolts.', stackable: true, value: 20, iconUrl: 'https://api.iconify.design/game-icons:spears.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 82, weaponType: WeaponType.Bolt } },
    { id: 'adamantite_bolts', name: 'Adamantite Bolts', description: 'Adamantite crossbow bolts.', stackable: true, value: 35, iconUrl: 'https://api.iconify.design/game-icons:spears.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 100, weaponType: WeaponType.Bolt } },
    { id: 'runic_bolts', name: 'Runic Bolts', description: 'Runic crossbow bolts.', stackable: true, value: 300, iconUrl: 'https://api.iconify.design/game-icons:spears.svg', material: 'runic', equipment: { slot: EquipmentSlot.Ammo, rangedStrength: 115, weaponType: WeaponType.Bolt } },
];